### ISSUE TITLE
onDateChanged() event

### ISSUE THREAD

**Issue by doctor46** [prolificinteractive/material-calendarview#101]
Hello, onDateChanged() event(callback) is triggered only when the user selects new date. Is it possible to get a callback when the user clicks again on the selected date?
Thanks.

**Comment by dandc87** [comment]
This is something we can do when implementing multi-day selection (#52). But right now, I don't think it would make sense to add a new callback, or modify the existing one for this.

**Comment by VictoriaSlmn** [comment]
I need it to... I can't use your perfect calendarview without it(((

**Comment by dandc87** [comment]
This will make it into the 1.0 release. Please test out the beta (see #131)
