### ISSUE TITLE
View Draw issue

### ISSUE THREAD

**Issue by flamenvo** [prolificinteractive/material-calendarview#102]
@dandc87       How can I solve this problem
![360 0813_15_41_01](https://cloud.githubusercontent.com/assets/2337535/9247070/f93a073c-41e2-11e5-9ad1-56e488ff99e7.png)

**Comment by dandc87** [comment]
Hi @flamenvo, are you referring to the left and right months being drawn? This is being fixed in pull request #99 and the issue is being tracked with #84.

**Comment by dandc87** [comment]
Assuming that this is the same issue as #84, which is now fixed.
