### ISSUE TITLE
How to Change B.C. year on title to Buddha year ?

### ISSUE THREAD

**Issue by beergtx** [prolificinteractive/material-calendarview#1030]
<img width="315" alt="Screen Shot 2563-03-19 at 16 55 52" src="https://user-images.githubusercontent.com/53737236/77055082-f5878680-6a02-11ea-812e-fa31e25c2acc.png">

 Can I change B.C. year to Buddha year in a red circle?

**Comment by skl-songkiat** [comment]
@beergtx hl

Hi , you have solution right , can you explain how to convert year to bhudda please

**Comment by skl-songkiat** [comment]
I solve it 
We can setTitleMonth with call interface format in lib
