### ISSUE TITLE
 how to change the format selectDates to format (YYYY-MM-DD)

### ISSUE THREAD

**Issue by alvyfajri** [prolificinteractive/material-calendarview#1041]
I need a format [2020-04-01,2020-04-02,...]
not format [CalendarDay{2020-4-1},CalendarDay{2020-4-1},...]

`public void onClick(View view) {
                final List<CalendarDay> selectedDates = calendarView.getSelectedDates();

                if (!selectedDates.isEmpty()){
                    Toast.makeText(activity, selectedDates.toString(), Toast.LENGTH_SHORT).show();

                    Log.i(TAG, "onClick: "+selectedDates);

                }else {
                    Toast.makeText(activity, "No Selected", Toast.LENGTH_SHORT).show();
                }

            }`

**Comment by dexter-ops** [comment]
did you find an answer?
