### ISSUE TITLE
Remove the padding left and right

### ISSUE THREAD

**Issue by NeoDigi** [prolificinteractive/material-calendarview#11]
I'd like to remove the padding to the left and right.
You can see in the issue #9 the padding that I'm talking about.
It would be great to have the choice to remove it.

**Comment by dandc87** [comment]
@NeoDigi I'm not sure what padding you are referring to. Are you talking about the individual day views, or the calendar as a whole? Both are set to a certain size and then centered, no padding should be set.

**Comment by NeoDigi** [comment]
Ok I understood, then what I wanted to say/request would be to let us put the calendar width as we decide. I'll check this week end if this is troublesome to do.

**Comment by dandc87** [comment]
Now tracking resize feature with #13.
