### ISSUE TITLE
Today's and selected date's text color

### ISSUE THREAD

**Issue by RakeshPatil111** [prolificinteractive/material-calendarview#1100]
How to set text color for today's date and different text color for selected date?

**Comment by RakeshPatil111** [comment]
Found solution

**Comment by aashitshah26** [comment]
Whats the solution ?

**Comment by GCancinoH** [comment]
What was the solution, @RakeshPatil111 ?

**Comment by dungtmagithub** [comment]
What is the solution?

**Comment by RakeshPatil111** [comment]
Add custom decorator.
```
class CalendarDateTodayDecorator(val context: Context) : DayViewDecorator {

  override fun shouldDecorate(day: CalendarDay?): Boolean {
    return day == CalendarDay.today()
  }

  override fun isDecorationDynamic(): Boolean {
    return true
  }

  override fun decorate(view: DayViewFacade?) {
    view?.addSpan(ForegroundColorSpan(ContextCompat.getColor(context, R.color.red)))
  }
}
```
Set this decorator,
```
view.addDecorators(CircularDateSelectionDecorator(requireContext()), calendarDateDecorator)
```

I needed circle around selected date so created **CircularDateSelectionDecorator**, you can create other decorators depending upon your need.

```
class CircularDateSelectionDecorator(context: Context) : DayViewDecorator {

  private val drawable: Drawable = ContextCompat.getDrawable(context, R.drawable.event_calendar_date_selector)!!

  override fun shouldDecorate(day: CalendarDay): Boolean {
    return true
  }

  override fun isDecorationDynamic(): Boolean {
    return false
  }

  override fun decorate(view: DayViewFacade) {
    view.setSelectionDrawable(drawable)
  }

```
**NOTE** This solution is a 2 years old, may be will not work now.

**Comment by dungtmagithub** [comment]
> Add custom decorator.
> 
> ```
> class CalendarDateTodayDecorator(val context: Context) : DayViewDecorator {
> 
>   override fun shouldDecorate(day: CalendarDay?): Boolean {
>     return day == CalendarDay.today()
>   }
> 
>   override fun isDecorationDynamic(): Boolean {
>     return true
>   }
> 
>   override fun decorate(view: DayViewFacade?) {
>     view?.addSpan(ForegroundColorSpan(ContextCompat.getColor(context, R.color.red)))
>   }
> }
> ```
> 
> Set this decorator,
> 
> ```
> view.addDecorators(CircularDateSelectionDecorator(requireContext()), calendarDateDecorator)
> ```
> 
> I needed circle around selected date so created **CircularDateSelectionDecorator**, you can create other decorators depending upon your need.
> 
> ```
> class CircularDateSelectionDecorator(context: Context) : DayViewDecorator {
> 
>   private val drawable: Drawable = ContextCompat.getDrawable(context, R.drawable.event_calendar_date_selector)!!
> 
>   override fun shouldDecorate(day: CalendarDay): Boolean {
>     return true
>   }
> 
>   override fun isDecorationDynamic(): Boolean {
>     return false
>   }
> 
>   override fun decorate(view: DayViewFacade) {
>     view.setSelectionDrawable(drawable)
>   }
> ```
> 
> **NOTE** This solution is a 2 years old, may be will not work now.

Thank you
