### ISSUE TITLE
Option to disable swiping between months

### ISSUE THREAD

**Issue by balazsgerlei** [prolificinteractive/material-calendarview#111]
I really like the library, but I have a simple UX issue when I try to integrate it in my application. I would like to display the calendar in a viewpager, so the swiping is used to change pages. But this lib uses the swipe gesture to change between months, so it currently behaves really odd. The arrows at the top would be sufficent to change months in my use case, so could you provide an option (either from code or from xml) to disable the lib's listening to swipe gestures?

Thank you in advance.

**Comment by dandc87** [comment]
This is coming thanks to #145

**Comment by ticofab** [comment]
+1, thanks!

**Comment by ticofab** [comment]
Hi, and thanks for this library. I have the same issue - my calendar view is embedded in a ViewPager. I just upgraded to 1.1.0, and disabled paging on the calendar. Unfortunately what happens is exactly the opposite of what I was hoping for: the calendar doesn't scroll between months but it still consumes the gestures: my "outer" view pager doesn't scroll either. At the same time, setting the paging to false also disables the arrows, which I wanted to be the only way to change months. 

What I would love to use is a calendar view where the only way to change between months is via the arrows. Do you think this would be something possible?

**Comment by dolphinziyo** [comment]
Hi, I 'm looking for the same feature. I would like to only allow month switching using the arrows and disable the swipe gesture from the calendar.
I have an approach by extending the "MaterialCalendarView" and disabling touch when moving on calendar, this way i can switch months using the arrows and the calendar swipe is disabled, but now my parent ViewPager doesn't swipe if I move pressing over the calendar.
Any help would be really appreciated.
Thank you for this library, is great!!¡¡

**Comment by dolphinziyo** [comment]
I finally solved it, let me tell you how to do it.
First of all you need to create your custom "Material Calendar View" and "Custom View Pager" by simply extending them (and creating its constructors, both of them).
In the "Custom Material Calendar" you have to implement the "onInterceptTouchEvent" and return true when the action received is "ACTION_MOVE" (Constant 2), doing this you disable the swipe from the calendar.
To make your ViewPager to work as expected even swiping over the Calendar, in your "Custom View Pager" you need to implement the "onInterceptTouchEvent" again and there you call the "onTouch" method passing the received event and then return the response from the call to "super.onInterceptTouchEvent(event);".
By this way you have the calendar working with all its features but with the swipe disabled.

**Comment by ticofab** [comment]
hey @dolphinziyo , thanks for your research. Unfortunately what I'm finding is that this way clicking on the arrows or on the days becomes tricky. I'd rather hope in a proper fix from within the library (or try to contribuite to it myself as I find time).

**Comment by dolphinziyo** [comment]
When I did it I didn't notice any issue when clicking the arrows or the days, but I will try it again. 
Of course, a solution from the library creators would be better but meanwhile I will try to get a good solution, I will tell you

**Comment by dandc87** [comment]
I'm going to consider the buttons becoming disabled a bug, I thought I had fixed that before the previous release. Fix is now in the `future-1.x` branch

**Comment by dolphinziyo** [comment]
Is it possible to know a release estimation date for the future branch which includes this feature? I would like to know if I can include this calendar in my app next update. 
@ticofab is right and my "fix" doesn't work well in some devices
Thank you very much

**Comment by Zamuzo** [comment]
Hi,
I have the same problem and i want to include it in my app.
@dolphinziyo thanks for your previous research and i would like to know if you have found a stable solution ?
Thanks in advance

**Comment by dolphinziyo** [comment]
@Zamuzo I couldn't do more research because i am refactoring my whole app. But if I achieve a temporary fix I will let you know.
