### ISSUE TITLE
Change month by click on different month days

### ISSUE THREAD

**Issue by botty87** [prolificinteractive/material-calendarview#116]
Is possible to change the month by click on a different month day? Maybe it's already possible and I don't have found how, but the others days seems click disabled.

Many thanks.

**Comment by dandc87** [comment]
There isn't anything to do this, and it would be complex to change it. Right now the views for days from previous and next months are disabled entirely, which disables clicking and changes the text color automatically. I might be able to include this with #88; we will have to see.

**Comment by botty87** [comment]
Many thanks! Anyway great work, my compliments!

**Comment by Charrondev** [comment]
I will be working on this in the next couple days and will make a pull request. Thinking of either adding another attribute (disabledViewsAreSelectable) with the same possible values as showOtherDates).

**Comment by botty87** [comment]
Wonderful! I think your addition idea could be nice. Well done, thanks!

**Comment by Charrondev** [comment]
Well I did most of the work in getting this functional. I structured it pretty similarly to showOtherDates, but I'm having an issue where when it's applied programatically, it only applies to the nearest couple of months, and when I scroll back to the months it was working on, the affect has disappeared.
