### ISSUE TITLE
Setting background to DayViewFacade bug

### ISSUE THREAD

**Issue by KonstantinKeshikov** [prolificinteractive/material-calendarview#118]
Hi.

I'm trying to set a background to current date (today) using decorator. I'm setting a background drawable using dayViewFacade.setBackgroundDrawable. But this produces the result on attached screenshot (the red frame should be only on day 7). This happens only on version 0.8.+. I tried the same on version 0.7.0 and everything was correct.

P.S. I'm using emulator with API 16 (4.1.1)

![bug](https://cloud.githubusercontent.com/assets/12651833/9711404/540d74c4-557e-11e5-8ac4-c4a1dcf0231c.jpg)

**Comment by dandc87** [comment]
I'm not able to reproduce this. What kind of drawable are you using? Or could you post some code?
