### ISSUE TITLE
Change dot span colour when day selected?

### ISSUE THREAD

**Issue by xbroak** [prolificinteractive/material-calendarview#120]
I'm sure there is a way to do this but i cannot find it! 

I have two decorators, one for a custom background for selection and the other is the EventDecorator for placing a dot span. My problem however is that the dot span and the selected background are the same color, such that when the day is selected, the dot can no longer be seen. I need a way of changing the color of the dot when the day is selected to white. Is that possible?

**Comment by dandc87** [comment]
You are going to have to add third decorator which draws the selected dot, and as long as you add it after the other decorators it should draw on top. I wish there was a more elegant solution to this. I looked into trying to change `DotSpan` to accommodate selected state, but it looks like there isn't a way to get state into a span and also have custom drawing code :disappointed:

**Comment by xbroak** [comment]
Should be left open till we find a solution surely? :)

**Comment by dandc87** [comment]
@xbroak Sorry was clicking quickly

**Comment by xbroak** [comment]
Ah :) No problem!

**Comment by xbroak** [comment]
Why was this closed? Has a solution been implemented?
