### ISSUE TITLE
Change Calendar row

### ISSUE THREAD

**Issue by Thewhitelight** [prolificinteractive/material-calendarview#121]
i want change calendar row is two line  ,how to modify.

Many thanks.

**Comment by dandc87** [comment]
I'm sorry, but I'm not sure what you are asking.

**Comment by Thewhitelight** [comment]
DEFAULT_MAX_WEEKS=2  calendarview can Full display

**Comment by dandc87** [comment]
Ok, this is similar to #77. We only plan to support displaying one month. The calendar uses horizontal swiping, and supporting arbitrary rows would be a large architecture change that I don't feel a good idea. If you feel differently, please "+1" on #77 and this may be implemented, some day.
