### ISSUE TITLE
Multiple dates background change

### ISSUE THREAD

**Issue by vaishalshah** [prolificinteractive/material-calendarview#124]
I want to change background of some of the dates of month to show on which dates user was active on app. These are just indicators and cannot be changed by user. How do i do that?

**Comment by dandc87** [comment]
You can use Decorators. Please see the (DayViewDecorator)[https://github.com/prolificinteractive/material-calendarview#dayviewdecorator] section of the readme and the `BasicActivityDecorated.java` sample activity.

**Comment by vaishalshah** [comment]
Thanks. Works fine now
