### ISSUE TITLE
How to refresh the Decorators?

### ISSUE THREAD

**Issue by don59** [prolificinteractive/material-calendarview#128]
I have added the decorators on activity create like the sample.
And I need refresh the decorators status or remove decorators or change the color when I add a new event or delete event.Please help,Thanks!

**Comment by dandc87** [comment]
To remove, you can call `removeDecorator()` or `removeDecorators()`. And to refresh decorators after one has changed, you call `invalidateDecorators()`.

**Comment by don59** [comment]
Thanks

**Comment by jayshildave** [comment]
I know this is closed. But in case you feel that your view is not getting updated after removing decorators. Check the data set which was passed. I was passing old data set and was wondering this functionality is not working. May help someone looking specifically at this.

**Comment by devendraPatel2808** [comment]
Yes i faced issue
