### ISSUE TITLE
Make Resizeable

### ISSUE THREAD

**Issue by dandc87** [prolificinteractive/material-calendarview#13]
Right now, the day view is hard coded (44dp). This should be allowed to be set via XML and code.

We might need to switch from using xml internally for layouts.

Should we also add an option for auto-resizing? Like how `android:adjustViewBounds` works for ImageViews?

Should we do anything special with text sizes if we allow resizing?

**Comment by dotnick** [comment]
Auto-resizing would be awesome; I had trouble trying to get the calendar to show correctly in a dialog.

**Comment by wisekingokok** [comment]
How to auto-resizing? Is there any guide for it？
