### ISSUE TITLE
How to show the week view?

### ISSUE THREAD

**Issue by don59** [prolificinteractive/material-calendarview#130]
How to show the week view when touch up?
like this:
![Image of WeekView](http://a1.eoeandroid.com/attachment/forum/201501/20/092629d88ddqz7q7eqxccy.gif)

**Comment by dandc87** [comment]
@don59 as stated in other issues (#49, #77), this feature is not, and probably will never be, supported in this library.

**Comment by don59** [comment]
ok,got it,thanks
