### ISSUE TITLE
Horizontal tile spacing

### ISSUE THREAD

**Issue by dsn5ft** [prolificinteractive/material-calendarview#132]
Hi @dandc87, I just started experimenting with the library (versions 0.8.1 and 1.0.0-beta1) and I think it's awesome! I'm wondering if it's possible to set the tile size and still make the view fill all of the horizontal space. Currently, if I set the tile size to something smaller than the default 44dp, the tiles group together in the center, leaving padding on the left and right sides of the calendar. Basically, I'm trying to reduce the overall height of the calendar view, while still making it fill the horizontal space of the screen.

This is what I'm doing in XML:

    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

And then in Java:

    calendarView.setTileSizeDp(38);

Here's a screenshot of what the calendar looks like:

![screenshot_2015-09-20-17-54-19](https://cloud.githubusercontent.com/assets/1420597/9983221/56cf1f56-5fc3-11e5-9e15-0db7af86ec73.png)

And here's a screenshot of roughly what I'm going for:

![screenshot_2015-09-20-18-00-00](https://cloud.githubusercontent.com/assets/1420597/9983222/5b4f9dbc-5fc3-11e5-8fd2-d31c1af54a7e.png)

Thanks in advance!
-Dan

**Comment by Charrondev** [comment]
I will be looking into this in the coming week, so expect a pull request soon.

**Comment by ChrisDolge** [comment]
Hi

First this is an awesome library :+1:  . Is there already a solution for this problem?  I also trying to reduce the overall height of the calendar view but it doesn't work :(

**Comment by MingLi-EB** [comment]
Hi
I have the same problem.I also trying to reduce the height of the topbar in the MaterialCalendarView.I changed the LayoutParams for the topbar,but it did not work.

**Comment by lavelas** [comment]
To stretch the width of the calendar should:
1. The measure TileSize reduce by a factor of (in the method onMeasure class MaterialCalendarView) int childHeightMeasureSpec = MeasureSpec.makeMeasureSpec ((int) (p.height * (measureTileSize / 1.5)), MeasureSpec.EXACTLY);
2. The same is done in the MonthView int childHeightMeasureSpec = MeasureSpec.makeMeasureSpec ((int) (measureTileSize / 1.5), MeasureSpec.EXACTLY);
3. Something come up with the background (stretched into an oval)

**Comment by ChrisDolge** [comment]
@lavelas  thx for help ;-)

**Comment by chrissd23** [comment]
Fixed

**Comment by lavelas** [comment]
@chrissd23 how?

**Comment by chrissd23** [comment]
You need to add minimizeHorizontalTileSpacing in xml file  and thats it

**Comment by limitky** [comment]
Hello guys! I want to use the library, and put the changes that @lavelas says, but i want to know, 
i have to clone the repository on my local machine and then just made the change? if this is the case how can i use the library local?, thanks !

**Comment by AntaresR** [comment]
Please could you post a sample on how to do this? the monthView method is private. I m not the most savyy programmer :(

**Comment by NageswaraRaoCH** [comment]
@chrissd23  i am also having the same issue to reduce height,increase width,you are guided add minimizeHorizontalTileSpacing in xml,I didn't find this option in my xml,can you guide me with a peace of code,your response will appreciated.

**Comment by chrissd23** [comment]
@NageswaraRaoCH  you need to check out my branch tile_spacing. My PR wasn't merged.

After checking out , you can add ` app:mcv_minimizeHorizontalTileHeight="your value"` to your xml. So and that's it.

Hope it helps

**Comment by NageswaraRaoCH** [comment]
@chrissd23  Thanks for responding,i was added in my xml file   app:mcv_minimizeHorizontalTileHeight="50dp". my android studio says ,No resource identifier found for attribute 'mcv_minimizeHorizontalTileHeight' in package

**Comment by chrissd23** [comment]
@NageswaraRaoCH checkout this branch [https://github.com/chrissd23/material-calendarview/tree/tile_spacing](branch https://github.com/chrissd23/material-calendarview/tree/tile_spacing)

**Comment by chrissd23** [comment]
@NageswaraRaoCH you need to add an integer value like 2 without dp in xml file

**Comment by tommy-le** [comment]
Hi chrissd23
How can I checkout your branch? I did it in my SourceTree and it says Forbidden
Thanks

**Comment by tommy-le** [comment]
Hi @chrissd23
I managed to get your source code.
However I see the background circle (white circle) now does not locate in the center of the dayview
Can you give me an advice?
![fullsizerender](https://cloud.githubusercontent.com/assets/11551883/14549514/aa188eb6-02ea-11e6-8f00-ab415b6fb9b6.jpg)
Thanks

**Comment by chrissd23** [comment]
@tommy-le I add your values to my calenderview and the circle are located to the center of the dayview. 

Did you check out the last commit of this branch ?

**Comment by tommy-le** [comment]
@chrissd23: I cannot checkout your branch as it says Forbidden, I can only download the zip file from the page https://github.com/chrissd23/material-calendarview/tree/tile_spacing

Could you send me the latest source code of your branch to my email lat233@gmail.com?
Thanks

**Comment by chrissd23** [comment]
@tommy-le 

You can try this dependency ` compile 'com.github.chrissd23:material-calendarview:0536edc503'`

if it's not working. Then try to fork my project and build this project with jitpack.io from your repository.

Hope it helps.

**Comment by quentin41500** [comment]
@chrissd23 thanks for working on this issue and for your PR. It's almost working perfectly, but shows some issue on Lollipop. We are looking in a fix, but feel free to help us and fix the different issues that happens on Lollipop

**Comment by ajithkpistar** [comment]
pls give step by step info by anyone for implement to removing the tile spaing wen setthe tile size...i am getting the spacing between the calendar

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!

**Comment by m1ga** [comment]
I'm using 1.4 of the library and want the reduce the height of the calendar. So I set `setTileHeight()` to a value and it is working fine besides my custom `DayViewDecorator` with a `OvalShape()` as a drawable. This is stretched like the image in https://github.com/prolificinteractive/material-calendarview/issues/132#issuecomment-160551109
The normal highlight (by click) is perfectly round.

What do I need to set to get the full width but a smaller height?

**Comment by maheshsuthar93** [comment]
hello guys i want to clear the decorated tiles by selected date color any one have idea how to to do this??

**Comment by maheshsuthar93** [comment]
its overlap the decorated date by selected date color
