### ISSUE TITLE
View to bitmap lose dayView selectBackground.

### ISSUE THREAD

**Issue by anysome** [prolificinteractive/material-calendarview#134]
![device-2015-09-22-123614](https://cloud.githubusercontent.com/assets/233960/10011028/f7c66810-6126-11e5-9dd0-b2279971fe39.png)
![device-2015-09-22-123701](https://cloud.githubusercontent.com/assets/233960/10011029/fa82eaba-6126-11e5-940d-2c93683ebffc.png)
Android system snap is ok.

**Comment by dandc87** [comment]
Try setting a custom text appearance for days. Call `setDateTextAppearance()` or `mcv_dateTextAppearance` where the style you use is something like this:

```xml
<style name="CustomDayTextAppearance" parent="android:TextAppearance.DeviceDefault.Small">
    <item name="android:textColor">@android:color/black</item>
</style>
```

The important part is setting the text color to always be black. The default will lighten when the day is selected.

**Comment by anysome** [comment]
I use two DayViewDecorators to decorate some other days. 
One use DotSpan, everything work well.
Another DayViewDecorator call setBackgroundDrawable with ring shape drawable,
ui look well, but to bitmap losing shapes. (Only one shape left on a wrong day)

BTY, the current selected day is always ok, thanks a lot!

**Comment by dandc87** [comment]
@anysome can you post the code for the second decorator and the ring drawable?

**Comment by anysome** [comment]
Yes!
```
result[1] = new DayViewDecorator() {

                private final Drawable background = AndroidUtil.getDrawable(GoalCalendarActivity.this, R.drawable.round);

                @Override
                public boolean shouldDecorate(CalendarDay day) {
                    return dones.contains(day);
                }

                @Override
                public void decorate(DayViewFacade view) {
                    view.setBackgroundDrawable(background);
                }
            };
```
And drawable
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="ring"
    android:innerRadius="0dp"
    android:thickness="16dp"
    android:useLevel="false">
    <solid android:color="@color/accent"  />
</shape>
```
