### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by sanyok7734** [prolificinteractive/material-calendarview#137]
Hi.
I would like to be able to resize the only vertically. And it was the width of the entire screen.

![image](https://cloud.githubusercontent.com/assets/5102102/10086803/116e13e6-6319-11e5-87b3-2dbf7fc4996f.png)

You can implement it?

**Comment by dandc87** [comment]
@sanyok7734 are you asking for the same thing as #132?

**Comment by sanyok7734** [comment]
@dandc87 Yes
