### ISSUE TITLE
multiple drawables in 1 decorator

### ISSUE THREAD

**Issue by prashantwosti** [prolificinteractive/material-calendarview#148]
How can i use multiple drawables in one decorator?
For example,  I want to set a decorator that covers two or more dates. I have to set drawable1 to the starting element and drawable2 to all the element in between and drawable3 to the last element.
Is it possible? 
Any help is highly appreciated.

Thanks

**Comment by dandc87** [comment]
Hey @prashantwosti you will need to use 3 different decorators, on for each of your drawables.
