### ISSUE TITLE
Hide day names line

### ISSUE THREAD

**Issue by RenanLazarotto** [prolificinteractive/material-calendarview#150]
Hi there!
I noticed that there is a way to hide the top bar, but there is no way to hide the day names line. I am missing something or this isn't implemented?

**Comment by dandc87** [comment]
Hey @RenanLazarotto, this isn't implemented yet

**Comment by markoregano** [comment]
Hey,
Can you add the day names in another layout, so that we can customize its properties like TextSize/Color/BackgroundColor/hide

**Comment by quentin41500** [comment]
Hi @markoregano, you can actually do all of this using `mcv_headerTextAppearance` or `setHeaderTextAppearance`, beside the visibility. @markoregano @RenanLazarotto setting visibility of the header is something that you still need ?

**Comment by Aissa-H** [comment]
@quentin41500 It will be great if you can add this kind of function `setWeekDaysVisible(boolean)`

**Comment by quentin41500** [comment]
Will be available in the latest version
