### ISSUE TITLE
Make left / right padding of calendar swipe-able. 

### ISSUE THREAD

**Issue by caltseng** [prolificinteractive/material-calendarview#153]
I decreased the tile size but kept the width of the calendar view to match_parent. This results in padding on the left and the right of the calendar, but this margin is can't be swiped like the body of the calendar is. It would be great if this padding could be swiped to switch months. 

Thanks!

**Comment by dandc87** [comment]
Hey @caltseng, when you set a tile size the calendar will completely ignore the `match_parent`. So the padding you see isn't actually part of the calendar. This is new, as of version 0.8.0.

**Comment by bschnack** [comment]
Is there any way to get the functionality of having the sides be swiped and changing the tile size? Our problem is that the calendar is taking too much of the screen for our liking so we would like it to be a bit smaller but then it makes it so we can no longer swipe from the sides and that is less than ideal.

**Comment by caltseng** [comment]
@dandc87 Setting the tile size does not completely ignore the match_parent. We are using version 1.1.

With a smaller tile size, when using width = match_parent, the entire width of the screen has the same background color as the calendar and the calendar is centered. When using wrap_content, the calendar is narrower (and is not centered by default when in RelativeLayout) and the uninhabited space is the background of the container. 

I tried the following to pass the changes from the container view into the calendar, but for some reason it only works for the left side and not the right side. When setting a breakpoint, MonthPager.onInterceptTouchEvent() is only reached when clicking in the left and not the right. 

            mMaterialCalendarContainer.setOnTouchListener(new View.OnTouchListener() {
                @Override
                public boolean onTouch(View v, MotionEvent event) {
                    mMaterialCalendarView.dispatchTouchEvent(event);

                    return true;
                }
            });

**Comment by caltseng** [comment]
When we applied the above code, clicking left of the calendar view (in the container view) selects the nearest date. However, this behavior does not happen right of the calendar view.

**Comment by caltseng** [comment]
@dandc87 Please check out the PR I just submitted  - https://github.com/prolificinteractive/material-calendarview/pull/173

This should fix the issue. To see the difference, set the tile size for one of the examples to be pretty small and swipe the sides. Also, set the padding of the sample activities to be 0 and the calendar will be scrollable from the very edges of the screen, making a very natural motion. 

Please let me know if you have any questions or if there's anything blocking this fix from being checked in. This is an important issue for us. Thanks.
