### ISSUE TITLE
java.lang.RuntimeException: Unexpected exception in dex writer thread

### ISSUE THREAD

**Issue by hirakchhatbar** [prolificinteractive/material-calendarview#155]
Getting this exception when I run the app. 
Tried these things.

1) dexOptions {
        incremental true
        javaMaxHeapSize "4g"
    }

2) multiDexEnabled true

3) compile ('com.prolificinteractive:material-calendarview:1.0.1'){
        exclude module: 'support-v4'
    }

Still not working.

**Comment by dandc87** [comment]
I'm not sure how to help. No one else has reported this issue, and my internet searches only suggest the fixes you've tried.
