### ISSUE TITLE
Blink the calendar view

### ISSUE THREAD

**Issue by VivekKumarApps** [prolificinteractive/material-calendarview#156]
Hello,

When I am adding a material-calendarview in the relativelayout, it is working fine but when removed from the relativelayout or setvisibility to gone. Then the calendarview blink with the selected view color.

Please tell, what I need to do? I am waiting for your response.

Thanks,
Vivek Kumar

**Comment by dandc87** [comment]
Hey @VivekKumarApps, I'm not able to replicate this. What device(s) and version(s) of Android do you see this on? And what customization options do you have set on the calendar (decorators, etc)?
