### ISSUE TITLE
How select multiple dates?

### ISSUE THREAD

**Issue by VivekKumarApps** [prolificinteractive/material-calendarview#157]
Hello,

I need to set multiple dates as previous selected. Please tell me what I need to do?

Thanks,

**Comment by dandc87** [comment]
1. Make sure that the calendar is in multi-selection mode
2. For each day you want to select, call `calendar.setDateSelected(myDay, true)`. It accepts Dates, Calendars, or CalendarDays

**Comment by Aamirkhan2610** [comment]
I have a list of dates for month, i want to highlight that all dates in calendar,i don't want to use multiple selection, just want to highlight some dates, how to do that?
