### ISSUE TITLE
Change size of span 

### ISSUE THREAD

**Issue by byanjati** [prolificinteractive/material-calendarview#159]
Does new DotSpan(5, color) and new DotSpan(1,color) have a difference in radius ? cause when i implement those Object into dayViewFacade, i get the same size of DotSpan around the date. 

I also want to set the size of span ( drawable / dotspan ) but where can i found the setting of span size at this lib ?

**Comment by dandc87** [comment]
Hi @byanjati, I just tested changing the size of the DotSpan and it works. The constructor takes a radius in pixels, so if you are on a high density device it might look the same.

Could you post the code for your decorator? That might help.
