### ISSUE TITLE
Calendar days not displaying when Calendar is in RecyclerViews, but title shows up. 

### ISSUE THREAD

**Issue by caltseng** [prolificinteractive/material-calendarview#160]
I'm adding the calendar as an item in a recycler view. The header shows up correctly (with < Month > ), but none of the dates below appear. 

For some reason, when I turn off the screen and turn it back on, the dates show up correctly. Has anyone else run into this? I'm not sure if I'm doing something wrong, but it is very peculiar to me that the header shows up and the dates don't.

**Comment by quentin41500** [comment]
@caltseng Works for us in recyclerViews with last version. Feel free to reopen if you still see this issue
