### ISSUE TITLE
add parameters to Decorate method to make it more flexible

### ISSUE THREAD

**Issue by mishindmitriy** [prolificinteractive/material-calendarview#161]
- TextView dateText (e.g. for changing textColor to black, if background white)
- boolean disable (for decorate disable days another background or textColor)

In my case, i need set Today white background and setTextColor to black, if it enabled. I can not do it now. http://joxi.ru/QeAOe7XiN6aYmo.jpg

Thank you.

**Comment by dandc87** [comment]
For changing text color, you should be able to use a [`ForegroundColorSpan`](http://developer.android.com/reference/android/text/style/ForegroundColorSpan.html). Ex:

```java
dayViewFacade.addSpan(new ForegroundColorSpan(Color.WHITE));
```

I'm not sure what you are asking for in your second bullet point. DayViewFacade already has methods to set a background and disable days. If you're looking to decorate a set of days differently than another set, you can always add another decorator.

**Comment by mishindmitriy** [comment]
You helped me, thank you. I will be carefully reading the documentation)
