### ISSUE TITLE
Custom selection of date range

### ISSUE THREAD

**Issue by juliakvashyna** [prolificinteractive/material-calendarview#162]
Hi! Thanks for this amazing calendarview. I used it my project, but cant understand how to implement selection dates like in attach image.  I have decorator with circle and rectangle drawables.
![calendar](https://cloud.githubusercontent.com/assets/5637436/10765222/544d5b4c-7cda-11e5-9e04-32b849d92b8b.png)

**Comment by dandc87** [comment]
@juliakvashyna you didn't attach an image

**Comment by juliakvashyna** [comment]
@dandc87 sorry, thanks!

**Comment by dandc87** [comment]
@juliakvashyna There isn't an easy way to do this. Basically, you will need to implement 3 decorators (left, center, and right selections) and manually determine which days should be decorated with what decorator appropriately.

[Here is documentation on decorators](https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md)

**Comment by juliakvashyna** [comment]
Thanks! I will try)

четверг, 29 октября 2015 г. пользователь Adam Koski написал:

**Comment by iad24** [comment]
@dandc87 Hi dan. did u managed to do this? Is it possible to share your code?

**Comment by saurabhmdh** [comment]
Hi juliakvashyna, Can you share us code for this implementation.

**Comment by harshitaahuja** [comment]
I also want to achieve same decorations on a range. Can anyone help.

**Comment by hitesh-dhamshaniya** [comment]
@HalimOmar : Did you find the way to decorate range and selected dates?
@saurabhmdh : Have you found any way or code for same?
Anyone has implement please share.

**Comment by sampengilly** [comment]
The only way to do this still is to specify three different decorators as mentioned above (left, middle, and right) and apply/remove those as necessary. For the purposes of date range selection I feel that decorators shouldn't be used (and instead should be reserved for stuff like event dots and other such decoration). 

The idea of start, middle, and end range selection drawables should probably be migrated inside the library and exposed via some attributes on the view. Would be interested in seeing this reopened and discussed as it seems to be a common problem
