### ISSUE TITLE
Displaying list of events (dots) on dates (using Parse online datastore)

### ISSUE THREAD

**Issue by myatthiha** [prolificinteractive/material-calendarview#163]
I'm getting a list of objects from Parse database, which contains int day, int month and int year. How can I use those three data to show dots in the calendar?

**Comment by quentin41500** [comment]
@myatthiha You can use `CalendarDay.from()` method. You can do this:

ArrayList<CalendarDay> dates = new ArrayList<>();
  for (ParseDateObject date : list) {
                dates.add(CalendarDay.from(date.year, date.month, date.day));
  }
  widget.addDecorator(new EventDecorator(Color.RED, dates));

Closing this issue, feel free to reopen if you want more info.
