### ISSUE TITLE
CalendarDay(Calendar calendar)  - @Deprecated, How now create CalendarDay?

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#165]
CalendarDay(int year, int month, int day) is Deprecated
my code:
date = CalendarDay(1999, 1,1);
widget.setCurrentDate(date)
widget.setDateSelected(date);

how can I optimize it?

**Comment by dandc87** [comment]
Hey @kamilwlf, factory methods were added awhile ago. In your case you would use `CalendarDay.from(year, month, day)`.

[See the javadoc here](https://prolificinteractive.github.io/material-calendarview/com/prolificinteractive/materialcalendarview/CalendarDay.html)
