### ISSUE TITLE
Picking Multiple Dates from the Calendar

### ISSUE THREAD

**Issue by artur8906** [prolificinteractive/material-calendarview#169]
Hello.
I need to pick multiple dates from the calendar and highlight  that dates.
I have tried, but couldn't did. Please. if you can help me!
Thanks

**Comment by dandc87** [comment]
Call `setSelectionMode(MaterialCalendarView.SELECTION_MODE_MULTIPLE)` to enable multiple selection. Then call `setDateSelected(date, selected)` to select or un-select certain dates. See the [date selection section in the customization docs](https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#date-selection) for more.
