### ISSUE TITLE
Cannot find weekDayLabels and monthLabels attr

### ISSUE THREAD

**Issue by yolapop** [prolificinteractive/material-calendarview#17]
Hi, in my Android Studio, it could not resolve these attributes.

    app:weekDayLabels="@array/custom_weekdays"
    app:monthLabels="@array/custom_months"

Although this attribute was resolved

    app:weekDayTextAppearance="?android:attr/textAppearanceMedium"

Thank you for this nice library.

**Comment by yolapop** [comment]
> Set the color of the date selector. By default this is the color set by ?android:attr/colorPrimary on 5.0+ or ?attr/colorPrimary from the AppCompat library.

Also, it seems on my 5.1 device, `selectionColor` by default picks on `colorAccent` rather than `colorPrimary`.

I was using `style.xml`

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/teal_500</item>
        <item name="colorPrimaryDark">@color/teal_700</item>

        <item name="colorAccent">@color/teal_a200</item>
    </style>

And `layout_calendar.xml`

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.prolificinteractive.materialcalendarview.MaterialCalendarView
            android:id="@+id/calendar_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:showOtherDates="true"
        />

    </LinearLayout>

And the result: `selectionColor` uses `teal_a200`

![screenshot_2015-03-12-10-13-37 1](https://cloud.githubusercontent.com/assets/2100294/6611648/658ce578-c8a1-11e4-83d7-e7b773d83c73.png)

**Comment by dandc87** [comment]
Hey @yolapop, I'm sorry about both of these.

The changes for custom labels were merged to master, but not released. If you update to version 0.2.5, you should have the attributes.

For the selection color, the library uses `colorAccent` by default and I've update the README to indicate that. If you want to use `colorPrimary`, you can use `app:selectionColor="?attr/colorPrimary"` (or `?android:attr/colorPrimary"`)
