### ISSUE TITLE
How to change background color of the header?

### ISSUE THREAD

**Issue by sanjayharan** [prolificinteractive/material-calendarview#170]
Hey,

I want to change background color of the header view where the month title is showing and left and right arrow showing.
Can you tell me how can I change it?

Thanks

**Comment by dandc87** [comment]
Hey @sanjayharan, there currently isn't a way to do that. RIght now, you could either 

1. Hide the top bar using `setTopbarVisible(false)` and implement your own
2. Create a background for the entire calendar that colors only the top bar area

**Comment by jagatappv** [comment]
Thanks for the support

I have added custom header, but I don't know how can i change next month and previous month on the click of arrows programmatically?

Thanks again

**Comment by tsuharesu** [comment]
@dandc87 how could one do option 2? I am having the same "problem", but I want to color weekday.
