### ISSUE TITLE
Change radius of circle drawable bg

### ISSUE THREAD

**Issue by tobiasheine** [prolificinteractive/material-calendarview#171]
First of all thanks for this the awesome lib. Works like a charm. However I am missing the option to style the DayView exactly for our needs. We're using a DayViewDecorator to provide a different bg for special days. 
Here's a screenshot of what the calendar looks like atm:
![calendar](https://cloud.githubusercontent.com/assets/1046688/10995049/6a38342a-847a-11e5-9675-56991046b200.png)

What we want to do is to reduce the radius of the circle drawable in general (also for non decorated DayViews). Changing the tile doesn't help me since it affects the dimensions of the whole view.

**Comment by tobiasheine** [comment]
We meanwhile found a workaround and provided a custom selection drawable for each DayViewDecorator. Would be great if setting a selection drawable would be exposed to the Calendar itself, similar to com.prolificinteractive.materialcalendarview.MaterialCalendarView#setSelectionColor

**Comment by dandc87** [comment]
Yes, for now, you will need to use a decorator for a custom drawable

**Comment by Sermilion** [comment]
@tobiasheine I am in need of solution for that as well. Could you please provide me a sample code for generating custom drawable and setting it? 
I am trying to use m.amulyakhare.textdrawable like this:
```java
 TextDrawable drawable = TextDrawable.builder().beginConfig()
                .width(20)
                .height(20)
                .endConfig()
                .buildRound(null, Color.parseColor(color));
        view.setBackgroundDrawable(drawable);
```
But this does not change the radius. Thank you.
