### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by jcaruso001** [prolificinteractive/material-calendarview#172]
Is there a way to change the color of each day dynamically? I.E. Oct 1st Red, Oct 2nd Blue...

**Comment by dandc87** [comment]
Hey @jcaruso001 you can use the [decorator api](https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md). You will need to create one decorator per color and then supply the logic for `shouldDecorate()`
