### ISSUE TITLE
Problem with margin

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#174]
my code:
http://codepaste.net/rdhpxu
result:
![calendar](https://cloud.githubusercontent.com/assets/7765963/11116085/58b9a796-8930-11e5-9e66-862416950860.jpg)

I expect that there will not be an empty space between MaterialCalendarView and TextView

**Comment by ekchang** [comment]
By default, MaterialCalendarView will take up 6 rows to display any valid calendar month (take a look at January 2016 for an example of a 6 row month). This causes 5 row months to show a blank row below it so the view layout does not change.

If you want the calendar to shrink and add/subtract that row as needed, use `MaterialCalendarView.setDynamicHeightEnabled(true)`.
