### ISSUE TITLE
Change EventDecorator's date Text Color

### ISSUE THREAD

**Issue by rajesh130jadav** [prolificinteractive/material-calendarview#177]
How can i change all Event's date Text color not all dates color using EventDecorator or other way?

**Comment by xu6148152** [comment]
I have the same problem.

**Comment by rajesh130jadav** [comment]
@xu6148152 can you show your code?

**Comment by xu6148152** [comment]
@rajesh130jadav 
[this pr](https://github.com/prolificinteractive/material-calendarview/pull/183)

**Comment by ekchang** [comment]
In the sample `EventDecorator` you can add a ForegroundColorSpan during `decorate`:
````
@Override
    public void decorate(DayViewFacade view) {
        view.addSpan(new DotSpan(5, color));
        view.addSpan(new ForegroundColorSpan(Color.GREEN)); // replace with your own color
    }
````
Closing.
