### ISSUE TITLE
how to change dayView margin 

### ISSUE THREAD

**Issue by Thewhitelight** [prolificinteractive/material-calendarview#178]

**Comment by wisekingokok** [comment]
I have a question same with this.

**Comment by xu6148152** [comment]
you can modify DayView, it has a tmpRect, can modify tmpReact using inset(x, y) to change the size of tmpReact. I have resolved.

**Comment by Thewhitelight** [comment]
@xu6148152 thanks

**Comment by xu6148152** [comment]
You may change some other code, i has been disable SelectionColor.
