### ISSUE TITLE
Change the first day of the week

### ISSUE THREAD

**Issue by dotnick** [prolificinteractive/material-calendarview#18]
As far as I can see there isn't a way to change the first day of the week at the moment. It would be nice if there was an option to change it.

Looking at the code, MonthView internally sets the day to Sunday.

I hacked something together by exposing the setFirstDayOfTheWeek method to the MaterialCalendarView; if you want I can checkout the repo and open a pull request.

**Comment by dandc87** [comment]
Hey @dotnick, I can't see you're fork of this project, but if you would like to submit a pull request it would be welcome! Somethings I would be looking for are:

*  Match the API of `android.widget.CalendarView` (name and input)
*  Add a new XML attribute `app:firstDayOfWeek="enum"`
    * You can make it easier for yourself if you set the values of the enums to those of the Calendar fields (e.g. `<enum name="sunday" value="1" />`)

Thanks for wanting to contribute!

**Comment by dandc87** [comment]
A namespace is now applied to all attributes, so this should use `mcv_firstDayOfWeek`

**Comment by Ryosan23** [comment]
Isn't this included in actual version? When will be included or when will appear new 1.0.0 version? 
Thank u for Calendar, is really well done.

**Comment by dandc87** [comment]
This feature currently not in the library. We want this feature to be in the library before we release 1.0.

**Comment by ozzcet** [comment]
are there any solution of setFirstDayOfWek

**Comment by RandomCatGit** [comment]
> are there any solution of setFirstDayOfWek

For now you can send
`calendar.setFirstDayOfWeek(Calendar.SUNDAY);`
to the EventDay first parameter Calendar object.

E.g:
```
    @SneakyThrows
    private void calendarSetup() {
        List<EventDay> events = new ArrayList<>();
        Calendar calendar = Calendar.getInstance();
        scheduleCalendar.setDate(calendar);
        calendar.setFirstDayOfWeek(Calendar.SUNDAY);
        events.add(new EventDay(calendar, R.drawable.ic_baseline_av_timer_schedule_24));
        scheduleCalendar.setEvents(events);
    }
```
