### ISSUE TITLE
one question for disable paging

### ISSUE THREAD

**Issue by xu6148152** [prolificinteractive/material-calendarview#181]
First of all, thanks very much for you library.
The question is that when disable paging,pager setCurrentItem will not work, so I view your source code, then found 
```
@Override
    public void scrollTo(int x, int y) {
        if (pagingEnabled) {
            super.scrollTo(x, y);
        }
    }
```
In my opinion, I think paginEnabled may not be used here, may be using in 
```
@Override public boolean onTouchEvent(MotionEvent ev) {
        return pagingEnabled && super.onTouchEvent(ev);
    }
```
will more better?

**Comment by ekchang** [comment]
This is already addressed for a future release. See the [`future-1.x`](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/library/src/main/java/com/prolificinteractive/materialcalendarview/MonthPager.java) branch.
