### ISSUE TITLE
scroll to selected date

### ISSUE THREAD

**Issue by fahimk** [prolificinteractive/material-calendarview#188]
When using setSelectedDate, it would be nice to have the calendar to scroll to that selected date or maybe have a function that could scroll the calendar to a specific date.

**Comment by GerritHoekstra** [comment]
I hope this functionality is going to be implemented. Meanwhile I've fixed it:
```java
if (currentMonth.getMonth() != day.getMonth()) {
    titleChanger.setPreviousMonth(currentMonth);
    // Find difference between months and move the view pager by that much
    int difference = currentMonth.getMonth() - day.getMonth();
    int newPosition;
    if(difference > 0) {
        newPosition = pager.getCurrentItem() + difference;
    } else {
        newPosition = pager.getCurrentItem() - difference;
    }
    pager.setCurrentItem(newPosition, true);
    currentMonth = adapter.getItem(newPosition);

    updateUi();
    dispatchOnMonthChanged(currentMonth);
} 
```
(Add this after [line 658](https://github.com/prolificinteractive/material-calendarview/blob/master/library/src/main/java/com/prolificinteractive/materialcalendarview/MaterialCalendarView.java#L658) in MaterialCalendarView.java)

**Comment by quentin41500** [comment]
@fahimk @GerritHoekstra You can easily do this using `mcv.setSelectedDate()` paired with `mcv.setCurrentDate()`

**Comment by bharamalhusen** [comment]
@quentin41500 Thans.... you save my day.

**Comment by MinaSamirCap** [comment]
fist I use the mode that shows all dates in the calendar
when selecting a date form the next month  it scrolls perfectly to the selected data
but when scroll back I found the selected date from the next month still selected
I know that the logic is correct in that case but that may confuse some users so 
what about adding function to make that part optional for the developers ...
