### ISSUE TITLE
Getting error when i tried to integrate with my app.

### ISSUE THREAD

**Issue by Prashanthlkv** [prolificinteractive/material-calendarview#191]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.transform.api.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.class

**Comment by Jogan** [comment]
looks like it could be a gradle plugin issue. Will reopen if still a problem
