### ISSUE TITLE
Google calendar like jump to today feature possible in calendar view?

### ISSUE THREAD

**Issue by vineetkaushik** [prolificinteractive/material-calendarview#192]
Hi, I want to know if there is a way to navigate to today's date in calendar view. I want the action to be similar to Google calendar's jump to today. 
I am planning to use this feature with a floating action button.

**Comment by chrissd23** [comment]
@vineetkaushik look at my PR

**Comment by hvsimon** [comment]
what is 'PR' 0..0?
