### ISSUE TITLE
How do i customize the Header month/year format ?

### ISSUE THREAD

**Issue by hvsimon** [prolificinteractive/material-calendarview#201]
i wanna change the format from "MMMM yyyy" to "yyyy MM" or anyelse.
i had read CUSTOMIZATION.md and try it but fail.

this is i did：
DateFormatTitleFormatter custom ;

SimpleDateFormat format = new SimpleDateFormat("yyyy MM");
custom = new DateFormatTitleFormatter (format);

what do i miss ?

**Comment by leigo** [comment]
```java
private static final SimpleDateFormat YYYYM_FORMAT = new SimpleDateFormat("yyyy年M月");
widget.setTitleFormatter(new DateFormatTitleFormatter(YYYYM_FORMAT));
```

**Comment by dx51job** [comment]
Thanks for helping ^_^
