### ISSUE TITLE
can anyone develop a canlendar view like tickticl which can toggle between month and week

### ISSUE THREAD

**Issue by gewuxy** [prolificinteractive/material-calendarview#202]
can anyone develop a canlendar view like ticktick which can toggle between month and week,it would be perfect if we do it

**Comment by quentin41500** [comment]
@gewuxy You can change the calendar mode to be weekly or montly with this library. To do so, use:
`widget.setCalendarDisplayMode(CalendarMode.WEEKS)` or `widget.setCalendarDisplayMode(CalendarMode.MONTHS)`
