### ISSUE TITLE
MaterialCalendarView is clipped in a RelativeLayout

### ISSUE THREAD

**Issue by roccadev** [prolificinteractive/material-calendarview#204]
If the position of the view in a RelativeLayout is set relative to an another View, if not tileSize is set, the MaterialCalendarView appears clipped; it seems it's trying to get more space than it actually has availabale.
This layout:    

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.rocca.ringapp.WelcomeActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/textView2"
        android:text="this view takes relevant space above the calendar" 
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="10dp" />

    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/calendarView"
        android:layout_centerVertical="true"
        android:layout_centerHorizontal="true"
        android:layout_below="@+id/textView2"
        android:layout_above="@+id/buttonContinue" />

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/buttonContinue"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true" />
    </RelativeLayout>

produces this:
![device-2016-01-14-002313](https://cloud.githubusercontent.com/assets/11795213/12311222/02d657e6-ba56-11e5-8a51-c6803ae232f0.jpg)

**Comment by quentin41500** [comment]
Your example works for me. You can now setTileHeight if you want to have smaller row. Otherwise just try to put the view in a scrollview so you can access all the calendar content.

Closing this issue, let me know if you need more information.
