### ISSUE TITLE
How to use the single week paging

### ISSUE THREAD

**Issue by wisekingokok** [prolificinteractive/material-calendarview#209]
I notice there has add the single week paging through #175 ,  but I didn't any guide for it? 
Would you show some sample for this wonderful changes? I'm waiting for you.

**Comment by ekchang** [comment]
Until some more detailed guides are written, take a look at [`sample/SwappableBasicActivityDecorated.java`](https://github.com/prolificinteractive/material-calendarview/blob/master/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/SwappableBasicActivityDecorated.java) in the meantime

**Comment by wisekingokok** [comment]
Thanks, I expect the more detailed guides come out as soon as possible
