### ISSUE TITLE
Disabled days

### ISSUE THREAD

**Issue by samiro** [prolificinteractive/material-calendarview#21]
How disable any day?

**Comment by dandc87** [comment]
Hey @samiro, right now there isn't a way to disable individual days, only minimum and maximum dates can be set. I don't see this feature being a priority right now, unless it becomes popular.

As always, pull requests are welcome, but I would advise waiting for events (see #3) to be implemented so we can have a similar APIs.

**Comment by samiro** [comment]
Ok. Thank you very much.

**Comment by johnkil** [comment]
+1

**Comment by NicolaChimerapps** [comment]
+1

**Comment by jsa-nic** [comment]
I just wanted to point out to anyone that's interested in this feature, that I managed to implement this functionality buy implementing onDateChanged, keeping track of the currently selected date and re-setting the currently selected date if the newly selected date should be disabled. The other thing that I had to do was implement a DayViewDecorator which set the disabled day's background to the same color as the calendar background.

**Comment by dandc87** [comment]
Thanks for the suggestion @jsa-nic!

**Comment by dandc87** [comment]
Released in 0.6.0. Disabling days was added to the decorator system.

**Comment by roeiros** [comment]
@dandc87 Can you provide an example for disabling certain dates?

I was trying to do as proposed here: [:](https://stackoverflow.com/a/37650029/6696453) 

`ArrayList<CalendarDay> enabledDates = new ArrayList<>();


            enabledDates.add(new CalendarDay(new Date(2017, 8, 25)));
            enabledDates.add(new CalendarDay(new Date(2017, 8, 26)));
            enabledDates.add(new CalendarDay(new Date(2017, 8, 27)));
            enabledDates.add(new CalendarDay(new Date(2017, 8, 28)));
            enabledDates.add(new CalendarDay(new Date(2017, 8, 29)));
            enabledDates.add(new CalendarDay(new Date(2017, 8, 30)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 1)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 10)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 11)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 13)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 16)));
            enabledDates.add(new CalendarDay(new Date(2017, 9, 19)));


            mcv.addDecorator(new DayEnableDecorator(enabledDates));`

`public class DayEnableDecorator implements DayViewDecorator {
        private HashSet<CalendarDay> dates;

        public DayEnableDecorator(Collection<CalendarDay> dates) {
            this.dates = new HashSet<>(dates);
        }

        @Override
        public boolean shouldDecorate(CalendarDay day) {
            return dates.contains(day);
        }

        @Override
        public void decorate(DayViewFacade view) {
            view.setDaysDisabled(false);
        }
    }`

However, it doesn't work and it seems like CalendarDay() is deprecated.
Any help would be appreciated.
