### ISSUE TITLE
How to bold current date.

### ISSUE THREAD

**Issue by antoniomerlin** [prolificinteractive/material-calendarview#210]
Can anyone help me how to set bold for current date.

**Comment by leigo** [comment]
```java
@Override 
 public void decorate(DayViewFacade view) {
      view.addSpan(new StyleSpan(Typeface.BOLD));
 } 
```

**Comment by NageswaraRaoCH** [comment]
@leigo : i was implemented my class with DayViewDecorator the overriden method decorate was came,i was wirtten 

 view.addSpan(new StyleSpan(Typeface.BOLD));

inside the method but it was not working,Can you please guide me,where i did mistake ? Your response will be appreciated.

**Comment by Jogan** [comment]
@NageswaraRaoCH could you post your decorator code

**Comment by quentin41500** [comment]
@leigo's answer should work. Feel free to reopen this issue with your code if you want us to help you.
