### ISSUE TITLE
Changing device timezone in positive direction causes calendar to display previous month

### ISSUE THREAD

**Issue by faithfracture** [prolificinteractive/material-calendarview#212]
If I have my device set to GMT+0 and I change the timezone to GMT+1, the month that is displayed is the previous month. The app has to be killed & restarted for the calendar to display the correct month. For instance, in the sample app, if I look at "Basic Example", the calendar will display January. If I change the timezone from PST (GMT-8) to MST(GMT-7), the calendar will display December.

If I launch the "Dynamic Setters Test" calendar, then go change the device timezone and go back to the sample app, the month now shows the previous month. If I click "set min date", a date picker appears and prompts me to chose a date for January. if I set the date to Monday, January 18, the December calendar that is shown is now limited to Monday, December 17th. It's as though the entire calendar is still actually correct, but for whatever reason is using the calendar data from 1 month prior.

**Comment by faithfracture** [comment]
![example](https://cloud.githubusercontent.com/assets/717745/12490068/90ddea36-c028-11e5-8198-d7b370d54a7d.gif)

**Comment by quentin41500** [comment]
Seems like it has been fixed, can't reproduced. @faithfracture feel free to reopen if you are still experiencing this

**Comment by hilfritz** [comment]
also please check the bug I found [here](https://github.com/prolificinteractive/material-calendarview/issues/519), not sure if they are the same.
