### ISSUE TITLE
How to custom a button to trigger next month or previous month? and setSelectorDate don't  trigger onDateSelected?

### ISSUE THREAD

**Issue by reaper12** [prolificinteractive/material-calendarview#215]
How to custom a button to trigger next month or previous month? and setSelectorDate don't  trigger onDateSelected?

**Comment by leigo** [comment]
```java
setLeftArrowMask()
setRightArrowMask()
```
or

```xml
app:mcv_leftArrowMask="drawable"
app:mcv_rightArrowMask="drawable"
```

**Comment by reaper12** [comment]
custom a button,not used original Butoon

**Comment by leigo** [comment]
you can replace `mcv_action_next.png`  and `mcv_action_previous.png`

**Comment by reaper12** [comment]
original Button only show in Top , but i hope show it to other location，so i have to custom a button

**Comment by leigo** [comment]
Hide the top bar using setTopbarVisible(false) and implement your own

**Comment by reaper12** [comment]
implement your own？can you show some codes for me . like this:
![12](https://cloud.githubusercontent.com/assets/13657190/12542818/19286e2e-c363-11e5-9132-7fd13b5b06d5.png)

**Comment by piyush1225** [comment]
Hi, Whenever a date is selected the textcolor of that date is changed to white.
Please tell me how can i customize that color and the selectedDate drawable.
