### ISSUE TITLE
Set selected date is not working

### ISSUE THREAD

**Issue by don59** [prolificinteractive/material-calendarview#218]
set selected date is not working in the "Dynamic Setters Test" demo if the selected date is not in current month

**Comment by quentin41500** [comment]
@don59 works for me, it selects the date, but you have to manually go to the month where you selected the date. Closing for now, feel free to open if you still see the same bug.

**Comment by tomboul** [comment]
@quentin this work also for me but, with setSelectedDate  the date is selected, but the calendar dont display the month from this newdate...
 if you have to use setSelectedDate it's to help the user to prevent from being obliged to go to the month manually.
Is there a method to display the month of selectedDate ?

**Comment by tomboul** [comment]
@quentin, @ don59 ok i wrote a function :
```
    private void goToMonthOfDate(Calendar actualDate,Calendar newDate) {
        if(newDate.after(actualDate)) {
            int nb=(newDate.get(Calendar.YEAR) - actualDate.get(Calendar.YEAR))*12 +
newDate.get(Calendar.MONTH) - dateActive.get(Calendar.MONTH);
            for(int i=0;i<nb;i++) {
                MC.goToNext();
            }
        }
        else {
            int nb=(actualDate.get(Calendar.YEAR)-newDate.get(Calendar.YEAR))*12+actualDate.get(Calendar.MONTH)-newDate.get(Calendar.MONTH);
            for(int i=0;i<nb;i++) {
                MC.goToPrevious();
            }
        }
    }

```
