### ISSUE TITLE
How  To Get Title text .

### ISSUE THREAD

**Issue by kashifandroiddev** [prolificinteractive/material-calendarview#224]
how do i get title of calender . it change every month change ...
how do i get it 

thanks

**Comment by nazarcybulskij** [comment]
i use reflection , that  get  titleTextview 
It  is  my  code 

private TextView getTitleTextView(){
        Field f = null;
        TextView titleTextView = null;
        try {
            f = widget.getClass().getDeclaredField("title");
            f.setAccessible(true);
            titleTextView = (TextView) f.get(widget);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return titleTextView;
    }

**Comment by quentin41500** [comment]
@kashifandroiddev There is no functions to get the title yet, but it wouldn't be a problem to add IF necessary. Feel free to reopen this thread and ask for it.
