### ISSUE TITLE
How to scale height

### ISSUE THREAD

**Issue by wisekingokok** [prolificinteractive/material-calendarview#225]
At first, Through set tile size to control the size of calendar view is a good design.

But this isn't enough. sometimes we need the width match its parent and we hope the height size is small as soon as possible.

So, we don't know how to realize this requirement. would you give us some suggestion?

**Comment by ipcjs** [comment]
i do the featur on [this branch](https://github.com/ipcjs/material-calendarview/tree/dev).
bug have some bug~~

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
