### ISSUE TITLE
How to add labels to the next/previous month buttons for TalkBack?

### ISSUE THREAD

**Issue by AidanA11y** [prolificinteractive/material-calendarview#227]
When using the TalkBack screen reader the buttons that indicate the next or previous month read as unlabelled (e.g. Button 69 unlabeleed, Button 47 unlabelled). 

Is there a way to assign the values Next Month and Previous Month to these buttons?

The screenshot shows the calendar with TalkBack enabled and focussed on the previous button, and the overlay shows the text TB reads out. 

![previous-button-talkback](https://cloud.githubusercontent.com/assets/9468139/13018596/657fba78-d198-11e5-9851-f17dc2a16227.PNG)

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!

**Comment by ekchang** [comment]
Public APIs were added: `setContentDescriptionArrowPast`, `setContentDescriptionArrowFuture`, `setContentDescriptionCalendar` with 1.3
