### ISSUE TITLE
TalkBack reads all the days of the week at once, rather than individually

### ISSUE THREAD

**Issue by AidanA11y** [prolificinteractive/material-calendarview#228]
When using the TalkBack screen reader the days of the week read all at once rather than individually.

The screenshot shows the calendar with TalkBack enabled 
![days-of-week-talkback](https://cloud.githubusercontent.com/assets/9468139/13018817/e92b373e-d199-11e5-8fb1-ef5c736bebc5.PNG)
 and the overlay shows the text TB reads out.

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
