### ISSUE TITLE
can somebody help me to understand the tileSize? I

### ISSUE THREAD

**Issue by carlosandresSanchez** [prolificinteractive/material-calendarview#230]
I want to make my view will be a rectangle, but when I set tileSize, it is very small. I dont understand how to distribute all the view in my rectangle.

**Comment by mandrachek** [comment]
The component currently is a 7x8 grid, and all tiles are square.

**Comment by quentin41500** [comment]
@carlosandresSanchez A tile correspond to one cell of the calendar. You can set the size of a cell using tileSize field (in xml or java). As mentioned before, the tile is a square for now,
