### ISSUE TITLE
not able to set background for selected date range

### ISSUE THREAD

**Issue by surajsau** [prolificinteractive/material-calendarview#233]
I need to select the date range and set the background color for the selected dates in between range.

**Comment by quentin41500** [comment]
You can now select range of date: https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#date-selection

You can also provide a custom background: https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOM_SELECTORS.md#custom-selectors
