### ISSUE TITLE
Set tileWidth and tileHeight independently?

### ISSUE THREAD

**Issue by mandrachek** [prolificinteractive/material-calendarview#235]
If tileSize is not defined, it would be nice to be able to set tileWidth and tileHeight independently to be able to support non-square cells.

**Comment by DeoMortis** [comment]
+1

**Comment by ranjitzade** [comment]
I got the same question @mandrachek

**Comment by jagatappv** [comment]
Sorry I don't get any attribute like tileWidth and tileHeight.

**Comment by imp8468** [comment]
+1

**Comment by henrystivens** [comment]
+1

**Comment by ekchang** [comment]
This has been added and will be in the next release. Thanks! Worth pointing out that `getTileSize` will be deprecated (`setTileSize` works fine).

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
