### ISSUE TITLE
support clicking on dates from other months

### ISSUE THREAD

**Issue by mandrachek** [prolificinteractive/material-calendarview#236]
When showOtherDates is set to other_months, users can see events on those dates (if we load them), but they cannot click on those dates.

Ideal behavior would be to page to the other month (forward/backward as appropriate), and select that new day.

Less ideal, but still ok, would be to still fire the date selected event so that we can respond to out of month day touches, and we could handle the rest ourselves.

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
