### ISSUE TITLE
setWeekDayFormatter or xml attr doesn't work

### ISSUE THREAD

**Issue by CallMeXYZ** [prolificinteractive/material-calendarview#240]
And when scrolling The calendar has an old language view after change the system language.

**Comment by quentin41500** [comment]
@CallMeXYZ This doesn't have enough information for me to resolve. Please take a look at the sample app which has an example using `setWeekDayFormatter` that works!

If you want me to fix your issue, show me some code for me to reproduce the issue.

Closing this for now.
