### ISSUE TITLE
How can i disable specific dates , i used setdisabled(true) in decorator but its completely removing date but i want it present and not selectable with light color text

### ISSUE THREAD

**Issue by Venkatesh2391** [prolificinteractive/material-calendarview#242]

**Comment by alex-marochko** [comment]
See DisableDaysActivity from sample - https://github.com/prolificinteractive/material-calendarview/tree/master/sample
![device-2016-03-14-104839](https://cloud.githubusercontent.com/assets/15875712/13739190/6e22542c-e9d2-11e5-9275-16853e17eb25.png)

**Comment by Venkatesh2391** [comment]
Thanks
