### ISSUE TITLE
PFA : I enabled only set of dates , in the image showing selected dates in march month so it means i can't go to next month april as no selected dates in april, here i want right arrow to be disabled but its not not, check image once

### ISSUE THREAD

**Issue by Venkatesh2391** [prolificinteractive/material-calendarview#243]
![bug with right arrow](https://cloud.githubusercontent.com/assets/10152091/13697241/268dcafc-e792-11e5-8cdb-425dfe69f84d.png)

**Comment by quentin41500** [comment]
@Venkatesh2391 Use `setMinimumDate` and `setMaximumDate` to make user can't go to next dates. 1.3.0 has the issue fixed where arrow was black but not enabled.
