### ISSUE TITLE
PFA: I used calendar in dialog with height as as wrap_content , in some devices i'm getting grey color strip at the bottom of the dialog , whats the issue?

### ISSUE THREAD

**Issue by Venkatesh2391** [prolificinteractive/material-calendarview#244]
![bug with right arrow](https://cloud.githubusercontent.com/assets/10152091/13697438/829ecb7e-e793-11e5-8215-979bc08ea2bd.png)

**Comment by quentin41500** [comment]
@Venkatesh2391 Can you give us the android version that you used and/or the device ? That would help, thanks!

**Comment by Venkatesh2391** [comment]
Android 4.4.2

**Comment by quentin41500** [comment]
This is not related to MaterialCalendarView but to Android dialogs
