### ISSUE TITLE
Selecting a range of dates

### ISSUE THREAD

**Issue by joaosardinha** [prolificinteractive/material-calendarview#245]
Greetings, how can I select a range of dates by clicking the first and last date? 
Example: I want to mark an event from jan 1 to fab 10 by clicking in jan 1 and then fabruary 10.
Thanks

**Comment by DeoMortis** [comment]
As far as I can tell there is no such option. You can always do it "manually".
I would use onDateChangeListener to store CalendarDays i clicked on. When stored at least two dates made a list of CalendarDays between the two selected days and create DayViewDecorator using that list. You get the idea.
There is always a problem of what if user presses 3rd date, but you will solve it somehow.

**Comment by caltseng** [comment]
+1 I'd also really like this built in.

**Comment by ekchang** [comment]
This feature will be added in `1.4.0` release. You are encouraged to try the feature out in the snapshot build at 'com.prolificinteractive:material-calendarview:1.4.0-SNAPSHOT'. Be sure to point maven toward the sonatype snapshot URL.

**Comment by joaosardinha** [comment]
it's working percetly and looks good, one question tho, what is the right way to get a range of dates? Im printing them in a textView like this `textView.setText(String.valueOf(dates));` and it prints [CalendarDay{2016-4-11}, CalendarDay{2016-4-12}, CalendarDay{2016-4-13}...] not that this is a problem, just wondering

**Comment by quentin41500** [comment]
@joaosardinha Check the doc https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/docs/CUSTOMIZATION.md#date-selection everything is in there

**Comment by quentin41500** [comment]
`OnRangeSelectedListener` is what you are looking for, it returns a list of dates that were in the range

**Comment by joaosardinha** [comment]
Yes, but should it return like this: "[CalendarDay{2016-4-12}, CalendarDay{2016-4-13}..." ?

**Comment by ekchang** [comment]
Dates is returned as a list so you are probably looking for `Arrays.toString(dates.toArray())`

**Comment by quentin41500** [comment]
Yes it's normal, dates are CalendarDay objects

**Comment by joaosardinha** [comment]
Alright, thanks a lot!

**Comment by JoseAlva7** [comment]
en el modo Range....Como se puede seleccionar las misma fecha??
