### ISSUE TITLE
Throwing java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by allenz8512** [prolificinteractive/material-calendarview#246]
Appear when calling `setCalendarDisplayMode(CalendarMode.WEEKS)` and no day was selected

**Comment by heatherSnepenger** [comment]
I'm seeing similar behavior

**Comment by ipcjs** [comment]
#252 fix the bug.

**Comment by ipcjs** [comment]
#252 fix the bug.

**Comment by wzieba** [comment]
Same here, how other handle it? I show calendar in Fragment and then setting CalendarDisplayMode to Weeks

**Comment by emitchel** [comment]
In `MaterialCalendarView.setCalendarDisplayMode(...)` it doesn't check `CalendarPagerAdapter.selectedDates` size before `.get(0)` at line 451.

This reason and many others is why I imported the code locally and made changes as I go. Will be submitting a PR one of these days to fix little problems including this. 

To fix you must simply change 

` setCurrentDate(selectionMode == SELECTION_MODE_SINGLE
                ? adapter.getSelectedDates().get(0)
                : CalendarDay.today());`

to `CalendarDay daySelected = selectionMode == SELECTION_MODE_SINGLE &&
                adapter.getSelectedDates().size() != 0 //if nothing is selected this will be 0
                ? adapter.getSelectedDates().get(0)
                : CalendarDay.today();`
