### ISSUE TITLE
How to Change Sun,Mon...Sat titles with Custom Names?

### ISSUE THREAD

**Issue by NageswaraRaoCH** [prolificinteractive/material-calendarview#247]
I want to change Sun,Mon,Tue,Wen,Thu,Fri,Sat with my custom names Day1,Day2...
How can i change?Any one can guide me Your response will be appreciated.

**Comment by DeoMortis** [comment]
It's easy. Use weekDayLabels:
`<com.prolificinteractive.materialcalendarview.MaterialCalendarView`
 `                   android:id="@+id/calendarView"`
`                    android:layout_width="match_parent"`
`                    android:layout_height="wrap_content"`
`                    app:mcv_weekDayLabels="@array/weekdays_cust"`
`                    />`

and of course in strings.xml you need to have weekdays_cust array like:

`<array name="weekdays_cust">`
    `    <item>Day1</item>`
    `    <item>Day2</item>`
    `    <item>Day3</item>`
    `    <item>Day4</item>`
     `   <item>Day5</item>`
    `    <item>Day6</item>`
    `    <item>Day7</item>`
    `</array>`

**Comment by NageswaraRaoCH** [comment]
Thank you so much,It is really helped for me.
