### ISSUE TITLE
How to show some specified dates (Ex: march 3,5,April 1,2....)   Rounded circle?

### ISSUE THREAD

**Issue by NageswaraRaoCH** [prolificinteractive/material-calendarview#248]
I have a collection of dates.how to show those days rounded circle.i need to show circle colors  green,red.Can any guide me,Your response will be appreciated.

**Comment by DeoMortis** [comment]
create new DayViewDecorator and feed it with the list of the dates (CalendarDay list).
See sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/decorators
