### ISSUE TITLE
Not showing the previous month dates in current month

### ISSUE THREAD

**Issue by gaganpreet4423** [prolificinteractive/material-calendarview#249]
While using this library, I am not getting the last few days entries of last month in current selected month. It is showing blank.

Can you please tell me how to make those last month's dates visible in current month?

**Comment by DeoMortis** [comment]
See app:mcv_showOtherDates property in xml.
It takes all, none, defaults, other_months, out_of_range, decorated_disabled

**Comment by gaganpreet4423** [comment]
Thanks for the quick reply. :+1:
