### ISSUE TITLE
How to decrease space between the dates?

### ISSUE THREAD

**Issue by NageswaraRaoCH** [prolificinteractive/material-calendarview#251]
1                   2                   3                      4
                                      ========>  How i need to customize the height between dates
5       ||             6                   7                      8
          ||
          ||
            ====> This  Width also
 
Height and width, can any one guide me,Your response will be appreciated....

**Comment by DeoMortis** [comment]
There is no space between dates at all.  You can change a tile size using mcv_tileSize (both height and width).
`                    app:mcv_tileSize="40dp"`
For now there is no possibility to change it separately. 
There is https://github.com/prolificinteractive/material-calendarview/issues/235 
vote and hopefully it will be implemented.
Or implement it on your own and share with us :)

**Comment by quentin41500** [comment]
@NageswaraRaoCH please close this issue if `mcv_tileSize` is the right solution for you

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
