### ISSUE TITLE
Different background/selector for out of bounds dates

### ISSUE THREAD

**Issue by karlkar** [prolificinteractive/material-calendarview#253]
Hello.
I have a calendar displaying all days within a month and few days from previous and next month.
What I want to do is to create a DayViewDecorator that will set different background for a range of days, but if it is a day from the previous/next month I want the color to be a bit different to notify the user that this day isn't within current month.

Let's say that I have:
             JUNE
27 | 28 | 29 | 30 | 1 | 2 |  3
 4  |  5  |  6  |  7  | 8 | 9 | 10 
...
and I have set a decorator for range 01.06 - 30.07.
I want decorator to set dark blue background for dates 27.06, 28.06, 29.06, 30.06 and light blue background for dates 01.07 - 30.07. After changing the view to july I'd like to have light blue on July's dates, and dark blue on June's dates.
How can it be achieved?

**Comment by DeoMortis** [comment]
I have had the same idea! I did it by reloading decorators whenever month changed. You know, you can use onMonthChangedListener to do so.
However, reloading decorators takes some time, and visual stutter can be a pain.

Some serious fork needs to be done, to achieve this goal. I have this on my mind, hovewer not on the top priority,
