### ISSUE TITLE
Week from March 13-19 2016 is missing when displaying a calendar on Week Mode.

### ISSUE THREAD

**Issue by elg0nz** [prolificinteractive/material-calendarview#254]
When in Week Mode, the days for March 13-19 week are missing! See screenshots below.

![pt1](https://cloud.githubusercontent.com/assets/63699/14031585/b163ae8e-f1ca-11e5-8405-d09fad986c47.png)

![pt2](https://cloud.githubusercontent.com/assets/63699/14031579/a9df643c-f1ca-11e5-9115-b7f5775f86d9.png)

**Comment by elg0nz** [comment]
Tested on a Samsung Galaxy J1 (2016) on Android 5.1.1 (Lollipop)

**Comment by elg0nz** [comment]
Found these possibly related issues on CalendarView while investigating the root cause:
* [Android CalendarView Drops Weeks at Random](http://stackoverflow.com/questions/17518677/android-calendarview-drops-weeks-at-random)

* [CalendarView Issues when Used Directly Outside of a DatePicker](http://stackoverflow.com/questions/18534349/calendarview-issues-when-used-directly-outside-of-a-datepicker)

**Comment by elg0nz** [comment]
I've narrowed the issue to the remove row calculation on CalendarPagerView.resetAndGetWorkingCalendar. 

https://github.com/prolificinteractive/material-calendarview/commit/9edc9bf88c1150d3e57f96ee5b1e6b39b4d65134#diff-eb999a88de10aba2edab468c9e0c402bR74

**Comment by emitchel** [comment]
I too had issues until I specified a minimumDate for the calendar, then the issue abstractly went away :+1:  whatever works I guess

**Comment by keith30xi** [comment]
Is it a coincidence that DST began for a number of countries on March 13?  Could a missing hour cause date arithmetic to be off?

**Comment by ekchang** [comment]
I cannot recreate this issue. Can you confirm this is still a problem with version 1.2.1?

**Comment by elg0nz** [comment]
Yes, this is no longer happening on 1.2.1

**Comment by tylerwilson** [comment]
FYI, it is March 16, 2018, and we are seeing this issue now on some devices. Using latest 1.4.3. Anything we can do without shipping a whole new app?

**Comment by darkengine** [comment]
It happened to week March 14-20, 2021 too. Does this bug get fixed?
