### ISSUE TITLE
Calendar in landscape mode missing days

### ISSUE THREAD

**Issue by mtrakal** [prolificinteractive/material-calendarview#261]
In landscape mode, when I compile source code:

![ICalendar in landscape](http://android.mtrakal.cz/github/imgs/device-2016-04-01-151655.png)

there iare missing days.

![Calnedar in portraint](http://android.mtrakal.cz/github/imgs/device-2016-04-01-151958.png)

**Comment by StefMa** [comment]
Same here. Using version 1.2.0.
<img src="http://i.imgur.com/2hF2fGY.png" width=680px height=auto />
This is my layout file:
```xml
    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
        android:id="@+id/calendar_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mcv_arrowColor="@color/mcv_text_date_dark"
        app:mcv_dateTextAppearance="@style/TextAppearance.AppCompat.Body1"
        app:mcv_firstDayOfWeek="monday"
        app:mcv_headerTextAppearance="@style/TextAppearance.AppCompat.Headline"
        app:mcv_weekDayTextAppearance="@style/TextAppearance.AppCompat.Button"/>
```
Full project can be found here https://github.com/StefMa/TimeTracking/tree/master/client (WIP)

**Comment by StefMa** [comment]
The funny part: It works like designed.
If you don't set any `tileHeight` the 'MaterialCalendarView` measured each tile to wrap on `match_parent`.
So one tile is `match_parent` / 7 == height and width.
And yes, this is very big!

Our days doesn't "go away". The are "under" the screen. You can check this if you wrap a `ScrollView` over it. And, btw, is the solution. If you want big tiles like above in horizontal mode.
Another solution is to set a specific tile height with `mcv_tileHeight="28dp"` for example. Or get it from your `dimens` and put another value depending on phone, tablet and portrait or landscape...

**Comment by quentin41500** [comment]
@mtrakal Scrollview and setting tileSize sounds like the right solution. if @StefMa solution solves your issue, please upvote his comment and close this issue, thanks

**Comment by mtrakal** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/261#issuecomment-210442820
