### ISSUE TITLE
How to add space between raw in calender

### ISSUE THREAD

**Issue by sahilappv** [prolificinteractive/material-calendarview#264]

**Comment by Jogan** [comment]
related to #235

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
