### ISSUE TITLE
How can I increase the height of days box?

### ISSUE THREAD

**Issue by harry225** [prolificinteractive/material-calendarview#265]
Hey,

I'm using this library its awesome but i need a small changes in it.
I want to set custom height of days box but i'm unable to do it.

Can you help me to increasing height of days box?

Let me attach the screenshot for more understanding of this problem.

The bottom event decorater gets cut so i want to increase the day height.

Thanks in advance.
![device-2016-04-05-071122](https://cloud.githubusercontent.com/assets/1648504/14279924/b0ce9f92-fafd-11e5-95f8-b4a5581e489d.png)

**Comment by jagatappv** [comment]
+1

**Comment by Jogan** [comment]
related to #235

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
