### ISSUE TITLE
How to set Type face of weekDayLabels,monthLabels?

### ISSUE THREAD

**Issue by NageswaraRaoCH** [prolificinteractive/material-calendarview#267]
How to set Type face of weekDayLabels,monthLabels?

 can any one guide me once, your response will appreciated.

**Comment by emitchel** [comment]
`app:mcv_dateTextAppearance="@style/AppTheme.TextAppearance.Thin"
app:mcv_weekDayTextAppearance="@style/AppTheme.TextAppearance.Thin"`

Is what you're looking for

**Comment by Jogan** [comment]
:+1:
