### ISSUE TITLE
Exposing more pager functionality

### ISSUE THREAD

**Issue by emitchel** [prolificinteractive/material-calendarview#269]
I would like to use my own `buttonFuture` and `buttonPast` functionality since I'm not showing the given header via `setTopbarVisislbe(false)` but rather using my own custom header. 

That's nice but there is no `next/previousMonth()` functionality implemented so we can call them via our custom header - is that in a future release?

**Comment by ekchang** [comment]
This has been added and will be part of the next release. Thanks!

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
