### ISSUE TITLE
Hello, I want to know the background of the selected day how to shrink

### ISSUE THREAD

**Issue by 18810979455** [prolificinteractive/material-calendarview#272]

**Comment by kaupunki-apina** [comment]
Create your own drawable which has inset.

For example:
<inset xmlns:android="http://schemas.android.com/apk/res/android"
    android:insetBottom="dimension"
    android:insetLeft="dimension"
    android:insetRight="dimension"
    android:insetTop="dimension">

    <shape android:shape="oval">
        <solid android:color="your_color" />
    </shape>
</inset>

**Comment by quentin41500** [comment]
You can use `setTileWidth` and `setTileHeight`. Let me know if this doesn't work

**Comment by quentin41500** [comment]
Closing for now, feel free to reopen if it's not working for you
