### ISSUE TITLE
Remenber date, but now I open calendar again, it show current date.

### ISSUE THREAD

**Issue by rakjang007** [prolificinteractive/material-calendarview#275]
I remember date when I selected always. I open calendar again I want to see a remember date. But now i see current date always.

Can you fix it or how to implement this case?

Thank you.

http://im2.ezgif.com/tmp/ezgif-3769166743.gif

**Comment by emitchel** [comment]
You'll have to manage the previously selected date (`previousDate`) and select it upon opening if you're using a dialogue of sorts. You're probably reinitializing every time (which is ok) but you'll have to call `yourCalendarView.setCurrentDate(previousDate)` as well as `yourCalendarView.setSelectedDate(previousDate)` upon opening

**Comment by rakjang007** [comment]
OK, It's work.

Many Thanks to emitchel. :smile:
