### ISSUE TITLE
Add decorator functionality to top bar

### ISSUE THREAD

**Issue by susemi99** [prolificinteractive/material-calendarview#276]
I want custom week day label. so call setTopbarVisible(false), but hide only month  parts(prev/next button, month label).

phone: LG G4
os: mashmallow

Thank you for very good calendar.

**Comment by chuks** [comment]
This would be a great feature --I also needed this feature. What I did was to use a custom style for the header, and set the text to transparent, so it's not visible. Then I built a new layout over the calendar with the customized text. Basically, what I really needed was to have a static week view, so that it's not sliding when you swipe the calendar.

**Comment by chuks** [comment]
Actually, this works for me - setTopbarVisible(false)

**Comment by ekchang** [comment]
I believe I understand what @susemi99 is asking for--Right now you can change the month labels with `setTitleMonths`, but there's no way to tailor the top bar to change based on weeks: ie. have Week mode top bar show "Week of May 08 - May 14".

Currently the `TitleChanger` is tightly coupled to months, even though you can call `MaterialCalendarView#setTitleFormatter` to specify a custom formatter. `TitleChanger` was modified to not animate if you were paging weeks and are still in the same month.

**Comment by susemi99** [comment]
sorry. my bad english.

I want insert long separator line  between week label and day numbers. but setTopBarVisible(false) is don't hide week label part.

**Comment by ekchang** [comment]
Hm, I don't think we have decorators for top bar yet. Revised enhancement request.

As a workaround, you should be able to wrap your MCV in a FrameLayout and place a manual View as a divider, offset from the top by the height of the top bar.

**Comment by susemi99** [comment]
no plan for like setWeekLabelBarVisible()?

**Comment by ekchang** [comment]
There currently is no divider right now--it would have to be added as a full feature with a default divider and optional, override-able decorator (to specify what kind of divider you want, similar to `DayViewDecorator`). For the time being, you can clone the repo and add the divider view manually as part of [`setupChildren`](https://github.com/prolificinteractive/material-calendarview/blob/master/library/src/main/java/com/prolificinteractive/materialcalendarview/MaterialCalendarView.java#L349) but it will take time to write out a complete solution.

It is currently not part of the `1.x` roadmap but if there is more demand, we will look into it!

(You are welcome to work on a solution and submit a PR!)

**Comment by susemi99** [comment]
ok. thank you for comment :)
