### ISSUE TITLE
IndexOutOfBoundsException on mCalendarView.setCalendarDisplayMode(CalendarMode.WEEKS);

### ISSUE THREAD

**Issue by lawgimenez** [prolificinteractive/material-calendarview#277]
I'm getting an IndexOutOfBoundsException  when setting setCalendarDisplayMode(CalendarMode.WEEKS) and stack trace is pointing at at com.prolificinteractive.materialcalendarview.MaterialCalendarView.setCalendarDisplayMode(MaterialCalendarView.java:451)

**Comment by lawgimenez** [comment]
When I call mCalendarView.setSelectionMode(MaterialCalendarView.SELECTION_MODE_NONE);
no exception is thrown. But when I choose SELECTION_MODE_SINGLE it throws based on the condition set on MaterialCalendarView.java:451)

**Comment by emitchel** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/246
