### ISSUE TITLE
Programmatically move calendar view to certain date (either in the future or past)

### ISSUE THREAD

**Issue by chuks** [prolificinteractive/material-calendarview#279]
Is there a method that can programmatically move the calendar to a certain date? This would be useful when, for instance, say I am viewing December 2016 in month mode, and want to move back to May 4 (todays date) without swiping. It would be nice to build a button that would programmatically move (in swipe motion) the calendar back to today's date --just like in Google calendar.

**Comment by DeoMortis** [comment]
There is such option. I use it just like you - go back to today.
It's something like **setCurrentDate**, sorry for no details but I don't have my code right now.
Tomorrow I can give you 100% sure details.

**Comment by chuks** [comment]
Great! I just tried it, and it works! Here's the code to programmatically scroll to three months out, for example:

`Calendar c = Calendar.getInstance();
c.add(Calendar.MONTH, 3);
widget.setCurrentDate(CalendarDay.from(c.getTime()), true);`

**Comment by emitchel** [comment]
//selects the day
        mCalendarView.setSelectedDate(calendarDay);

        //scrolls to month (if not already viewing)
        mCalendarView.setCurrentDate(calendarDay);

**Comment by quentin41500** [comment]
@chuks Please close the issue if resolved, thanks!

**Comment by chuks** [comment]
Resolved!
