### ISSUE TITLE
Set Week/Month mode as attribute in XML

### ISSUE THREAD

**Issue by ekchang** [prolificinteractive/material-calendarview#288]
#285

Add an XML attribute to set week/month mode. Otherwise users are forced to `setCalendarMode(WEEKS)` during view creation. Something like:

```
<attr name="mcv_calendarMode" format="integer">
  <flag name="month" value="0" />
  <flag name="week" value="1" />
</attr>
```

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
