### ISSUE TITLE
getItemPosition (and possibly indexOf, etc) returning wrong index for WeekMode

### ISSUE THREAD

**Issue by ekchang** [prolificinteractive/material-calendarview#292]
#285 #291

Reproducible by creating a RV of MCVs, setting them to Week mode, and scrolling them off screen to trigger `CalendarPagerAdapter#getItemPosition` and calling `setMinimumDate(today)` during `onBind`. As of 05/10/2016, on creation the calendar shows week of 05/04 - 05/10, but scroll through and it will rebind as 04/27 - 05/03. This is because month mode would have shown `minDate` as 04/27 (which is correct) but week mode has no intelligent way of setting a narrower minDate at the moment.

**Comment by quentin41500** [comment]
Seems like the issue is coming from `materialCalendarView#setFirstDayOfWeek(Calendar.WEDNESDAY);`

**Comment by quentin41500** [comment]
Related to #222

**Comment by quentin41500** [comment]
This issue has been fixed and is available in the 1.3 snapshot. Stay tuned for the next release.You can try the 1.3 snapshot with the instructions in [README](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md). Enjoy and report issues!
