### ISSUE TITLE
setMaximumDate(date) in 'weeksMode' does not disable weeks paging like the way in 'monthsMode'

### ISSUE THREAD

**Issue by joecizac** [prolificinteractive/material-calendarview#293]

**Comment by ekchang** [comment]
I need to look into this. I believe `minDate` and `maxDate` for weeks is not WIA.

**Comment by emitchel** [comment]
@joecizac, @ekchang this is an easy fix I've done locally:

In `MaterialCalendarView#setCalendarDisplayMode(...)`

it doesn't call `adapter.setRangeDates(minDate,maxDate)` even though it sets the `max` and `min` in `adapter.migrateStateAndReturn(...)`. Calling `adapter.setRangeDates(...)` will init the bounds of the new adapter. 

My apologies for not submitting a PR, have been working to get it implemented and this, along with a number of other small items, have forced me to pull locally for now.

**Comment by joecizac** [comment]
@emitchel it didn't work. It's locking the paging a week or two before the actual max date

**Comment by ekchang** [comment]
We will be releasing a 1.3 snapshot soon. You're encouraged to try it out and let us know if these problems are still existent. Please tag any issues with the 1.3 snapshot with the `1.3-SNAPSHOT` label. Thanks!

**Comment by joecizac** [comment]
@ekchang Looking forward to test the snapshot.

**Comment by ekchang** [comment]
[Snapshot instructions](https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/README.md): Change to the snapshot maven URL and add `compile 'com.prolificinteractive:material-calendarview:1.3.0-SNAPSHOT'` to your dependencies.

**Comment by ekchang** [comment]
Confirm whether the issue is still present now that 1.3.0 is live.
