### ISSUE TITLE
How to set Dynamic height of the Calendar

### ISSUE THREAD

**Issue by ajithkpistar** [prolificinteractive/material-calendarview#299]
I want to set the height of the calendar in which it should adjust height of the specified layout.my layout is Liner layout and in this calendar is a child layout, which weight is 50, so inside this layout i need to place calendar.if i use setTileSize() it padding the calendar from left and right...but i need to set width as match parent..pls help me out its Urgent...!

**Comment by ekchang** [comment]
`setTileHeight` and `setTileWidth` are upcoming features for 1.3. Stay tuned for a `1.3-SNAPSHOT` release to test shortly today.
