### ISSUE TITLE
adding events and showing events

### ISSUE THREAD

**Issue by kprathap23** [prolificinteractive/material-calendarview#3]
adding events and showing events in the calender like calendar app in android.

**Comment by dandc87** [comment]
I'm not sure where this fits into the goal of the project, which is to make a date picker widget of material design. I'm not against it, but this will likely take low priority, unless this is a popular request.

While this percolates:

What kind of API are you thinking of? Something like this:
```java
calendarView.addEvent(new Event(date, "Extra Data"));
```

And how should events be shown indicated on the view?

**Comment by ppatriotis** [comment]
Maybe just some different highlighting for a few "event" dates in the background using would be the easiest without a whole different UI. Might be nice option to highlight today's date too?

**Comment by kprathap23** [comment]
@dandc87 

Thanks for the comments.

Exactly like this.
calendarView.addEvent(new Event(date, "Extra Data"));

**Comment by NeoDigi** [comment]
I support this idea, i'll try to see if I can help

**Comment by MadScientistUA** [comment]
So, when will be update? I can't wait. I haven't seen usage like this in other libraries, so i hope update will be soon

**Comment by jlindenbaum** [comment]
I would be happy with a simpler implementation, something that just let's me return true in a delegate that checks if a date has an event, like: `public boolean dateHasEvent(Date date)`. Then I can still have my own, styled list view below the calendar to show those events properly when the `OnDateChangedListener` fires.

**Comment by dandc87** [comment]
@jlindenbaum I was trying to find an appropriate way to indicate a day had an event; thanks for the suggestion!

Does anyone else have input they would like to give for the API? If we are going to use the dot indicator, I'm supportive of the delegate pattern, but I see what I initially proposed as more extensible. Maybe a mix between the two and call it and `EventAdapter`? Though I'm not quite sure how that would work.

**Comment by jlindenbaum** [comment]
I'd prefer a lighter weight calendar utility, and handling my own event
listing / adapter. I'd be very happy with just a way to highlight that
there's something going on that day.

Since I personally want to handle the click and styling of the event
listing, and won't want to have to jam custom adapters into the calendar
view to do so.

**Comment by NeoDigi** [comment]
I think the dot indicator would be a good idea and it would be easy to put different kind of event simply by changing the color of the dot.
But as @jlindenbaum said we should be able to override the "dot adapter" by using an adapter of our own.

**Comment by jlindenbaum** [comment]
This is a very naive, and untested, implementation of how I imagine the flow. There is no caching, but that could be added. For every `CalendarDay` we call the `EventDelegate` that is implemented, most likely, in a `Fragment`. This naive implementation does not highlight the current day in any way. It's merely seeing if people would agree with this type of implementation.

https://github.com/jlindenbaum/material-calendarview/commit/15d0fb9a4e18408f9df97b2977b35b67f6e7e77e

**Comment by jlindenbaum** [comment]
Based off #21, I'd suggest changing `EventsDelegate` to something more appropriately named, perhaps `CalendarDayConfigurationDelegate`. I've been rolling with delegate, as it's not really a listener, but also not entirely a delegate. Help appreciated.

Functions in the delegate could now be `public boolean calendarDayHasEvent(CalendarDay day)` and `public boolean calendarDayIsSelectable(CalendarDay day)`, or `calendarDayIsEnabled(CalendarDay day)`. Any number of functions that allow us to configure the CalendarDay while it's being rendered.

**Comment by nambv** [comment]
![selection_722](https://cloud.githubusercontent.com/assets/6938776/6728649/d600cfa6-ce5d-11e4-8c0f-b05210f56c7d.png)
Hi @dandc87,  can you update calendar view like this: 
-The dot or indicator below is a date which has event
- The selected day is the day marked red

**Comment by krazykira** [comment]
I think it would be awesome to have events adding and deleting feature in this calendar. This is something that is implemented in Caldroid.
https://github.com/roomorama/Caldroid
We can even customize the appearance of events shown on Calender in Caldroid. And i would like the same sort of functionality here.

**Comment by angelpinheiro** [comment]
A more general solution would be to provide custom decorators to day views. I was working on a very simple implementation that allows you to do so https://github.com/angelpinheiro/material-calendarview/commit/7d7f1ce132544850366d71314dd29ce3d3e0f1ac. I have also updated the sample project with a new example that looks like this:

<img src="https://cloud.githubusercontent.com/assets/5940259/7102238/46a9a97a-e07a-11e4-8eb9-f6c45ad83793.png" width="250"/>


First you define your decorator, to decorate day views as you want:
```
public class HighlightDecorator implements DayViewDecorator{
    @Override
    public void decorate(DayView view,Context context) {
        view.setBackground(generateCircleDrawable(color));
    }
}
```

Then you tell calendar widget wich dates you want to decorate:
```
widget.addDayViewDecorator(new HighlightDecorator(), dates)
widget.addDayViewDecorator(new AnotherDecorator(), ...)
```
You can probably improve it in many ways, since I do not know very well the architecture of the library, but it's a starting point. I will do a pull request if you are interested!

**Comment by dandc87** [comment]
I like the decorator idea @angelpinheiro, but it needs some work. Will you create a pull request so we can discuss some changes?

**Comment by dandc87** [comment]
You can now use DayViewDecorator to show events!

**Comment by kprathap23** [comment]
Thanks for all , Awesome Work.

**Comment by vardimir** [comment]
how i can add a new event like intent?

**Comment by SugamPradhan** [comment]
how can i add a text below a date?? (Can be event or reminder)

**Comment by recker115** [comment]
Yes, like can we popup a title or a text somehow for the decorated dates ??

**Comment by rajputneeru** [comment]
Please Let me any idea How i can  show all events on material calendar after getting from Google calendar API??

**Comment by CoderAlok** [comment]
Please somebody give me the proper detailed code to add and view the event in this calander view
