### ISSUE TITLE
TextDecorator is very slow

### ISSUE THREAD

**Issue by Budincsevity** [prolificinteractive/material-calendarview#30]
Hi!

I'm using Your library in my application, and it's a very cool and unique calendar. I have just one problem with the new decorators. It's a great new feature for me, so I've started using it. 

My problem is, that when I'm using the sample class, TextDecorator, my app runs really slow. The GPU rendering chart shows that my GPU is working on a full performance. 

Here is my code:

private List<Date> mDateOfEvents;
private TextDecorator mTextDecorator;
onCreate {
mDateOfEvents = new ArrayList<>();
mTextDecorator = new TextDecorator("●", mDateOfEvents);
mMonthCalendar.addDecorator(mTextDecorator);
}

.
.
.

addEvents() {
    for (Object object : objectList) {
        mDateOfEvents.add(event.getStartTime().getTime());
    }

mTextDecorator = new TextDecorator("●", mDateOfEvents);
mMonthCalendar.invalidateDecorators();
}

Thanks for your help!

**Comment by kamilwlf** [comment]
Do you want improve performance? With a large number of dates running very slowly. when you expect a new version?

**Comment by dandc87** [comment]
Hi @Budincsevity and @kamilwlf. I've been working on improving the decorators. Would you be willing to test `0.4.0-SNAPSHOT` and let me know if its better? Directly manipulating text will no longer be supported, instead you are allowed to set spans and I added an new `DotSpan`. The samples were updated to use the new APIs too.

**Comment by Budincsevity** [comment]
Hi! Yes of course. How can I download it?

**Comment by dandc87** [comment]
* Change the version of the calendar dependency to `0.4.0-SNAPSHOT`
* Add the staging maven repo to your project `maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }`

If you're using the standard project template, the top level `build.gradle` should look like:
```groovy
...

allprojects {
    repositories {
        jcenter()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
If you want to download the AAR, you can download it here https://oss.sonatype.org/content/repositories/snapshots/com/prolificinteractive/material-calendarview/0.4.0-SNAPSHOT/

**Comment by Budincsevity** [comment]
It's working like charm now for me! Thank you! :)

**Comment by dandc87** [comment]
Closing now that 0.4.0 is released
