### ISSUE TITLE
How to change the Date text size and color?

### ISSUE THREAD

**Issue by TokyoAndroid** [prolificinteractive/material-calendarview#305]
My background is black , so I want the day text is white , and I can't find the function like "textSize" or "textColor"

**Comment by TokyoAndroid** [comment]
I am SORRY I asked a so foolish question,Now I found it.

**Comment by TokyoAndroid** [comment]
And thanks for your beautiful Calendar!

**Comment by nAkhmedov** [comment]
@TokyoAndroid How did you change calendar text color?

**Comment by hasancse91** [comment]
@nAkhmedov 

Check this code sample:

`@Override
public void decorate(DayViewFacade view) {
    view.addSpan(new ForegroundColorSpan(Color.RED));
    //set any color which are mentioned in your color.xml file
    // view.addSpan(new ForegroundColorSpan(ContextCompat.getColor(context, R.color.your_color)));
}`
