### ISSUE TITLE
Any way to toggle showing year or not?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [prolificinteractive/material-calendarview#32]
sometimes all we need is to choose a month&dayOfMonth...

**Comment by dandc87** [comment]
Hey @AndroidDeveloperLB. You can set a TitleFormatter that only displays the month and set minimum and maximum dates that limit the selection to a single year. This library can never be truly year agnostic because things like days of the week and leap years.

**Comment by AndroidDeveloperLB** [comment]
I see, so it's a problem...
Thank you. You are welcomed to try out my repos if you wish.
