### ISSUE TITLE
Tile size not changed after rotation

### ISSUE THREAD

**Issue by sofiahellofresh** [prolificinteractive/material-calendarview#325]
I have 2 layouts defined, one in layout and the other in layout-land. When I rotate the device the layout is redrawn correctly, the problem is that the tile size is not correct.

This is how I defined the calendar:

```
<com.prolificinteractive.materialcalendarview.MaterialCalendarView
      android:id="@+id/calendarView"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      app:mcv_firstDayOfWeek="monday"
      app:mcv_dateTextAppearance="@style/CalendarDateTextAppearance"
      app:mcv_headerTextAppearance="@style/CalendarHeaderStyle"
      app:mcv_weekDayTextAppearance="@style/CalendarWeekTextAppearance"
      app:mcv_tileSize="@dimen/calendar_tile_size"
      />
```

Then I have 3 values for the tile size:
````
<!-- values/dimens.xml -->
<dimen name="calendar_tile_size">50dp</dimen>

<!-- values-sw720dp/dimens.xml -->
<dimen name="calendar_tile_size">100dp</dimen>

<!-- values-sw720dp-land/dimens.xml -->
<dimen name="calendar_tile_size">80dp</dimen>
````

If I open the calendar with the device on landscape the layout and sizes are correct. But if I open the calendar on portrait and then rotate the device, the layout is correct but not the tile size. The same if I do it the other way around.

I also tried setting the size dynamically but it doesn't work either.

What could be the problem?

Thanks!

**Comment by ekchang** [comment]
On rotation it is restoring the previous tile width/height that the view had. It should resize if you call `setTileSize` again during your Activity `onCreate`. Do you want to include a snippet of what it looks like when you set the tile size dynamically?

**Comment by sofiahellofresh** [comment]
It's in a fragment, I call setupView in onViewCreated.

```
private void setupView() {
        mCalendarView.setOnMonthChangedListener(this);
        mCalendarView.setOnDateChangedListener(this);
        mCalendarView.setDayFormatter(new DateFormatDayFormatter(new SimpleDateFormat("dd", Locale.getDefault())));
        mCalendarView.setLeftArrowMask(mNavigateBackIcon);
        mCalendarView.setRightArrowMask(mNavigateNextIcon);
        mCalendarView.setTileSize(getResources().getDimensionPixelSize(R.dimen.calendar_tile_size));
    }
```

**Comment by ekchang** [comment]
Hm. I am unable to recreate the issue--if you check out the Dynamic Setters sample, I can set a tile size, rotate, observe that the previous tile size is respected, and can call `setTileSize` again to update it.

**Comment by quentin41500** [comment]
Are you still having this issue @sofiahellofresh ? I do believe this is working properly. Will be closing if no updates

**Comment by sofiahellofresh** [comment]
You can close it. Thank you :)

**Comment by Gansgar** [comment]
For everybody who not happy with the solution here (if there even is one). The problem can be fixed by simply recalling `setTileSize` **after** the whole layout was rendered with help of a `GlobalLayoutListener`.

Here:
```java
MaterialCalendarView cal = ...

cal.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
    @Override
    public void onGlobalLayout() {
        cal.getViewTreeObserver().removeOnGlobalLayoutListener(this);
        cal.setTileSize(getResources().getDimensionPixelSize(R.dimen.calendar_tile_size));
    }
});
```

> **A note:**
> I use a layout orientation depending dimension to get the correct custom value for my `tileSize`. That's why there's just one line accessing the `R.dimen.calendar_tile_size`.
