### ISSUE TITLE
how to select multiple dates programatically

### ISSUE THREAD

**Issue by iad24** [prolificinteractive/material-calendarview#326]
Im planning to present a calendar dialog with min and max date. Then user need to select multiple dates.
User may need to select all the dates. So i need to put a Select All button (and Deselect All too).

**Comment by quentin41500** [comment]
@iad24 You can use the snapshot and select programmatically a range of date `materialCalendarView.selectRange(min, max)`: use your min and max date. https://github.com/prolificinteractive/material-calendarview/tree/future-1.x#major-change-in-140

**Comment by quentin41500** [comment]
I suggest you dive into the documentation a little, https://github.com/prolificinteractive/material-calendarview/blob/future-1.x/docs/README.md. This library contains tones of features and it's better if you learn more about those before implementing what you need. You will probably find what you are looking for.

**Comment by iad24** [comment]
Thanks for the quick reply. Sorry noob here. What do u mean by the snapshot? 
Also 1.4.0 havent been released yet right?

**Comment by quentin41500** [comment]
No, 1.4.0 is only available using the snapshot for now. A snapshot is a preview of the next release, it allow users to test and report bugs easily, so we can then make a final release version. We should release the 1.4.0 in the next few weeks or so. 

It should be available using compile 'com.prolificinteractive:material-calendarview:1.4.0-SNAPSHOT` i believe. 

If you want something more stable, you can always use the 1.3.0 release. I do think you can implement it without the `selectRange` even so it would be easier in my opinion.

**Comment by iad24** [comment]
yea. We can use 
public void setDateSelected(@Nullable CalendarDay day, boolean selected) for this.

thanks a lot man
