### ISSUE TITLE
Enable/Disable method.

### ISSUE THREAD

**Issue by ar-g** [prolificinteractive/material-calendarview#328]
I tried to disable calendar view `calendar.setEnabled(checked);` but it turns out to be that this method not implemented.

Any workarounds for this?  Meanwhile, I tried `setClickable()` it also not working. Probably can show another view over it but it seems quite a dirty solution.

**Comment by ekchang** [comment]
You can call `setSelectionMode(SELECTION_MODE_NONE)` to prevent dates from being clickable. Is that what you're looking to do?

**Comment by quentin41500** [comment]
@ar-g Feel free to reopen this issue if @ekchang solution does not work for you. Closing for now

**Comment by NumezmaT** [comment]
@ekchang solution does not work for me, me need select days and enabled select any
 day
