### ISSUE TITLE
How to add and view event detail in android material- calendar view?

### ISSUE THREAD

**Issue by sugeivan** [prolificinteractive/material-calendarview#330]

**Comment by quentin41500** [comment]
You might want to use decorators: https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md

**Comment by sugeivan** [comment]
from using that, we can  add background color to date, I want add description to that event

**Comment by quentin41500** [comment]
@sugeivan What do you mean by adding a description to an event ? Can you give us a screenshot or a sketch of what you are trying to do ? Im not sure that adding too much information to the calendar will makes the tiles too big and it's not intended. We want the calendar to stay simple and easy to use.

**Comment by sugeivan** [comment]
![screenshot_2016-06-03-09-39-26](https://cloud.githubusercontent.com/assets/9394146/15768699/c9bece86-2970-11e6-854a-2c88003f2a3f.png)
I want like this, when i click the date(in this case 19th) , that display the event(Poson full Moon poya Day). I finished put background color to this date

**Comment by sugeivan** [comment]
////////////////My code in Main Activity

       eventDay2 = CalendarDay.from(2016, 04, 18);
        type2.add(eventDay2);
        widget.addDecorator(new EventDecorator(type2, this));

////////////EventDecorator class

public class EventDecorator1 implements DayViewDecorator {

    private final HashSet<CalendarDay> dates;
    private final Drawable drawable1;


    public EventDecorator1(Collection<CalendarDay> dates, Context context) {
        this.dates = new HashSet<>(dates);
        drawable1 = ContextCompat.getDrawable(context, R.drawable.red_circle);
  }
@Override
    public boolean shouldDecorate(CalendarDay day) {

        return dates.contains(day);
    }
    @Override
    public void decorate(DayViewFacade view) {
       /* view.addSpan(new StyleSpan(Typeface.BOLD));
        view.addSpan(new RelativeSizeSpan(1.4f));
        view.addSpan(new DotSpan(10, Color.RED));*/
        view.setBackgroundDrawable(drawable1);
    }
}

**Comment by quentin41500** [comment]
This is not a feature from the Material CalendarView but you can do without it. 
Just set an `OnDateChangedListener`. When a new date is selected, populate a list with your events.

```java
widget.setOnDateChangedListener(new OnDateSelectedListener() {
            @Override
            public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {
                listAdapter.swapData(loadMyEvents(date.getDate()));
            }
        });
```

```java
private List<Events> loadMyEvents(Date date) {
        // TODO Load events from Date and return list
        return events;
    }
```

Use the decorator to display the dot, and that should be it.

**Comment by sugeivan** [comment]
What is swapData, I am new in Android, Can u explain more about u mentioned above???

**Comment by quentin41500** [comment]
@sugeivan swapData is just an example of a name function that should update your list in your ListView adapter or your RecyclerView adapter. Name it what you want.

**Comment by jabes93** [comment]
widget.setOnDateChangedListener(new OnDateSelectedListener() {
            @Override
            public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {
                listAdapter.swapData(loadMyEvents(date.getDate()));
            }
        });

private List<Events> loadMyEvents(Date date) {
        // TODO Load events from Date and return list
        return events;
    }

hello quentin41500 could you please drop your code here i find it difficult to understand it

**Comment by quentin41500** [comment]
@jabes93 This was just an example on how to update a list that displays a list of events based on a date.
You can just add a decorator to the MCV like this: `mcv.addDecorator(new EventDecorator(Color.RED, yourDay));`.

The sample app contains many examples, please take a look first. Post your bugs or question afterward.

Closing this issue as resolved.

**Comment by jabes93** [comment]
[material-calendar-issue.txt](https://github.com/prolificinteractive/material-calendarview/files/329015/material-calendar-issue.txt)

I posted already my concern and it looks the same problem with sugeivan and my second concern is displaying an event base on date created/ selected I already posted my code thank you very much. hope you could see it. Thanks in advance

**Comment by ofix-Parul** [comment]
Hello,

I want to paint a range of dates. Is there a way to do that. Sorry I am new to android.

**Comment by mariocasereses** [comment]
Can i add multiple DotSpans in a single day?

**Comment by poojalad** [comment]
Hi all,
I want to add a label below some dates in material- calendar view, same it is showing for events. Is there any to do this. Thanks in advance

**Comment by CoderAlok** [comment]
Can you please add the source code , i mean the MainActivity.java file to add and view the events in this calendar view. It will help me a lot
