### ISSUE TITLE
setOnLongClickListener for clicking dates

### ISSUE THREAD

**Issue by Evgen-skyline** [prolificinteractive/material-calendarview#335]
MaterialCalendarView have setOnLongClickListener method, but it not working. In my app, i need long click listner for selected date, is there anything suitable ?

**Comment by quentin41500** [comment]
We don't have any api for that yet. It's not on the roadmap either but if this gets upvoted maybe we'll add it

**Comment by rohitguptanm** [comment]
You can add new interface class for long click like below.
**1. Crate new interface class OnDateLongClickListener.class**

`package com.prolificinteractive.materialcalendarview;

import android.support.annotation.NonNull;

/**
 * The callback used to indicate a date has been selected or deselected
 */
public interface OnDateLongClickListener {

    /**
     * Called when a user clicks on a day.
     * There is no logic to prevent multiple calls for the same date and state.
     *
     * @param date     the date that was selected or unselected
     */
    void onDateLongClickListener(@NonNull CalendarDay date);
}
`
2. Edit addDayView method in CalendarPagerView class and implement View.OnLongClickListener 
` protected void addDayView(Collection<DayView> dayViews, Calendar calendar) {
        CalendarDay day = CalendarDay.from(calendar);
        DayView dayView = new DayView(getContext(), day);
        dayView.setOnClickListener(this);
        //Todo add onLongClickListener
        dayView.setOnLongClickListener(this);
        dayViews.add(dayView);
        addView(dayView, new LayoutParams());
        calendar.add(DATE, 1);
    }`

`// Todo onLongClick
    @Override
    public boolean onLongClick(View v) {
        if (v instanceof DayView) {
            final DayView dayView = (DayView) v;
            mcv.onDateLongClicked(dayView);
        }
        return true;
    }`

3. Add onDateLongClicked() and onDateLongClick() method in  MaterialCalendarView.java class 

` protected void onDateLongClicked(final DayView dayView) {
        final CalendarDay currentDate = getCurrentDate();
        final CalendarDay selectedDate = dayView.getDate();
        final int currentMonth = currentDate.getMonth();
        final int selectedMonth = selectedDate.getMonth();

        if (calendarMode == CalendarMode.MONTHS
                && allowClickDaysOutsideCurrentMonth
                && currentMonth != selectedMonth) {
            if (currentDate.isAfter(selectedDate)) {
                goToPrevious();
            } else if (currentDate.isBefore(selectedDate)) {
                goToNext();
            }
        }
        onDateLongClick(dayView.getDate());

    }`

` //Todo onLongMethod work
    protected  void onDateLongClick(@NonNull CalendarDay date){
        Log.d("MaterialCalenderView", "onDateLongClick: ");
        mOnDateLongClickListener.onDateLongClickListener(date);
    }`
