### ISSUE TITLE
how can i change monthView to Weekview with animation

### ISSUE THREAD

**Issue by BatenLang** [prolificinteractive/material-calendarview#337]
how can i change monthView to Weekview with animation

when i pull up the calendar view

**Comment by ekchang** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/278#issuecomment-218274439

You can set `android:animateLayoutChanges="true"` and `LayoutTransition#enableTransitionType(CHANGING)` on your parent layout.

**Comment by quentin41500** [comment]
Closing this issue, feel free to comment #278 if you need more info.
