### ISSUE TITLE
Change the English date to Nepali Date

### ISSUE THREAD

**Issue by krazziekay** [prolificinteractive/material-calendarview#338]
How can I change the English date system into Nepali date?? Using a English to Nepali date convertor plugin, is there anyway I can change the month and dates of this calendar view??

**Comment by quentin41500** [comment]
@krazziekay You need to use formatters. Here is the doc https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#custom-labels.

You should check the sample project, there is examples as well.
