### ISSUE TITLE
Set weekDay tile size

### ISSUE THREAD

**Issue by gmltA** [prolificinteractive/material-calendarview#339]
Is there any way to change week day tiles dimensions independetly from other tiles?

**Comment by quentin41500** [comment]
@gmltA What do you mean from other tiles ? Change the size using `setTileWidth` and `setTileHeight`

**Comment by gmltA** [comment]
@quentin41500 I want to set height of line with days of week to a specific value, but I don't want to change height of cells with dates.

**Comment by quentin41500** [comment]
I don't think you can. We would have to tweak the logic pretty significantly to make it works.

**Comment by sunwicked** [comment]
You can import the code in your project as a module and tweak the onMeasure() of CalendarPagerView.class something like the code sinppet below. 
```
// Modifying week view height to 3/4th of Tile Height
            if (child instanceof WeekDayView) {
                childHeightMeasureSpec = MeasureSpec.makeMeasureSpec(
                        measureTileHeight * 3 / 4,
                        MeasureSpec.EXACTLY
                );
            }
```

**Comment by plastus** [comment]
@sunwicked Your code works perfectly in that method. I also created my own topbar so now the spacing is much nicer. The use of regular calendar tile sizes for the top bar + weekdays puts too much white space by default.
