### ISSUE TITLE
Allow layout animation of the calendar view when switching between week and month modes

### ISSUE THREAD

**Issue by chuks** [prolificinteractive/material-calendarview#341]
Currently, when you call setCalendarDisplayMode(CalendarMode.MONTHS) or setCalendarDisplayMode(CalendarMode.WEEKS), the layout jumps between the views, making it look very abrupt. It would be great to enable layout changes, perhaps using enableTransitionType(LayoutTransition.CHANGING) or in xml android:animateLayoutChanges="true"

**Comment by ekchang** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/278#issuecomment-218274439

You can apply `animateLayoutChanges="true"` to the parent layout and setting `LayoutTransition#enableTransitionType(CHANGING)`. Because these are things that apply to the parent ViewGroup of MCV (and not MCV itself), it is not within the scope of changes we can apply to MCV.

**Comment by chuks** [comment]
Oh I've tried that, but that doesn't work. It still jumps between month and week view. I'd like a smooth scroll. I think it can be done within the ViewGroup holding the calendar view (I suppose it's a viewpager?). I have tried something like this, but that doesn't work:

`<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/content"
    android:orientation="vertical"
    android:background="@color/white"
    android:animateLayoutChanges="true"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <View
        android:id="@+id/top_bar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"/>

    <com.prolificinteractive.materialcalendarview.MaterialCalendarView
        android:id="@+id/calendar"
        android:layout_below="@+id/top_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:mcv_selectionColor="@color/white"
        app:mcv_dateTextAppearance="@style/CustomTextAppearance"
        app:mcv_headerTextAppearance="@style/CustomHeaderTextAppearance"
        app:mcv_weekDayTextAppearance="@style/CustomWeekDayTextAppearance"
        app:mcv_showOtherDates="none"/>

</RelativeLayout>`

**Comment by yatindeokar** [comment]
This solution dos not work for me

**Comment by chuks** [comment]
@ekchang this does not work. I think it needs to be enabled from within the library itself.

**Comment by AkhilDad** [comment]
@chuks It doesn't work because it changes the adapter, I am struggling with the same.
Any idea if one can apply animation while setting/removing the adapter to viewpager?
I am unable to find out a way to do that

**Comment by chuks** [comment]
Aha , that makes sense. One way would be to put the calendar view inside a LinearLayout that has animateLayoutChanges set to true.
