### ISSUE TITLE
Runtime error regarding RippleDrawable

### ISSUE THREAD

**Issue by jasperrietrae** [prolificinteractive/material-calendarview#343]
Hi. Thanks for the great library.

I'm getting this error during runtime sometimes (on Android 4.0.4, 5.1.1, 6.0.1 and 6.0.2):

`E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method com.prolificinteractive.materialcalendarview.DayView.generateRippleDrawable`

**Comment by quentin41500** [comment]
@Discover- Repro steps? code snippet?

**Comment by quentin41500** [comment]
generateRippleDrawable should only happen on Android 4.0.4 and above so something is weird with what you are getting, I wonder if this is still happening in the latest releases.

**Comment by jasperrietrae** [comment]
Sorry I honestly have no idea after 2 years 🙈

**Comment by quentin41500** [comment]
No problem! Hopefully you found a solution at the time, sorry for the delay
