### ISSUE TITLE
Option to disable decorators for "other days" outside the current month

### ISSUE THREAD

**Issue by StrangeLooper** [prolificinteractive/material-calendarview#344]
Is there currently any way to prevent a decorator from getting applied to "other days" around the current month in view? 

In the below screenshot, there is a decorator that highlights "today" in dark blue. We do not want this to be shown if "today" is in the "other days" around the month in view.

Is there any way to do this currently within the decorator framework? If not, is there a possibility of adding a method to set this option on the calendar view or the decorator itself? Hiding the "other days" is not a valid option for our use case.

![other_day_decorator_example](https://cloud.githubusercontent.com/assets/2363229/15977274/c6ec3922-2f25-11e6-8f53-f081df0fcf5d.png)

**Comment by quentin41500** [comment]
@StrangeLooper I suggest you just disable the `other days` features. Displaying `other days` without any decorations or selected days is contradictory with the idea of this feature. We are not planning to implement something like this, sorry about that.

Closing for now, let me know if you have any more questions
