### ISSUE TITLE
Localization Problem

### ISSUE THREAD

**Issue by oguzozcan** [prolificinteractive/material-calendarview#347]
Changing language configuration doesn't change the language of the dates because Calendar instance used in the library doesn't use Locale object. Thus changing locale has no impact.

**Comment by quentin41500** [comment]
@oguzozcan When changing the language of my phone, the calendar changes the month's title and the days' title. Im not sure what you are talking about. It's working as expected. Can you please explain a little bit more the bug you are facing? Maybe you could provide screenshots?

You can try with the sample app to see if it's working properly.

**Comment by oguzozcan** [comment]
Hello, I am changing the language from the app (getting the default locale and setting the user selected one). Activity restarts and all my text fields changes languages as expected apart from calendarview titles. I can send you a screenshot if this is not clear.

**Comment by oguzozcan** [comment]
![screenshot_2016-06-22-22-44-20](https://cloud.githubusercontent.com/assets/6877185/16281058/369dd38a-38cb-11e6-80b7-44e371ed4425.png)

As you can see all fields are in english except calendar texts, they are in Turkish (phones language was turkish but i changed it to english)

**Comment by quentin41500** [comment]
Material CalendarView is always going to use the language of the phone. You can however set custom labels yourself using https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#custom-labels. 
For example you can set english months and days like this:
```java
widget.setTitleFormatter(new MonthArrayTitleFormatter(getResources().getTextArray(R.array.custom_months)));
widget.setWeekDayFormatter(new ArrayWeekDayFormatter(getResources().getTextArray(R.array.custom_weekdays)));
```
```xml
 <string-array name="custom_weekdays">
        <item>Su</item>
        <item>M</item>
        <item>Tu</item>
        <item>W</item>
        <item>Th</item>
        <item>F</item>
        <item>Sa</item>
    </string-array>

    <string-array name="custom_months">
        <item>JAN</item>
        <item>Feb</item>
        <item>MARCH</item>
        <item>April</item>
        <item>MAY</item>
        <item>June</item>
        <item>JULY</item>
        <item>Aug</item>
        <item>SEPT</item>
        <item>Oct</item>
        <item>Nov</item>
        <item>DEC</item>
    </string-array>
```
Let me know if you have any more questions.

**Comment by quentin41500** [comment]
You can then set different custom lists per languages.

Closing this issue as resolved, let me know if you have more questions.

**Comment by oguzozcan** [comment]
No, this would work as well. Thank you.

**Comment by hoaipanda** [comment]
Can change font text for this ?

**Comment by pavelsust** [comment]
how i can change data number to another language.
