### ISSUE TITLE
Is it possible to change the color of Sunday's

### ISSUE THREAD

**Issue by binil1931** [prolificinteractive/material-calendarview#348]
I need a calendar view show all Sunday's color as RED. 

![calendar view](https://cloud.githubusercontent.com/assets/2820292/16069561/0e8f2792-32ed-11e6-9d06-8975c457345c.PNG)

Here in the picture all the sundays's text color is set as RED. Is it possible here by using Material calendar view.

**Comment by emitchel** [comment]
I'm pretty sure you could extend the Decorator class and pass your custom Decorator all the Sundays in your collection of days (might be a lot) - then the decorator knows what days are Sundays. Your Decorator would need to apply a span that colors the day red. Let me know if you have any issues

**Comment by quentin41500** [comment]
Closing this issue as resolved, thanks @emitchel
