### ISSUE TITLE
setDecorator doesn't update the UI

### ISSUE THREAD

**Issue by kolbasan** [prolificinteractive/material-calendarview#35]
I am setting the decorator with dates that i get from http request.
Calling setDecorator doesnt update the UI at all, however, when I move few months away, and
go back, the decorators are set correctly.
My code looks as the one in the sample with one exception: setDecorators is called outside the onCreate method (at the http resposne method).

Any input regarding this issue will be helpful.

**Comment by dandc87** [comment]
Hi @kolbasan , I've been working on improving the decorators. Would you be willing to test `0.4.0-SNAPSHOT` and let me know if its better? Directly manipulating text will no longer be supported, instead you are allowed to set spans and I added an new `DotSpan` to the library. The samples were updated to use the new APIs too.

**Comment by dandc87** [comment]
Closing now that 0.4.0 is released.
