### ISSUE TITLE
Prevent decoration of selected date

### ISSUE THREAD

**Issue by Maragues** [prolificinteractive/material-calendarview#350]
I'm decorating some dates using spans, which I'd like to not be drawn when the date is selected (the circle in the first image has a white stroke)

![image](https://cloud.githubusercontent.com/assets/655970/16114397/540ff2d6-33c1-11e6-82a7-60afa1c4703f.png) 
![image](https://cloud.githubusercontent.com/assets/655970/16114428/7b86f346-33c1-11e6-8a3c-e7905bd4487b.png)

I can think of 2 solutions, tho I haven't looked too much into the code

1. Support customization in *MaterialCalendarView* (some kind of *.shouldDecorateSelectedDate(boolean)*)
2. Give access to the date inside *decorate(DayViewFacade)*, as requested in https://github.com/prolificinteractive/material-calendarview/issues/270. Combined with an *OnDateSelectedListener*, we could avoid decoration of the selected date.

**Comment by emitchel** [comment]
The only way I was successfully able to get a different look when selected is by using `DayViewFacade.setBackgroundDrawable` and using a selector to decide which drawable to use. It actually works flawlessly but obviously you'll have to ditch the span and step into the _pain in the ass_ world of drawing in background drawables. 

Here's one of mine to get you start 
https://i.gyazo.com/f3a9212380d6557fab34b6366d7a5617.png

**Comment by quentin41500** [comment]
@Maragues Or you can just remove the white stroke and replace by a transparent one. You might have to tweak your icon a little bit so you keep the same design, but at least it's a more viable solution.

**Comment by quentin41500** [comment]
Let us know if you have any more questions, closing this issue for now.
