### ISSUE TITLE
Add other month days until week row is filled

### ISSUE THREAD

**Issue by Maragues** [prolificinteractive/material-calendarview#351]
I'd like to show other month dates, but I don't want to add an entire row with other month days. Something like this

![image](https://cloud.githubusercontent.com/assets/655970/16124317/c720d29a-33ee-11e6-9ef0-752e8fdf2590.png)

Currently, _mcv_showOtherDates_ fills the 6 week rows with CalendarDay, but it would be nice if we could specify a new _showOtherDates_ mode, for example _fill_week_

I guess this could be done by creating a Decorator in onDateSelected and dynamically calculating which dates fit, but it would be nice if the library provided an easier way

**Comment by emitchel** [comment]
Even in the most popular calendar apps (Google Calendar, native android calendars) you'll sometimes see an entire week of the following month. Likely for design reasons since you either A) don't show those days and leave that area _blank_(white space no-no) or B) remove the access space in which case would make the surrounding views constantly jump since that extra week is there quite often (assuming the calendar is swipe-able).

**Comment by Maragues** [comment]
The area is already left blank if you choose to not show other months. The space is there so that there's no jumping.

**Comment by quentin41500** [comment]
As @emitchel said, there is some design issues where the calendar would contain 5 rows instead of 6. PRs are welcome if you manage to make it work, but it's not on the roadmap.

**Comment by Maragues** [comment]
@quentin41500 I understand that, I probable expressed my self wrong, since you both understood the same.

I meant always keeping space for 6 weeks but offer a new *showOtherDates* option where the first and last week of the month was filled with othermonthDates, as in the screenshot in the first post

**Comment by quentin41500** [comment]
@Maragues So what is the difference with the current `showOtherDates` feature?

**Comment by Maragues** [comment]
Taking current June as example with weeks starting on sunday, my suggested scenario would be as follows

1st week would display

[29] [30] [31] [1] ....

5th week would display

[26] [27] [28] [29] [30] [1] [2]

**6th week would be empty**, but its vertical space untouched

With current *showOtherDaysOption*, 6th week would be

[3] [4] [5] ...

Sorry for using text instead of screenshots, I hope I made my idea clear

**Comment by quentin41500** [comment]
Ok I see what you are trying to accomplish. It's not on the roadmap, but I will leave this issue open in case anybody wants to pick it up and make a PR for it.

**Comment by Maragues** [comment]
Thanks for the input. I investigated a little but it wasn't easy. 

Anyway, since I'd also need https://github.com/prolificinteractive/material-calendarview/issues/344 implemented, for now I've told the designer that we'd better not display other month dates :-)

**Comment by quentin41500** [comment]
This is actually now part of the library using this:
```
    /**
     * By default, the calendar will take up all the space needed to show any month (6 rows).
     * By enabling dynamic height, the view will change height dependant on the visible month.
     * <p>
     * This means months that only need 5 or 4 rows to show the entire month will only take up
     * that many rows, and will grow and shrink as necessary.
     *
     * @param useDynamicHeight true to have the view different heights based on the visible month
     */
    public void setDynamicHeightEnabled(boolean useDynamicHeight) {
        this.mDynamicHeightEnabled = useDynamicHeight;
    }
```

Closing!
