### ISSUE TITLE
How to showing event on Date selected

### ISSUE THREAD

**Issue by AdamFM** [prolificinteractive/material-calendarview#352]
In my calendar i decorate event with dot span, and how can i know that day is event day which is decorated with dot span??

*sorry my english is bad

**Comment by quentin41500** [comment]
Hey @AdamFM. If you are adding the decorator like this `widget.addDecorator(new EventDecorator(Color.RED, calendarDays));`, you can just keep a copy of `calendarDays` when you create the Decorator. You can't get the decorated days for the MaterialCalendarView itself.

Reopen if you have more questions, closing for now

**Comment by khent04** [comment]
So you mean @quentin41500 , there is now way to retrieved the event decorated?
for example, I have a list of dates, and I decorated it to the calendar view, when i click the decorated dates, I cannot get what the event I placed for each of the decorators?

**Comment by 1jGabriel** [comment]
When you click in a date, check if your event list, contains da clicked date, and do something

**Comment by dsounded** [comment]
@quentin41500 can you please tell if there is a chance to know what event is clicked from decorated dateview once we have multiple marks e.g. https://github.com/prolificinteractive/material-calendarview/issues/753

Use case: we have 2 events on this date (A and B) and we want to remove B, that will be good to know what dot is clicked to remove specific one.

I understand we can show all the events on click, but I am curious if we can do it better (without additional "Show all" step)
