### ISSUE TITLE
Highlight a specific date in calendar

### ISSUE THREAD

**Issue by nandha444** [prolificinteractive/material-calendarview#355]

**Comment by emitchel** [comment]
https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md

Decorators will help you :) good luck

**Comment by nandha444** [comment]
emitchel i want to decorate a single date how to do it im a noob can u help me plz

**Comment by quentin41500** [comment]
@nandha444 You can refer to the sample app and the documentation. It's complete and up-to-date. Once you try it, let us know what is not working for you

**Comment by quentin41500** [comment]
Closing this issue for now, reopen if you have more questions
