### ISSUE TITLE
onRestoreInstanceState not restoring selectedDates

### ISSUE THREAD

**Issue by Androidert** [prolificinteractive/material-calendarview#357]
It looks like clearSelection()(Line 1072 @ MaterialCalendarView.java) clears all selected dates before they are reset.
After clearSelection() ss.selectedDates is empty and the for loop is never executed.

**Comment by quentin41500** [comment]
@Androidert Thank you for submitting the issue. It seems to be working for me on the sample app. Did you try it there or on your application? If you could try the sample and let me know. You can try in DynamicSettersActivity.

**Comment by Androidert** [comment]
The bug only happens when I go back to the material-calendarview by using popBackStack.
When I rotate the screen the material-calendarview gets recreated(no bug), when I use popBackStack the material-calendarview gets reinitialized(bug). 

When I rotate ss.selectedDates stays at 1 after clearSelection().
When I popBackStack  ss.selectedDates goes to 0 after clearSelection().

**Comment by quentin41500** [comment]
I don't understand, if you have removing fragments from the back stack will not impact the Material CalendarView. It seems like your issue might be coming from your code rather than the library itself. 

You can look at the sample app for more information.

**Comment by Androidert** [comment]
You're right, my code produced this bug. *Bangs head on wall*
Thanks for your support!
