### ISSUE TITLE
Saving and restoring events added with the SELECTION_MODE_RANGE

### ISSUE THREAD

**Issue by joaosardinha** [prolificinteractive/material-calendarview#359]
It's easy to save a single date into sharedprefs, just by storing the day, month and year values, but what about saving a range of dates without saving each, one by one, and then get them to decorate them?

**Comment by quentin41500** [comment]
I'm not sure your question is directly related to this library. You have different way to save data and there is a lot of blog post out there that will explain it better than me. Please keep your question related to this library, thank you!
