### ISSUE TITLE
Is there a way to highlight dates?

### ISSUE THREAD

**Issue by raahulbiswas** [prolificinteractive/material-calendarview#36]
If I have an array of dates, is there a way to have them highlighted in the calendar view using this library?

**Comment by dandc87** [comment]
Hey @raahulbiswas, there isn't a built-in highlighter, but you can implement and set a `DayViewDecorator` that can set custom background or modify the text of particular dates (look at `BasicActivityDecorated` in the sample app). 

Please note, there are reported performance issues with decorators, and the API for decorating may change to fix those issues.

**Comment by raahulbiswas** [comment]
Thanks so much, I managed to get it working and it seems to be working fine for me now. What are the performance issues I might face cause I haven't seen any yet?

**Comment by dandc87** [comment]
I was mostly referring to issue #30, but #33 and #35 are also worrisome.
