### ISSUE TITLE
Date selection not smooth when adding event

### ISSUE THREAD

**Issue by joaosardinha** [prolificinteractive/material-calendarview#360]
Not sure if I'm missing something, but I noticed that when I click on a day to add it a decorator, the animations of the selector don't happen. Below there's a video do explain, firstly I click on days without adding a decorator and it's beautifully smooth, when I active the decorator adding, it stops beeing so smooth, the fading animations are gone, and after I click on a date, the previous one remains selected for some nanoseconds, it can be seen more easily in a low-end device.

https://vimeo.com/171986927

The diffrence is quite subtle because this emulator is too fast, on my low end phone it's quite unsatisfactory

**Comment by quentin41500** [comment]
This might be due to decorators being very slow. There is some performance issues, check #234 for more details.

**Comment by joaosardinha** [comment]
Could it be related with the invalidation? When I added `invalidateDecorators()` in the onDateSelected, the smoothness was gone, wether I was adding a decorator or not

**Comment by quentin41500** [comment]
I think so, there is definitely some performance issues related to decorators. Feel free to investigate if you need it to be fixed.

**Comment by joaosardinha** [comment]
Unfortunately I won't be able to do so, I have a lot of work right now, I'll just keep an eye on the post 234, if you believe they are the same problem feel free to close this one!

**Comment by quentin41500** [comment]
Sounds good, thanks for reporting it @joaosardinha, hope it will works out for your situation
