### ISSUE TITLE
Adding two DotSpans in one date

### ISSUE THREAD

**Issue by joaosardinha** [prolificinteractive/material-calendarview#361]
Is there any way to check if a date already has a decorator? Something like `mCalendarDay.hasDecorator()` would be awesome. 

I'm trying to check if a date already has a dotSpan, so I can adjust the padding of the previous one allowing both to be aligned

**Comment by quentin41500** [comment]
I see what you want but there is no methods to know if there is decorators on the tiles as of right now.

**Comment by quentin41500** [comment]
You can create a custom decorator that would display multiple dots. You just need to save the number of dots for each date on your end. Documentation is here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md
