### ISSUE TITLE
Disabled days selected with range mode

### ISSUE THREAD

**Issue by a1018875550** [prolificinteractive/material-calendarview#362]
I set some days to disable and the mode is "SELECTION_MODE_RANGE";  when I selete two date it whill contain the disable days  ;like this:
![023ae709406aaad1689dda01097e60f6](https://cloud.githubusercontent.com/assets/8246218/16513720/6c2694c2-3f99-11e6-8971-293d1b2fb107.jpg)
![b50381636484ecc898ce47eaad5846a7](https://cloud.githubusercontent.com/assets/8246218/16513724/7269efb4-3f99-11e6-88e2-8c16529518de.jpg)

how can I skip the disable days?

**Comment by a1018875550** [comment]
and when I set the  "SELECTION_MODE_RANGE" mode;how can I get the second date?

**Comment by quentin41500** [comment]
Sorry for the late reply. Visually, you could just change the selection drawable to transparent like so:
```
@Override
    public void decorate(DayViewFacade view) {
      view.setDaysDisabled(true);
      view.setSelectionDrawable(new ColorDrawable(Color.TRANSPARENT));
    }
```
You would also need to filter the list that you get within your range listener to make sure you are not accounting for the disabled days.
