### ISSUE TITLE
Gradle build failing when including latest version

### ISSUE THREAD

**Issue by sahild** [prolificinteractive/material-calendarview#364]
I included this compile 'com.prolificinteractive:material-calendarview:1.4.0' in my gradle dependencies and it did not work. I had to downgrade it to v1.2.0 to make it work. Please fix this. I need to use the week view desparately.

**Comment by quentin41500** [comment]
I would check your gradle file. It's working properly for me.

**Comment by quentin41500** [comment]
At least provide us your implementation

**Comment by sahild** [comment]
I tried it again and it worked. It seems there was some problem with my build.gradle file. Thanks for quick response though and apologies for responding late. Closing the issue.
