### ISSUE TITLE
Using this library in a Xamarin Android project

### ISSUE THREAD

**Issue by amendezcabrera** [prolificinteractive/material-calendarview#369]
Hi, this is not an issue and I understand this library isn't developed thinking in Xamarin, but I would only ask if anybody knows how to bind it to a Xamarin Android project. I just got to see the calendar in my view but I can't instantiate it.
Any help would be really appreciated.

**Comment by Dimabiz** [comment]
This is ready project for xamarin android https://github.com/sreerajPR/Xamarin.MaterialCalendarView

**Comment by quentin41500** [comment]
Oops I deleted the link: https://github.com/sreerajPR/Xamarin.MaterialCalendarView

**Comment by quentin41500** [comment]
Feel free to reopen if you have other issues.

**Comment by amendezcabrera** [comment]
Hi again @quentin41500 I have seen this binding before but it uses the v1.2.0 of MaterialCalendarView, I tried to adapt it to the latest version recompiling the library adding it and setting the metadata like the linked project does but without success, the only achieve I made doing this is to show the calendar in the view as I said in my first comment, but it can't be instantiated.

**Comment by quentin41500** [comment]
@amendezcabrera I don't know much about Xamarin. I would suggest you post your questions in the issue section of the linked library, you might have more chances there to get an answer.

**Comment by amendezcabrera** [comment]
Ok, I will try, thank you very much

**Comment by alejo740** [comment]
Hello Guys, have you been successful with this issue? I cannot also instantiate it into a class.
