### ISSUE TITLE
Is there a way to turn off the selected date or make non highlighted dates not clickable?

### ISSUE THREAD

**Issue by raahulbiswas** [prolificinteractive/material-calendarview#37]

**Comment by raahulbiswas** [comment]
I fixed this by making the selector colour = my background colour in the XML and editing the mvc_text_date_light.xml file and setting the selected state colours to black instead of white.

**Comment by xarlotie** [comment]
What about the highlighted (selectable) dates? How do you set the selector for those dates if you've set the selector color the same a your background? Is there a dynamic way to change the selector color every time depending on which date you choose?

**Comment by dandc87** [comment]
@xarlotie you can use a DayViewDecorator to change the appearance of certain days (like changing the selection drawable and text color). If you want true day disabling, please vote for #21 with a "+1".

**Comment by xarlotie** [comment]
Got it! But I'm still left with a text color that does not change with state changes. I can already set background as the states change but not the text color. Is there a way to do that? Thanks!

**Comment by yash59** [comment]
@xarlotie did you find any solution?
