### ISSUE TITLE
How to disbale selection of dates and set round drawable of different colors

### ISSUE THREAD

**Issue by narendrakothamire** [prolificinteractive/material-calendarview#370]
Thanks for amazing work
What I want is disable selection of date on click and I want to show round drawables of different colors for some dates eg. if employee is absent on particular date i want red round drawable and green if he is present
also i want sunday dates in red

**Comment by quentin41500** [comment]
I would suggest you take a look at the documentation and the sample app. There is concrete examples for you to implement what you need. Giving you code snippet here would result copy and pasting stuff from the sample or documentation. You can post your snippet if you have issues with the library. I will be happy to fix it for you then.
