### ISSUE TITLE
Press day in next month go to last month

### ISSUE THREAD

**Issue by zichong** [prolificinteractive/material-calendarview#374]
In current month view, if we press a day in next month, calendar should go to next month.
But sometimes it does not go to next month but go to last month.
For instance, in Dec 2016, we press "3" which means Jan 3rd 2017. It should go to Jan 2017 but it doesn't.

![2016-dec](https://cloud.githubusercontent.com/assets/3186016/17050315/c902143c-5024-11e6-9cb3-9eb1f4b5b2cb.png)

It goes back to Nov 2016.
![2016-nov](https://cloud.githubusercontent.com/assets/3186016/17050314/c8fb41d4-5024-11e6-83b2-164cfa78bf6a.png)

This bug occurs in every Dec.
Similar problem in Jan if day in last month is pressed. It doesn't go back to last Dec but go Feb.

**Comment by quentin41500** [comment]
Nice catch

**Comment by quentin41500** [comment]
Fixed in v1.4.2
