### ISSUE TITLE
Arrow masks not working

### ISSUE THREAD

**Issue by andrewlord1990** [prolificinteractive/material-calendarview#375]
I assign mcv_leftArrowMask and mcvRightArrowMask on the view, but it still displays with the default arrow drawables. Upon checking the code, the method `setupChildren()` is called at the bottom of the constructor, which is after the custom arrow mask drawables have been set. This means the custom ones are overwritten with the default ones.

This must have been changed in the most recent release, as it worked fine before I updated to latest version of the library. Tried looking through the commit history, but didn't find the commit that caused this.

**Comment by RomanSytnyk** [comment]
I have this bug too

**Comment by johnriot** [comment]
I have this bug too (only when setting masks via XML: via Java code works fine).

**Comment by quentin41500** [comment]
Fixed in v1.4.2
