### ISSUE TITLE
'Today' indicator does not update in real time.

### ISSUE THREAD

**Issue by simondrabble** [prolificinteractive/material-calendarview#378]
I have a DayViewDecorator as follows:

```
 public class TodayDecorator implements DayViewDecorator {

    private Drawable mDrawable;

    public TodayDecorator(Drawable drawable) {
        mDrawable = drawable;
    }

    private boolean isToday(CalendarDay day) {
        Calendar cal = Calendar.getInstance();
        if (cal.get(Calendar.YEAR) == day.getYear()
                && cal.get(Calendar.MONTH) == day.getMonth()
            && cal.get(Calendar.DAY_OF_MONTH) == day.getDay()) {
            return true;
        }

        return false;
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return isToday(day);
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.setBackgroundDrawable(mDrawable);
    }
}
```

which works as expected, applying a highlight to the current day. Unfortunately this does not get updated in real time (as the date changes), possibly due to use of a ViewPager to draw the month pages. What this means is, if you are looking at the calendar view and the date rolls over, the view does not update until you page forward/ backward enough to invalidate the original view.

I'm toying with the idea of setting up a handler that pokes any bound activity to refresh the calendar widget when the date changes, but this seems kinda heavyweight, so I was wondering if there was a more elegant way to refresh the view when the date itself changes. 

For reference, the Google Calendar app does not update either, so it's not a huge issue, but if there's an easy, elegant solution please let me know.

**Comment by quentin41500** [comment]
I would suggest handling the update yourself. You can refresh the calendar once the date change. You just need to find a way to know when the date would be changing (maybe a broadcast receiver????)
