### ISSUE TITLE
onMonthChanged does not work

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#38]
I do not know why, but when I click on month button, then nothing happens. What can I do wrong?
Your test code obviously works.

my code:
http://paste.ofcode.org/EGipjmEmzfwjN2bcuKKRAt

**Comment by raplider** [comment]
add   widget.setOnMonthChangedListener(this)

**Comment by kamilwlf** [comment]
Thanks , I forgot about it.
