### ISSUE TITLE
Align drawable using setBackgroundDrawable on API 21

### ISSUE THREAD

**Issue by victor-vct** [prolificinteractive/material-calendarview#381]
Hi!
I'm trying set circle on DayViewDecorator using setBackgroundDrawable.

When I use this on API 19, 20, 22, 23, it's work. But on API 21 don't stay on center

API 21:
![api 21](https://cloud.githubusercontent.com/assets/13304329/17258467/6561cebc-559d-11e6-8d44-407d5387c79b.PNG)

API 23 and others:
![api23](https://cloud.githubusercontent.com/assets/13304329/17258475/6bfeee58-559d-11e6-9d7f-9067a909ba0b.PNG)

**Comment by quentin41500** [comment]
Seems to be working now, closing
