### ISSUE TITLE
change font of mcv_below_weekday_separator and mcv_below_header_separator

### ISSUE THREAD

**Issue by ir2pid** [prolificinteractive/material-calendarview#382]
changing the font doesn't take any effect, only colour and size gets changed

> app:mcv_weekDayTextAppearance="@style/CustomWeekDayTextAppearance"

where CustomWeekDayTextAppearance has a different font specified

**Comment by Niroj08** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/582

**Comment by quentin41500** [comment]
now in https://github.com/prolificinteractive/material-calendarview/pull/782
