### ISSUE TITLE
DayViewFacade's background drawable can't center in Lollipop

### ISSUE THREAD

**Issue by SteveMobile** [prolificinteractive/material-calendarview#388]
Hi,
I check the code, 
private void calculateBounds(int width, int height) {
        final int radius = Math.min(height, width);
        **// Lollipop platform bug. Rect offset needs to be divided by 4 instead of 2**
       **_// this will cause DayViewFacade's can't center_**
        final int offsetDivisor = Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP ? 4 : 2;
        final int offset = Math.abs(height - width) / offsetDivisor;

```
    if (width >= height) {
        tempRect.set(offset, 0, radius + offset, height);
    } else {
        tempRect.set(0, offset, width, radius + offset);
    }
}
```

So can you help me, How to center the DayViewFacade's background drawable ?

ThankYou

**Comment by quentin41500** [comment]
Seems to be working now, closing
