### ISSUE TITLE
Wrong week after setSelectedDate(), issue with scroll

### ISSUE THREAD

**Issue by antonkrasov** [prolificinteractive/material-calendarview#390]
Hello,

I saw this issue: https://github.com/prolificinteractive/material-calendarview/issues/222 , but I think I have another one.

So I have CalendarView with WEEKS mode. Also I have another view, where I can scroll and select another day, so after this I call: 

```
mWeekView.setSelectedDate(calendar.getTime());
mWeekView.setCurrentDate(calendar.getTime());
```

but after 12 November if I try to change date to 13 November, week doesn't scroll right.

Please check this video, to understand what I'm talking about: https://www.dropbox.com/s/tqx2r0hzudvh7pz/bug_with_scroll.mov?dl=0

For all weeks before 12 November works correctly..

I used logs and double check that November 13 passed correctly to setSelectedDate...

Please let me know, if you need any other info.

Thanks.

**Comment by hemant3370** [comment]
@antonkrasov Did you find any solution?

**Comment by antonkrasov** [comment]
@hemant3370 not really

**Comment by MahendraRaj** [comment]
try using setCurrentDate()
