### ISSUE TITLE
How to display selected Day on Title (month view mode) ?

### ISSUE THREAD

**Issue by phamthanhtong** [prolificinteractive/material-calendarview#393]
As my topic, I try to format title. But day of Title always display first day of month "01". 
So, How to change value day of Title after user selected a day ?
If you can, please help me. Thank you!
Please view this screen: 
![screen shot 2016-08-26 at 4 48 35 pm](https://cloud.githubusercontent.com/assets/20292327/18001491/64dbf65e-6bad-11e6-991d-92d355bdd601.png)

**Comment by quentin41500** [comment]
Im not sure how to do that, I would suggest using a custom label and display your date there using `OnDateSelectedListener`. Let me know if that doesn't work for you.

Closing this issue for now
