### ISSUE TITLE
Error in August month

### ISSUE THREAD

**Issue by kundansviet** [prolificinteractive/material-calendarview#395]
setOnDateChangeListener return 7 for august moth.

**Comment by sunnykinger** [comment]
I am facing the same issue. I am using week mode.

**Comment by kundansviet** [comment]
Actually month starts from 0 and ends on 11 so not a big problem.

**Comment by quentin41500** [comment]
Yes, months are calculated from 0 to 11 using the programming format. Let me know if you have any further questions!

Closing this issue for now
