### ISSUE TITLE
How to set list of selected dates to calender programatically

### ISSUE THREAD

**Issue by Subhash7** [prolificinteractive/material-calendarview#397]
Hi,
- To display single selected date, i can use materialCalendarView.setSelectedDate(CalendarDay.today()); 
- But how to apply list of selected dates to calender view ?
- If possible please reply the solution.

**Comment by SsKarthi** [comment]
How you solve this.. Plz explain.. Advance tanx

**Comment by Subhash7** [comment]
Make sure that the calendar is in multi-selection mode
For each day you want to select, call calendar.setDateSelected(myDay, true). It accepts Dates, Calendars, or CalendarDays

You can see at issue How select multiple dates? #157 
As their discussion i called calendar.setDateSelected(myDay, true) every time when i want to select individual date.
