### ISSUE TITLE
Is there a way to change the background of the header?

### ISSUE THREAD

**Issue by KwonSeokChan** [prolificinteractive/material-calendarview#399]
I would want to change the background color of the Header. However, I do not know very way. The visible of the current Top bar is set to false, and are used to create a direct Header. Is there a precise way that it is possible to change the color?

Sentence is created by using the translation. I'm sorry.

**Comment by quentin41500** [comment]
Take a look here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#text-appearances. 

You can customize the header and therefor probably change the background. Let me know if that doesn't work for you.

Closing for now

**Comment by and4test** [comment]
How can I change the background color of header?
I am using setHeaderTextAppearance (), but I can not set it.
Only TextColor will be changed, but BackgroundColor can not be changed.
