### ISSUE TITLE
How to clear TextDecorator?

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#40]
How to clear all TextDecorator?

![screenshot_2015-05-05-08-03-18 1](https://cloud.githubusercontent.com/assets/7765963/7467654/be831d10-f2fd-11e4-8609-b5751d5938f7.png)

widget.removeDecorators() delete all decorators but i want delete only TextDecorator, i dont want delete HighlightWeekendsDecorator()

On the other hand, i dont want use loop to delete each individual with:
widget.removeDecorator();

**Comment by kamilwlf** [comment]
widget.removeDecorators();

**Comment by dandc87** [comment]
Hi @kamilwlf, I've been working on improving the decorators. Would you be willing to test `0.4.0-SNAPSHOT` and let me know if its better? Directly manipulating text will no longer be supported, instead you are allowed to set spans and I added an new `DotSpan` to the library. The samples were updated to use the new APIs too.

**Comment by dotnick** [comment]
@dandc87 I made a patch from your PR and applied it to my fork. Its way faster for me. I'm planning on doing an app release in the next few days so I'll report any issues that come up.

**Comment by dandc87** [comment]
Closing now that 0.4.0 is released
