### ISSUE TITLE
 title of the header shows a reduction of one in the month

### ISSUE THREAD

**Issue by b1234569856** [prolificinteractive/material-calendarview#401]
When the data in the first week of the month is selected, as in the case of the first week of the month, when switching to a weekly mode, the title of the header shows a reduction of one in the month.

**Comment by quentin41500** [comment]
Thank you for mentioning this. This is actually normal behavior, the first day of the week is what determines which month is displayed. For example, if you select 2nd of September, and switch to week mode, it will show August as the first day is from the previous month.

Hope that makes sense to you! Feel free to ask more questions if you need.

**Comment by b1234569856** [comment]
Ok, thank you for your answer
