### ISSUE TITLE
how to back to currentdate quickly when i'm in the other date?thank you!

### ISSUE THREAD

**Issue by kobeky** [prolificinteractive/material-calendarview#402]

**Comment by skarempudi** [comment]
If you mean how to set the current date programmatically, then for your MaterialCalendarView instance, you can call setSelectedDate() with Calendar.getInstance().getTime().

**Comment by quentin41500** [comment]
I will close this issue as resolved. Thanks @skarempudi, @kobeky if you have more questions, do not hesitate to reopen this one.
