### ISSUE TITLE
Status of TODO in sample app?

### ISSUE THREAD

**Issue by skarempudi** [prolificinteractive/material-calendarview#404]
The README for the sample app includes this section:

## TODO

_We need to revamp/reorganize the samples to be less redundant and more comprehensive._

The README was last updated a year ago. Before I start working on this, is it the case that the README alone has to be updated and this task has already been completed, or is there still work to be done? In the latter case, I would appreciate additional details about what examples are expected, otherwise I'll change things on my own on my fork and send a pull request.

**Comment by quentin41500** [comment]
@skarempudi I do like the way the sample app is done, it has great and complete examples. There might be improvements possible here and there and would love to hear your opinion on that. Let me know what your ideas are. Otherwise, I will just turn this issue into removing this TODO line.
Thank you very much for your help.

**Comment by skarempudi** [comment]
In other issues, I've noticed people describing cases where they have multiple MaterialCalendarViews in the same layout and where they have multiple decorators on the same calendar. If these are common enough use cases, it may be worth creating Activities in the sample for them. There could also be an example to demonstrate how to integrate the calendar into Material Design (not affecting the other examples).

**Comment by quentin41500** [comment]
@skarempudi That would be great

**Comment by skarempudi** [comment]
Whoops, mistakenly wrote Material Design when I meant Data Binding. Anyway, I can work on it later this week.
