### ISSUE TITLE
How to remove default selection of first date of current month and its background color?

### ISSUE THREAD

**Issue by akashqss** [prolificinteractive/material-calendarview#405]
I want to show calender without default selection of 1st date of current month.Please suggest me.

**Comment by skarempudi** [comment]
No date is selected by default, You can see an example of this in the sample, in Basic Example (BasicActivity). In contrast, Calendar with Decorators (BasicActivityDecorated) explicitly sets the selected date through setCurrentDate().

If I'm misunderstanding you're issue, then please look through the sample app, which demonstrates various ways MaterialCalendarView can be modified.

**Comment by quentin41500** [comment]
Thank you for your answer @skarempudi, the sample app indeed contains lots of cool examples. Do not hesitate to follow up if you still have questions!

**Comment by akshaytaru2007** [comment]
Isn't there any way to achieve this?
