### ISSUE TITLE
Decrease the circle size in setSelectedDate();

### ISSUE THREAD

**Issue by Testinha420** [prolificinteractive/material-calendarview#406]
I can decrease the circle size of the selected day?

![calendar](https://cloud.githubusercontent.com/assets/8333067/18600571/b7255756-7c34-11e6-9422-cc26bd241213.jpg)

**Comment by quentin41500** [comment]
Im not sure you can if you are using the default selector. You can always provide yours: Take a look at the sample app or at the documentation, you should find what you need there!
