### ISSUE TITLE
Bug Selecting Other Date

### ISSUE THREAD

**Issue by bschnack** [prolificinteractive/material-calendarview#408]
Hello,

If there is a MaterialCalendarView that has the setting setAllowClickDaysOutsideCurrentMonth(true) set, and the calendar shows December, if you click a date in January it goes back to November. I have coded up a fix but I do not have push permission to make a PR. Here is my updated MaterialCalendarView.onDateClicked(DayView dayView) code:

    /**
     * Call by {@link CalendarPagerView} to indicate that a day was clicked and we should handle it
     *
     * @param dayView
     */
    protected void onDateClicked(DayView dayView) {
        CalendarDay currentDate = getCurrentDate();
        CalendarDay selectedDate = dayView.getDate();
        final int currentMonth = currentDate.getMonth();
        final int selectedMonth = selectedDate.getMonth();

        if (calendarMode == CalendarMode.MONTHS) {
            if (currentMonth == selectedMonth) {
                onDateClicked(dayView.getDate(), !dayView.isChecked());
            } else if (allowClickDaysOutsideCurrentMonth) {
                if (currentDate.isAfter(selectedDate)) {
                    goToPrevious();
                } else if (currentDate.isBefore(selectedDate)) {
                    goToNext();
                }
                
                onDateClicked(dayView.getDate(), !dayView.isChecked());
            }
        } else {
            onDateClicked(dayView.getDate(), !dayView.isChecked());
        }
    }

It would be great if you could pull this in to fix this issue we are running into.

Thanks,
Brian

**Comment by bschnack** [comment]
Hello,

I figured out how to create a Pull Request so look here now:
https://github.com/prolificinteractive/material-calendarview/pull/409

Cheers,
Brian

**Comment by quentin41500** [comment]
Nice catch, I will be reviewing that as soon as I can. Thank you for your help!

**Comment by quentin41500** [comment]
Fixed in v1.4.2
