### ISSUE TITLE
Show 6 Weeks in a month for CalendarMode.MONTHS

### ISSUE THREAD

**Issue by suherimarpaung** [prolificinteractive/material-calendarview#410]
Can We set  the value of enum Calendar Mode?
Example we want to set 5 weeks.

**Comment by quentin41500** [comment]
Sadly no, the calendar will show 5 weeks only if the `other Dates` `Out of Range` are not displayed

**Comment by suherimarpaung** [comment]
@quentin41500 : but my calendar shows 6 weeks, when i checked Calendar Mode, it defines 6 weeks. I set CalendarMode.MONTHS
` 
   @Experimental
   public enum CalendarMode {

    MONTHS(6),
    WEEKS(1);

    final int visibleWeeksCount;

    CalendarMode(int visibleWeeksCount) {
        this.visibleWeeksCount = visibleWeeksCount;
    }
}
`

![calendar ngaco](https://cloud.githubusercontent.com/assets/16096438/18981377/e93bc68e-8707-11e6-8337-78d5017e8494.PNG)

**Comment by quentin41500** [comment]
Yes, we are setting it to 6 because if set to 5, some month won't show all the days. We are setting the calendar to the maximum of weeks possible to make it exhaustive.

**Comment by suherimarpaung** [comment]
@quentin41500  But can we set to automatically show 5 or 6 if i have the case like my capture above??
