### ISSUE TITLE
Tablet support - Calendar in dialogs

### ISSUE THREAD

**Issue by light365** [prolificinteractive/material-calendarview#416]
In v1.4, the calendar dialog does not show the entire month.

Attached screenshots for reference.

![nexus-10-calendar-library-v1 4 0-landscape](https://cloud.githubusercontent.com/assets/888327/18922756/f1358294-8577-11e6-91ed-af90905376d1.png)
![nexus-10-calendar-library-v1 4 0-portrait](https://cloud.githubusercontent.com/assets/888327/18922758/f148bbb6-8577-11e6-947e-47f6a124b317.png)
![samsung-s7-calendar-library-v1 4 0-portrait](https://cloud.githubusercontent.com/assets/888327/18922757/f143b382-8577-11e6-9b7e-12c68860dbe8.png)

**Comment by StanKocken** [comment]
More generally, the view doesn't fit the space require. If you want to display this calendar into a 300dp box, it will be truncate instead of compressed.
