### ISSUE TITLE
Is ther any way to add more than one dot span for a Date View? 

### ISSUE THREAD

**Issue by avi2108** [prolificinteractive/material-calendarview#418]

**Comment by skarempudi** [comment]
You can add multiple decorators to a MaterialCalendarView, and you can customize the way a decorator look. Look at the sample for reference code.

**Comment by avi2108** [comment]
yeah i can add multiple decerators. I already done that.
But i want multiple dot spans for each date . That's my requirement.
one date may be having one dot span and other date may have 4 dot span which i will add using api response of each date..

**Comment by skarempudi** [comment]
You mean different dates having different numbers of dots? You'd have to create a custom decorator for that, since adding multiple dot decorators would just overlay them onto the same location. You can see examples of custom decorators in the sample project.

**Comment by quentin41500** [comment]
Documentation can be found here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md
