### ISSUE TITLE
Mode Weeks

### ISSUE THREAD

**Issue by juanlabrador** [prolificinteractive/material-calendarview#419]
Any mode to see calendar by weeks?

For example... week 1 to week 52, divided months?

January --> week 1, week 2, week 3, week 4.
February --> week 5, week 6... 

Thanks

**Comment by skarempudi** [comment]
[Use mcv.state().edit().setCalendarDisplayMode(CalendarMode.WEEKS).commit() ](https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION_BUILDER.md), or you can set it in XML with [app:mcv_calendarMode="mode"](https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md). You can see examples of this in the sample.

Unless I'm misunderstanding your question.

**Comment by quentin41500** [comment]
Doc can be found here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION_BUILDER.md#calendar-display-mode
