### ISSUE TITLE
Change selected day background color

### ISSUE THREAD

**Issue by spbisya** [prolificinteractive/material-calendarview#423]
Hi! Your calendar is perfect but how can I change selected item background color and text color? And there is a problem - titles are not showing at all. Why this happens?

**Comment by nzala** [comment]
https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOM_SELECTORS.md#text-color

**Comment by nzala** [comment]
@spbisya https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOM_SELECTORS.md#text-color
