### ISSUE TITLE
OnMonthChanged never called ?

### ISSUE THREAD

**Issue by blitz33** [prolificinteractive/material-calendarview#426]
Hi,

I have a problem with the event OnMonthChanged that seems nerver called when i swipe or i click on the arrows.

I m on the latest release 1.4.0

My CalendarFragmentCode 

`
public class CalendarFragment extends WizardFragment implements OnDateSelectedListener, OnMonthChangedListener {

    protected OnCalendarFragmentNewRequestApiListener mListener;

    private static final DateFormat FORMATTER = SimpleDateFormat.getDateInstance();

    private static String tag;
    private Item mItem;
    private Availability mAvailability;

    private View mProgressView;
    private View mNoDataView;

    MaterialCalendarView calendarView;

    public CalendarFragment() {
        // Required empty public constructor
    }

    public static CalendarFragment newInstance( Item item, String fragmentTag) {
        CalendarFragment fragment = new CalendarFragment();
        tag = fragmentTag;

        // Supply index input as an argument.
        Bundle args = new Bundle();
        if (item != null) {
            Gson gson = new Gson();
            JsonObject jsObj = new JsonObject();
            JsonParser jsonParser = new JsonParser();
            JsonElement jsonElement = jsonParser.parse(gson.toJson(item));
            jsObj.add("data", jsonElement);
            args.putString(JsonHelper.JSON_INTENT_PRODUCT, jsObj.toString());
        }

        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            JsonParser jsonParser = new JsonParser();
            JsonElement element = jsonParser.parse(getArguments().getString(JsonHelper.JSON_INTENT_PRODUCT));
            mItem = JsonHelper.ItemFromJSON(element.getAsJsonObject());

        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_calendar, container, false);
        mProgressView = view.findViewById(R.id.main_progress);
        mNoDataView = view.findViewById(R.id.no_data_access);
        calendarView=(MaterialCalendarView)view.findViewById(R.id.calendarView);
        calendarView.setSelectionColor(getResources().getColor(R.color.soorez_transparent));

        return view;

    }

    @Override
    public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {

    }

    @Override
    public void onMonthChanged(MaterialCalendarView widget, CalendarDay Day) {
        mListener.onCalendarFragmentRequestApi(Day.getDate());
    }

    public Date getDate() {
        return mItem.getDateChoosen();
    }

    //Initialise calendar
    public void setAvailability(Availability availability){
        mAvailability=availability;
        calendarView.setShowOtherDates(MaterialCalendarView.SHOW_DECORATED_DISABLED);

        calendarView.addDecorator(new AllDisableDayDecorator());
        calendarView.addDecorator(new EnableDayDecorator(mAvailability));
        calendarView.state().edit().commit();
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnCalendarFragmentNewRequestApiListener) {
            mListener = (OnCalendarFragmentNewRequestApiListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnCalendarFragmentNewRequestApiListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    private static class EnableDayDecorator implements DayViewDecorator {

        private Availability availability;

        public EnableDayDecorator(Availability availability){
            this.availability=availability;
        }
        @Override
        public boolean shouldDecorate(CalendarDay day) {
            if(availability!=null){
                return availability.isDayAvailable(day);
            }else return false;

        }

        @Override
        public void decorate(DayViewFacade view) {
            view.setDaysDisabled(false);
        }
    }

    private static class AllDisableDayDecorator implements DayViewDecorator {

        @Override
        public boolean shouldDecorate(CalendarDay day) {
           return true;

        }

        @Override
        public void decorate(DayViewFacade view) {
            view.setDaysDisabled(true);
        }
    }

    //NOTIFY ACTIVITY THERE is request with a new starting date
    public interface OnCalendarFragmentNewRequestApiListener {
        void onCalendarFragmentRequestApi(Date firstDateOfMonth);
    }

}`

**Comment by blitz33** [comment]
The same for onDateSelected, it seems it's not a bug, but i don't know why i didn't receive events fired by the calendar view.

**Comment by quentin41500** [comment]
@blitz33 Seems like you didn't set the listener to the calendar `calendarView.setOnMonthChangedListener(this)`. Same thing for date

**Comment by blitz33** [comment]
OMG that mistake ! Thanks for this amazing widget, it save lot of time.
