### ISSUE TITLE
日历在dialog-frament中显示不全

### ISSUE THREAD

**Issue by tbygg** [prolificinteractive/material-calendarview#428]
`importandroid.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v4.app.DialogFragment;
import android.support.v7.app.AlertDialog;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.View;
import android.view.Window;
import com.benqio.mobility.R;
import com.prolificinteractive.materialcalendarview.CalendarDay;
import com.prolificinteractive.materialcalendarview.MaterialCalendarView;
import com.prolificinteractive.materialcalendarview.OnDateSelectedListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
public  class SimpleCalendarDialogFragment extends DialogFragment implements OnDateSelectedListener{
    private static final DateFormat FORMATTER = SimpleDateFormat.getDateInstance();

```
MaterialCalendarView widget;

@Override
public void onAttach(Context context) {
    if(!(getActivity() instanceof DateCallback)){
        throw new RuntimeException("使用SimpleCalendarDialogFragemt的activity必须实现DateCallback接口");
    }
    super.onAttach(context);
}
```

//    @Override
//    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
//        getDialog().requestWindowFeature(Window.FEATURE_NO_TITLE);
//        return inflater.inflate(R.layout.dialog_basic, container, false);
//    }

//    @Override
//    public void onViewCreated(View view, Bundle savedInstanceState) {
//        super.onViewCreated(view, savedInstanceState);
//        String currentDay = (String) getArguments().get("currentDay");
//        KLog.d("currentDay:" + currentDay);
//        widget = (MaterialCalendarView) view.findViewById(R.id.calendarView);
//
//        widget.setOnDateChangedListener(this);
//    }

```
@Override
public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {

}

@NonNull
@Override
public Dialog onCreateDialog(Bundle savedInstanceState) {

     int  year  = (int) getArguments().get("year");
     int  month = (int)getArguments().get("month");
     int  day   = (int)getArguments().get("day");


    AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
    LayoutInflater inflater = getActivity().getLayoutInflater();

    View view = inflater.inflate(R.layout.dialog_basic,null);
    widget = (MaterialCalendarView) view.findViewById(R.id.calendarView);
    CalendarDay cd = CalendarDay.from(year,month,day);
    widget.setSelectedDate(cd);
    widget.setOnDateChangedListener(this);
    builder.setView(view)
            .setPositiveButton("确定", new DialogInterface.OnClickListener() {
                @Override
                public void onClick(DialogInterface dialogInterface, int i) {
                    DateCallback dateCallback = (DateCallback) getActivity();
                      CalendarDay  calendarDay = widget.getSelectedDate();
                      dateCallback.getData(calendarDay.getYear(),calendarDay.getMonth(),calendarDay.getDay());

                }
            })
            .setNegativeButton("取消",null)
            .setCancelable(false);
    Dialog dialog = builder.create();
    dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
    dialog.setCanceledOnTouchOutside(false);
    dialog.setOnKeyListener(new DialogInterface.OnKeyListener() {
        @Override
        public boolean onKey(DialogInterface dialogInterface, int keyCode, KeyEvent keyEvent) {
            if(keyCode == KeyEvent.KEYCODE_BACK){
                return true;
            }
            return false;
        }
    });
    return dialog;

}



public interface DateCallback{
    public void getData(int year,int month,int day);
}
```

}`

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:tools="http://schemas.android.com/tools"
              android:orientation="vertical"
              android:layout_width="200dp"
              android:layout_height="200dp"
              tools:context=".mvp.ui.activities.PlaybackActivity"
              xmlns:app="http://schemas.android.com/apk/res-auto"

>   <com.prolificinteractive.materialcalendarview.MaterialCalendarView
>         android:id="@+id/calendarView"
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"

```
    />
```

</LinearLayout>`

**Comment by quentin41500** [comment]
What is your issue ?
