### ISSUE TITLE
Title does not show 

### ISSUE THREAD

**Issue by shinayser** [prolificinteractive/material-calendarview#43]
When o give small height to the calendar it does not show the title. Happens even inside a scroll view.

**Comment by dandc87** [comment]
Try using wrap content for the width and height of the calendar, and place that in a scrollview. If you want the overall calendar smaller, you can use `setTileSize()` or `app:mcv_tileSize="custom_size"`.

**Comment by shinayser** [comment]
Hey, the wrap_content in width and height didn't worked. But i used your ideia using app:mcv_tileSize and created different sizes varying with screen size and i think it will be good. Thankyou so much for you help.

**Comment by dandc87** [comment]
Glad I something to help. The cropping issue is now going to be discussed and tracked in #44
