### ISSUE TITLE
is possible to add multiple view into one day cell.

### ISSUE THREAD

**Issue by sasowang** [prolificinteractive/material-calendarview#437]
Thanks for this fantastic library. if I'd like to add some textview/image view into one day cell. is it possible to achieve this requirement?

**Comment by quentin41500** [comment]
You can accomplish this using decorators. Documentation is here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md

**Comment by SuperXFan** [comment]
how to add Multiple decorators in one day

**Comment by quentin41500** [comment]
By adding the day to multiple decorators.
