### ISSUE TITLE
How to hide the days out of current month?

### ISSUE THREAD

**Issue by XinYiWorld** [prolificinteractive/material-calendarview#438]
it happended in he latest compile url   "  compile 'com.prolificinteractive:material-calendarview:1.4.2'   "

**Comment by XinYiWorld** [comment]
`

`
when i add code before,there is no day show

**Comment by quentin41500** [comment]
I think you are missing the code you want to show for your issue

**Comment by quentin41500** [comment]
Please reopen with more information. Check sample of examples
