### ISSUE TITLE
The results of month+1(EventDecorator)

### ISSUE THREAD

**Issue by Jieth** [prolificinteractive/material-calendarview#439]
hello;
CalendarDay day = CalendarDay.from(2016,9,16);
The results of month+1
![2g6up 1b 0 j 0yhxd3kl](https://cloud.githubusercontent.com/assets/10277344/19342575/eb66db26-9164-11e6-81ac-d4e340d9b2b0.png)

**Comment by magneticflux-** [comment]
Could you explain what you expected compared to what is shown in the image?

**Comment by Jieth** [comment]
And Settings in consistent

**Comment by magneticflux-** [comment]
I believe that the date is provided in Year-Month-Day form, which is consistent with the image.

**Comment by Jieth** [comment]
please,Is my way of use have mistakes?
![xlky a 1 s 1v iizb1og](https://cloud.githubusercontent.com/assets/10277344/19406919/2446cbb8-92c3-11e6-8f1e-71d8a65ed534.png)

**Comment by magneticflux-** [comment]
That looks correct. If you're adding the decorator asynchronously, you may need to introduce some sort of synchronization, or run the `.addDecorator(...` method on the main thread. I do not know if that is needed in this instance however.

**Comment by Jieth** [comment]
ok,thanks

**Comment by GavinSong91** [comment]
I met the same problem as you.Have you found a solution

**Comment by magneticflux-** [comment]
@GavinSong91 Check the documentation for the `CalendarDay.from` method. It may be using zero-indexed months (where January is month 0, etc.).
