### ISSUE TITLE
[Suggestion] Remove rows of weeks prior to the minDate

### ISSUE THREAD

**Issue by henriquedesousa** [prolificinteractive/material-calendarview#445]
Howdy. I'm currently creating a fragment containing a MaterialCalendarView, but I'd like to know if it's possible (and how!) to hide the full rows containing weeks prior to the minDate. 

My minDate is always the day tomorrow, and as seen in the following screenshot, we almost everything occupied by inactive days (you can see that the first selectable day is 21).

Thank you in advance.

![screen shot 2016-10-18 at 15 32 40](https://cloud.githubusercontent.com/assets/12630569/19482301/97eeb85a-9548-11e6-875f-2fd7fcf904b1.png)

**Comment by quentin41500** [comment]
You can't do that currently. You can change the height of the Calendar if that helps getting a bit more space for your view.

**Comment by quentin41500** [comment]
You should use weekview instead to display more accurate results. You can always use monthview if the date is less than 15 for example. Closing
