### ISSUE TITLE
Bug with calendar Days

### ISSUE THREAD

**Issue by darko1002001** [prolificinteractive/material-calendarview#447]
This is for some reason happening to me just on a specific device,
Genymotion simulator Samsung Galaxy S6, running API 23 Android 6.0.0.

Any pointers to where i can investigate and what can cause this issue?

![screen shot 2016-10-20 at 09 56 54](https://cloud.githubusercontent.com/assets/599343/19551541/ed0c48c0-96ab-11e6-9cf8-86b1ffd200ae.png)

I have the identical code running in the sample project and it seems ok.

What i've learned so far.
If i uninstall and reinstall my app the calendar works properly, when i run it again this always happens.
If i kill the app, it still happens when i run it, not just when normally exiting it.
When on click on the actual date, lets say the 30th it logs correctly as the 1st of the month being clicked, basically all the displayed dates are moved by 1 day.

**Comment by hilfritz** [comment]
Happened to me before when the device timezone was changed. It got fixed everytime kill then restart the app. I think it is a bug.

**Comment by quentin41500** [comment]
We fixed the timezone issue https://github.com/prolificinteractive/material-calendarview/pull/622

**Comment by quentin41500** [comment]
Reopening this issue as it hasn't been fixed yet.
