### ISSUE TITLE
Hi, Iam using prolificinteractive-material-calendarview in my app.  Need to make the SUNDAY AND SATURDAY in red color .Please post a solution as soon as possible.Thanks in advance

### ISSUE THREAD

**Issue by Ashtapathy** [prolificinteractive/material-calendarview#449]

**Comment by nzala** [comment]
/**
 * Highlight Saturdays and Sundays with a background
 */
public class HighlightWeekendsDecorator implements DayViewDecorator {

    private final Calendar calendar = Calendar.getInstance();
    private final Drawable highlightDrawable;
    private static final int color = Color.parseColor("#228BC34A");

    public HighlightWeekendsDecorator() {
        highlightDrawable = new ColorDrawable(color);
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        day.copyTo(calendar);
        int weekDay = calendar.get(Calendar.DAY_OF_WEEK);
        return weekDay == Calendar.SATURDAY || weekDay == Calendar.SUNDAY;
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.setBackgroundDrawable(highlightDrawable);
    }
}

**Comment by quentin41500** [comment]
Use decorators, check the sample app for more
