### ISSUE TITLE
Have you tried to put the view in a scroll view ?

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#45]
I can not move scroll view when touched calendar view
Have you tried to put the view in a scroll view ?

**Comment by dandc87** [comment]
The "Dynamic Setters Test" in the sample has the calendar inside of a ScrollView. I've also tried having the calendar as the child of the ScrollView. Both work for me. What device and what version of Android are you using? Can you provide code so I can try and replicate your issue?

**Comment by kamilwlf** [comment]
the error was in Add header(your calendar) to a RecyclerView, I changed rv to listview and already works
