### ISSUE TITLE
CalendarView IS NOT DISPLAYED with Android 7 (SDK 24)

### ISSUE THREAD

**Issue by Aissa-H** [prolificinteractive/material-calendarview#451]
Hi everyone,

I'm currently developping an app in which this great lib is used. The view works correctly on most of SDKs but I test today with the new version of Android (Nougat - 7 - SKD 24) and I can't see many things of the view : day numbers are not displayed at all and decorators are disturbed especially.

Im using the version 1.4.2.

Waiting for your responses,

Thank you for this lib!

**Comment by denisko21** [comment]
Hi. I tested it with API 24 emulator two day ago and all works great. Did you try to change styles?

**Comment by bskim45** [comment]
Works well here too on Nexus 5X with 7.1.1. Is there any style customization?

**Comment by Aissa-H** [comment]
Yes it is, I have some decorators on the calendar

**Comment by bskim45** [comment]
Is the problem persists after those decorators removed?

**Comment by Aissa-H** [comment]
I tested by removing some decorators, the one which cause the issue is the follow one:

`class SelectionDecorator implements DayViewDecorator {

        @Override
        public boolean shouldDecorate(CalendarDay day) {
            return !UtilsCalendar.isSameDay(day.getCalendar(), Calendar.getInstance());
        }

        @Override
        public void decorate(DayViewFacade view) {
            try {
                Drawable drawable = ContextCompat.getDrawable(getContext(), R.drawable.selected_day_selector);
            /*Here, in order to have a circle selector, you have to take the tile width/height and reduce from it in order to obtain an equal value for both.
             For example, if you want to make a circle selector which has a scale of 30x30 dps where the tile width is 50dp and the tile height is 40dp, you
             are going to retire 20dp for the width (so 10dp from left and 10dp from right) and 10dp for the height(so 5dp from bottom and 5dp from top).
              */
                int horizontalMargin = (int) UtilsMeasure.pxFromDp((tileWidth - 30) / 2);
                int top = (int) UtilsMeasure.pxFromDp(2);
                int bottom = (int) UtilsMeasure.pxFromDp(8);

                InsetDrawable insetDrawable = new InsetDrawable(drawable, horizontalMargin, top, horizontalMargin, bottom);
                view.setSelectionDrawable(insetDrawable);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }`

**Comment by ajithkpistar** [comment]
IN My case Calendar is not displaying fully its dispalying half only

**Comment by mays123** [comment]
i have the same problem. Your help is appreciated
