### ISSUE TITLE
getCurrentDate() always returns the first day and not the date set with setCurrentDate()?

### ISSUE THREAD

**Issue by Bevor** [prolificinteractive/material-calendarview#453]
I want to set the current date, let's say to 2016-09-22, with `setCurrentDate()`. When I want to return the current date, I don't get what I set, but the first day of the month of the current date, 2016-09-01. What is the purpose of this behavior?

**Comment by ivanove** [comment]
did you found a solution ?

**Comment by Bevor** [comment]
It's just a workaround, but it works for my needs. I just set the color to transparent after month scrolling:

```
calendarView.setListener(new CompactCalendarView.CompactCalendarViewListener()
{
    @Override
    public void onMonthScroll(Date firstDayOfNewMonth)
    {
        calendarView.setCurrentSelectedDayBackgroundColor(ContextCompat.getColor(getActivity(), R.color.transparent));
    }
});
```

**Comment by ivanove** [comment]
Thank's
