### ISSUE TITLE
try to use this view to show only one month data 

### ISSUE THREAD

**Issue by eaglewangl** [prolificinteractive/material-calendarview#460]
In my project , i need to use this view to show a year data , can i do something to let the viewpager doesn't work ? or just don 't use viewpager?

**Comment by denisko21** [comment]
Why you couldn't use the SimpleDateFormat?

**Comment by eaglewangl** [comment]
i'm sorry , maybe i don't show my question clearly, i find the view we used is alaways contains in viewpager , but i want to use recyclerview to contains that , but it takes a few seconds to load , so i want to find a solution .
thks.

**Comment by denisko21** [comment]
If you have calendar in each ViewHolder, i think that few seconds it's good. When onMeasure tries to calculate size of block, your device has a huge performance problems.

**Comment by eaglewangl** [comment]
yep , so i try to custom a view that suitable my projece , and learn more from this.
finally thanks a lot.
