### ISSUE TITLE
How can i display Week number

### ISSUE THREAD

**Issue by nAkhmedov** [prolificinteractive/material-calendarview#464]
I want to implement to display week number on top of date number or lefts side of calendar.
First approach(display on top of number): - i couldn`t give various style to week number and date number.Both of them has the same last style
![1111](https://cloud.githubusercontent.com/assets/8067423/20137725/ff2d59ac-a69d-11e6-9cfe-409ad27cc343.jpg)

Second approach - dont have any idea yet

http://sanziro.com/wp-content/uploads/2015/07/display-week-number-in-calendar-app-for-ios.png

**Comment by nAkhmedov** [comment]
![add-week-number](https://cloud.githubusercontent.com/assets/8067423/20167902/719e2b86-a740-11e6-9d4a-638abf7d67dd.jpg)

**Comment by nAkhmedov** [comment]
I need such kinda feature, it displays week number on each week line

**Comment by nAkhmedov** [comment]
@quentin41500  Could you help me to implement week day feature

**Comment by nAkhmedov** [comment]
`public class WeekDayDecorator implements DayViewDecorator {

    private int weekNumber = 1;

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        if (day.getCalendar().get(Calendar.DAY_OF_WEEK) == Calendar.MONDAY) {
            this.weekNumber = day.getCalendar().get(Calendar.WEEK_OF_YEAR);
            return true;
        }
        
        return false;
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.addSpan(new WeekDaySpan(weekNumber));
    }
}`

`calendarView.addDecorators(new WeekDayDecorator());`

**Comment by nAkhmedov** [comment]
It displays 
![device-2017-01-14-020518](https://cloud.githubusercontent.com/assets/8067423/21945603/fc443010-d9fd-11e6-9061-ce4b82b9aa82.png)

**Comment by nAkhmedov** [comment]
How to dynamically change weekNumber? I have seen https://github.com/prolificinteractive/material-calendarview/issues/270

**Comment by eimori** [comment]
@nAkhmedov 
Hi, can I know how your WeekDayDecorator () is written?
I also want to make the same effect, but not familiar with the span, refer to the example or can not successfully write
Hope to get your help, thanks!

**Comment by nAkhmedov** [comment]
@eimori I will send you the solution later, don't worry.

**Comment by eimori** [comment]
@nAkhmedov Thank you very much!!

**Comment by eimori** [comment]
@nAkhmedov 
May I ask when can I get a solution? This function is urgent for me

**Comment by nAkhmedov** [comment]
`calendarView.setOnMonthChangedListener(new OnMonthChangedListener() {
    @Override
    public void onMonthChanged(MaterialCalendarView widget, CalendarDay date) {
        currentMonthDate = date.getDate();
        displayWeekNumbers(currentMonthDate); 
   }
});

private void displayWeekNumbers(final Date currentMonthDate) {
    if (weekTask != null) {
        weekTask.stopAsyncTask();
    }
    weekTask = new WeekTask(MainActivity.this, currentMonthDate);
}

public void setWeeks(ArrayList<Date> newWeekDatas) {
    if (newWeekDatas != null) {

        weekDatas.clear();
        weekDatas.addAll(newWeekDatas);

        if (weekDayDecorator == null) {
            weekDayDecorator = new WeekDayDecorator(weekDatas);
            calendarView.addDecorators(weekDayDecorator);
        } else {
            calendarView.postDelayed(new Runnable() {
                @Override
                public void run() {
                    calendarView.addDecorators(weekDayDecorator);
                }
            }, 1200);
        }
    }
}

`
`public static ArrayList<Date> getWeekNumberList(Date currentMonthDate) {
    ArrayList<Date> dates = new ArrayList<>(5);
    Calendar startCalendar = Calendar.getInstance();
    startCalendar.setTime(currentMonthDate);
    startCalendar.set(Calendar.DAY_OF_MONTH,
            startCalendar.getActualMinimum(Calendar.DAY_OF_MONTH));
    Calendar endCalendar = Calendar.getInstance();
    endCalendar.setTime(currentMonthDate);
    endCalendar.set(Calendar.DAY_OF_MONTH,
            endCalendar.getActualMaximum(Calendar.DAY_OF_MONTH));

    long endTime = endCalendar.getTimeInMillis();
    while (startCalendar.getTimeInMillis() <= endTime) {
        if (startCalendar.get(Calendar.DAY_OF_WEEK) == Calendar.MONDAY) {
            dates.add(startCalendar.getTime());
            startCalendar.add(Calendar.WEEK_OF_MONTH, 1);
        } else {
            startCalendar.add(Calendar.DAY_OF_MONTH, 1);
        }
    }

    return dates;
}
`

`/**
 * Created by navruz on 1/13/17.
 */

public class WeekDayDecorator implements DayViewDecorator {

    private List<Date> weekNumberList;
    private Calendar calendar = Calendar.getInstance();
    private WeekDaySpan weekDaySpan;

    public WeekDayDecorator(List<Date> weekNumberList) {
        this.weekNumberList = weekNumberList;
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {

//        return date != null && day.equals(CalendarDay.from(date));

        int sizeweekNumbers = weekNumberList.size();
        Date minDate = weekNumberList.get(0);
        Date maxDate = weekNumberList.get(sizeweekNumbers - 1);
        if (day.isInRange(CalendarDay.from(minDate), CalendarDay.from(maxDate))) {
            for (int i=0;i<sizeweekNumbers;i++) {
                Calendar dayCalendar = Calendar.getInstance();
                dayCalendar.setTime(day.getDate());
                Calendar weekCalendar = Calendar.getInstance();
                weekCalendar.setTime(weekNumberList.get(i));
                if (dayCalendar.getTimeInMillis() == weekCalendar.getTimeInMillis()) {
                    return true;
                }
            }
        }
        return false;
    }

    @Override
    public void decorate(DayViewFacade view) {
        if (weekDaySpan == null) {
            weekDaySpan = new WeekDaySpan(weekNumberList);
        }
        view.addSpan(weekDaySpan);
    }
}
`

`/**
 * Created with Android Studio
 * User: navruz
 * Date: 1/22/17
 * Time: 10:29 AM
 * To change this template use File | Settings | File Templates
 */

public class WeekTask {

    private final MainActivity activity;
    private AsyncTask<Date, Void, ArrayList<Date>> getMonthList;

    public WeekTask(MainActivity mainActivity, Date currentMonthDate) {
        this.activity = mainActivity;
        getMonthList = new GetMonthList().execute(currentMonthDate);

    }

    private class GetMonthList extends AsyncTask<Date, Void, ArrayList<Date>> {
        @Override
        protected ArrayList<Date> doInBackground(Date... params) {
            return AndroidUtil.getWeekNumberList(params[0]);
        }

        @Override
        protected void onPostExecute(ArrayList<Date> dates) {
            super.onPostExecute(dates);
            activity.setWeeks(dates);
        }
    }

    public void stopAsyncTask() {
        if (getMonthList != null && !getMonthList.isCancelled())
            System.out.println("Task cancelled!!!!");
            getMonthList.cancel(true);
    }
}
`

You need to optimize WeekDayDecorator's class shouldDecorate method.

**Comment by nAkhmedov** [comment]
@eimori sorry for late

**Comment by eimori** [comment]
@nAkhmedov Thank you for your help,
but these code does not see WeekDaySpan()?
Is it possible to provide it together?

**Comment by nAkhmedov** [comment]
`package com.calendaruspro.util;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Rect;
import android.support.v4.content.ContextCompat;
import android.text.style.LineBackgroundSpan;

import com.calendaruspro.ApplicationLoader;
import com.calendaruspro.R;

import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 * Created by navruz on 1/13/17.
 */

class WeekDaySpan implements LineBackgroundSpan {

    private final List<Date> weekNumberList;
    private Calendar calendar = Calendar.getInstance();

    WeekDaySpan(List<Date> weekNumberList) {
        this.weekNumberList = weekNumberList;
    }

    @Override
    public void drawBackground(Canvas canvas, Paint paint2, int left, int right, int top,
                               int baseline, int bottom, CharSequence text, int start, int end, int lnum) {

        for (Date weekDate : weekNumberList) {
            if (Integer.parseInt(text.toString()) == weekDate.getDate()) {
                calendar.setTime(weekDate);

                Rect textBounds = new Rect();
                Paint paint = new Paint();
                text = calendar.get(Calendar.WEEK_OF_YEAR) +"";
                paint.setColor(ContextCompat.getColor(ApplicationLoader.getAppContext(), R.color.yellow_text));
                paint.getTextBounds(text.toString(), 0, text.length(), textBounds);
                paint.setTextSize(30);
                canvas.drawText(text.toString(), (left + right) / 2 - 10, textBounds.height() - textBounds.bottom, paint);
                break;
            }
        }
    }
}`

**Comment by nAkhmedov** [comment]
@eimori working?

**Comment by eimori** [comment]
@nAkhmedov Yes! It's working!
I have just finished my job! Thank you~
![device-2017-08-03-155436](https://user-images.githubusercontent.com/9261507/28914003-a1221cca-786c-11e7-8953-da7be11442a5.png)

**Comment by nAkhmedov** [comment]
you are welcome!

**Comment by SugamPradhan** [comment]
Hello nAkhmedov
I have names for events in json.
I want to add it to calendar on respective dates..
i have used decorator to color them with different color codes as in json data
i need to add Text (Event title) to the events dates
How text can be added to calendar??
