### ISSUE TITLE
how to add Multiple decorators in one day and Lunar calendar

### ISSUE THREAD

**Issue by SuperXFan** [prolificinteractive/material-calendarview#465]
how to add Multiple decorators in one day；

how to add Lunar calendar text info；

**Comment by androchentw** [comment]
decorators could be multiply added, just like [sample/BasicActivityDecorated.java] provides a demo 

[sample/BasicActivityDecorated.java]: https://github.com/prolificinteractive/material-calendarview/blob/1a89e3ff86bbf35e2f1a4bfbb773167f7d442308/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/BasicActivityDecorated.java#L106

**Comment by josephWang72** [comment]
Hi, according to sample/BasicActivityDecorated.java. Adding multiple decorators in a single dayView, the outcome is all decorators overlap each other.  No matter how many decorator I add, it looks like only one decorator for the date. Do you have any suggestions?
