### ISSUE TITLE
How to show indicator in particular day

### ISSUE THREAD

**Issue by ishwarverma39** [prolificinteractive/material-calendarview#472]
I want to show some dot indicator of events for particular day

**Comment by androchentw** [comment]
[sample/BasicActivityDecorated.java] provides a demo 

[sample/BasicActivityDecorated.java]: https://github.com/prolificinteractive/material-calendarview/blob/1a89e3ff86bbf35e2f1a4bfbb773167f7d442308/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/BasicActivityDecorated.javaL106

**Comment by ishwarverma39** [comment]
Thanks..

**Comment by ishwarverma39** [comment]
I have another issue, in week view, it not showing selected date, it shows either next week or previous weeks, random behaviours in different devices. I have tried to setCurrentDate passing selected date. Its happening when I switch from **month** view to **week** View.

**Comment by AvaniGJ** [comment]
how to solve the timezone issue in week View

**Comment by quentin41500** [comment]
There is timezone tickets open. make sure to check those.
