### ISSUE TITLE
Decorated CalendarDay is always set to clickable

### ISSUE THREAD

**Issue by androchentw** [prolificinteractive/material-calendarview#475]
I have 2 decorators: `DisableAllDecorator` and `EnlightenBeforeDecorator`

```java
public class DisableAllDecorator implements DayViewDecorator {

  @Override public boolean shouldDecorate(CalendarDay day) {
    return true;
  }

  @Override public void decorate(DayViewFacade view) {
    view.setDaysDisabled(true);
  }
}
```

```java
public class EnlightenBeforeDecorator implements DayViewDecorator {

  @Override public boolean shouldDecorate(CalendarDay day) {
    return day.isBefore(CalendarDay.today());
  }

  @Override public void decorate(DayViewFacade view) {
    view.addSpan(new ForegroundColorSpan(Color.WHITE));
  }
}
```

I found that if I disable > enlighten, the days before would always be clickable 

```
addDecorators(new DisableAllDecorator(),
        new EnlightenBeforeDecorator());
```

while the reverse one won't

```
addDecorators(new EnlightenBeforeDecorator(),
        new DisableAllDecorator());
```

Is this a designed behavior? If yes, why?

Or, is there smarter way to achieve the same effect? (making days before not clickable, but the style is slightly different from disabled days)
selectionMode is not an option, since I've used selected day for another style.

Thanks!

**Comment by quentin41500** [comment]
Decorators are applied in the order they are added, meaning if the last decorator disable days, then they will be disabled.
