### ISSUE TITLE
Even with tileWidth and tileHeight set to match_parent, day views are square

### ISSUE THREAD

**Issue by lordcodes** [prolificinteractive/material-calendarview#479]
Almost all of the same calendars in the sample app don't display properly in landscape.
I have found that in our app, this can be fixed by using the newly added `match_parent` for the `tileWidth` and `tileHeight`.

However, on our calendar we have added decorators to change the background colours of specific days on the calendar.

The problem is that the DayView onLayout code means that the day views are actually still squares, even if they appear wider than they are tall. This means the decorator background is a little square around the text.

I found by changing DayView onLayout code to be the following fixed the issue:

```java
    private void calculateBounds(int width, int height) {
        tempRect.set(0, 0, width, height);
    }
```

However, I wasn't sure why the previous (much more complicated code) in calculateBounds was required. I am happy to submit a PR, as currently this is causing real problems with our design. Either we remove the decorators and achieve the affect another way, or we will have to do something else for landscape, as the calendar looks quite bad in landscape when it is completely square.

**Comment by nicbell** [comment]
I have found this same problem, did you ever submit a PR?

**Comment by lordcodes** [comment]
@nicbell Sorry, I reported this nearly 2 years ago and was waiting to hear back before spending time working on it. Therefore, no I never looked into it. Our project moved on and so didn't have as pressing a need to fix it anymore.

Nice to see your PR 👍
