### ISSUE TITLE
Range of the month view

### ISSUE THREAD

**Issue by ChrisProlls** [prolificinteractive/material-calendarview#483]
Hi everyone !
Due to performance issue, I need to query my database only events that are displayed by the calendar. Is there a simple way to get the date range that is display by the calendar current's view ? 
Thanks !

**Comment by martijndebruijn** [comment]
Good question. I'm also searching for the answer.

**Comment by quentin41500** [comment]
You can add month listener, then query your database by passing the first day of that month and the last day. The implementation can be different for everyone based on your api structure and is out of scope for this library. Closing.
