### ISSUE TITLE
crash using mcv_firstDayOfWeek with a @string resource

### ISSUE THREAD

**Issue by rubinovk** [prolificinteractive/material-calendarview#484]
Customization in xml:   `app:mcv_firstDayOfWeek="monday"` works well, however a similar customization with the use of a `@string` resource crashes the activity containing the calendar. Example: `app:mcv_firstDayOfWeek="@string/monday"`

The activity crashes with:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{in.futurezoom/in.futurezoom.timeit.MainActivity}: android.view.InflateException: Binary XML file line #148: Error inflating class <unknown>` 

The following line concerning Calendar is in the stacktrace:
`Caused by: java.lang.NullPointerException at com.prolificinteractive.materialcalendarview.MaterialCalendarView.<init>(MaterialCalendarView.java:387)'`

Hope this is enough to track down the issue.
Thanks!

**Comment by quentin41500** [comment]
app:mcv_firstDayOfWeek is based on a custom attribute that does not take a string as valid param. 
Here are the valid params:
```
        <attr name="mcv_firstDayOfWeek" format="enum">
            <enum name="sunday" value="1" />
            <enum name="monday" value="2" />
            <enum name="tuesday" value="3" />
            <enum name="wednesday" value="4" />
            <enum name="thursday" value="5" />
            <enum name="friday" value="6" />
            <enum name="saturday" value="7" />
        </attr>
```
