### ISSUE TITLE
Does it support rtl locales?

### ISSUE THREAD

**Issue by orium-dev** [prolificinteractive/material-calendarview#485]
I need a calendar with day order from right to left for arabic locales.

**Comment by waqqas-abdulkareem** [comment]
+1

**Comment by pelegs1** [comment]
Same here with a hebrew application. It'd be nice to see support for RTL scrolling and day placement.
Thanks!

**Comment by quentin41500** [comment]
Better RTL support should be coming in the next release, stay tuned
