### ISSUE TITLE
Is there an 'weekview' in this library?

### ISSUE THREAD

**Issue by timkoers** [prolificinteractive/material-calendarview#49]
Right now I'm using the Android Week View library to show things in the calendar. That library isn't optimized very well, and it's lagging on my device. 
Does this library contain an 'mode' to only show one week (or x number of days) at a time? 

If yes, I'll try to implement this library into my project.

Thanks!
Tim

**Comment by dandc87** [comment]
This library only displays month views, and I don't see other 'modes' being implemented. The goal is to be a mix of the platform CalendarView and the new Material date pickers, all backported to Android 4.0. I'm sorry we can't help you.
