### ISSUE TITLE
 Calendar.getSelectedDates() list sort problem

### ISSUE THREAD

**Issue by hilfritz** [prolificinteractive/material-calendarview#491]
In the multiple/range selection, I noticed that when I select Dec 1, 2016 as start and Dec 22, 2016 as end in the calendar the List<CalendarDays> retrieved from 
_calendar.getSelected()_ dates are not in order. 

The list item object in index 0 is Dec 1, 2016.
The list item object in index 1 is Dec 22, 2016.
The list item object in index 2 is Dec 2, 2016 and the list continues as incremental dates.

How do you sort the returned list?

**Comment by hilfritz** [comment]
I ended up manually sorting the list by using **java.util.Collections**.
```java
Collections.sort(getCalendarDayListTemp(), new Comparator<CalendarDay>() {
            @Override
            public int compare(CalendarDay calendarDay, CalendarDay t1) {
                DateTime left = new DateTime(calendarDay.getCalendar());
                DateTime right = new DateTime(t1.getCalendar());
                return left.compareTo(right);
            }
        });
```

**Comment by krazykira** [comment]
i am also facing this problem
