### ISSUE TITLE
Customize Week Day views

### ISSUE THREAD

**Issue by allemattio** [prolificinteractive/material-calendarview#493]
It's possible to configure the WeekDays views dimensions and colors?
I've seen that it's possible to configure the TextAppearance but not other parameters like size and colors.
It would be useful to configure more values or the option to set a decorator also for WeekDaysViews, or at least to hide them and create a custom view.

**Comment by kamalsint** [comment]
You can create a custom theme and set it through the xml if you want to change the text appearance.
Like this  app:mcv_weekDayTextAppearance="@style/TextAppearance.WeekDay".

 <style name="TextAppearance.WeekDay" parent="android:TextAppearance.DeviceDefault.Small">
        <item name="android:textSize">14sp</item>
        <item name="android:textColor">#000000</item>
        <item name="android:textAllCaps">true</item>
    </style>


This works absolutely great. But one issue which I am still on searching is about how to set the background color for the Week Day View.

Hope the solution is useful to you.
Thanks.

**Comment by sixscorpions** [comment]
We are not able to change the background of the WeekDayTextAppearance.

**Comment by kamalsint** [comment]
@sixscorpions : If you are including this library using the gradle then you cannot change the background of week day text. So the workaround is include this library as a module in your project, that way I was able to change the background.

Hope the solution works for you as it did for me.

Thanks.

**Comment by quentin41500** [comment]
You could use decorators if it's for specific days. If the idea is to have all the cells with a specific color, you could have a background color on the MCV using `android:background="@color/my_color"`
