### ISSUE TITLE
Disable some date

### ISSUE THREAD

**Issue by hounsokhorn** [prolificinteractive/material-calendarview#494]
Hello, 
Greatly thank for provide the awesome calendar for every android developer. However, I have some issue to ask you. I want to disable some date in the calendar like we have the list of the holiday which needs to disable it. 
Days to disable.

> <days_off>
<day_off>2016-12-24</day_off>
<day_off>2016-12-25</day_off>
<day_off>2016-12-31</day_off>
<day_off>2017-01-01</day_off>
<day_off>2017-01-07</day_off>
<day_off>2017-01-08</day_off>
<day_off>2017-01-14</day_off>
<day_off>2017-01-15</day_off>
<day_off>2017-01-21</day_off>
<day_off>2017-01-22</day_off>
<day_off>2017-01-28</day_off>
<day_off>2017-01-29</day_off>
<day_off>2017-02-04</day_off>
<day_off>2017-02-05</day_off>
<day_off>2017-02-11</day_off>
<day_off>2017-02-12</day_off>
<day_off>2017-02-18</day_off>
<day_off>2017-02-19</day_off>
</days_off>

Would you show me how to do?

***note: disable date does not refer to min & max date.

thanks,

**Comment by roeiros** [comment]
@hounsokhorn Did you manage to find a solution?

**Comment by quentin41500** [comment]
The sample as examples for this, as well as the wiki. Please check there for more information before posting an issue, thank you.
