### ISSUE TITLE
How to go to selected date page?

### ISSUE THREAD

**Issue by akak19193** [prolificinteractive/material-calendarview#495]
Hi, this is a wonderful library with many good features. Still, I have one question. Say if one selected date is not in current week row or month page, is there any method to automatically move back or forth to go there? Thanks!

**Comment by Joisar** [comment]
I'm looking for the same. It will be great if we can navigate programmatically somehow.

**Comment by nomanbiniqbal** [comment]
+1

**Comment by nomanbiniqbal** [comment]
Its simple 👍 
just use
`
  calendarView.setCurrentDate(Calendar.getInstance());
        calendarView.setSelectedDate(Calendar.getInstance());
`

**Comment by akak19193** [comment]
setCurrentDate works! Thank you!
