### ISSUE TITLE
Dynamic height not working properly

### ISSUE THREAD

**Issue by ArthurNagy** [prolificinteractive/material-calendarview#498]
In month mode, if I set the first day of the week to Calendar.MONDAY(but I think that is irrelevant in some months) and enable the dynamic height, there are times, when a row is cut off, and some dates are missing:

without dynamic height:
https://goo.gl/IHml5I

dynamic height enabled:
https://goo.gl/ZzIUu4

this happens for a lot of months(just in 2017: january, april, july, september, october, december)

**Comment by AndrazP** [comment]
I noticed this issue is only present on Nougat devices.

**Comment by ArthurNagy** [comment]
@AndrazP so you managed to reproduce it also? The only thing I don't understand is that in the sample project if I enable dynamicHeight it works correctly. Can't figure out what causes this issue

**Comment by ReckeDJ** [comment]
I also experience this issue. Android 7.0 Having latest updates and calendar version 1.4.3.

**Comment by nicbell** [comment]
I have this same problem in Nougat, works fine in Marshmallow. Did anyone find a fix?

**Comment by nicbell** [comment]
I've submitted a PR.

If you want to test my fix the dependency is available here.
`implementation 'com.github.nicbell:material-calendarview:patch-1-SNAPSHOT'`

**Comment by nicbell** [comment]
Hi @quentin41500, @chahinem has this project been abandoned?
