### ISSUE TITLE
MaterialCalendarView.setSelectedDate(Date date) is not working

### ISSUE THREAD

**Issue by MinyoungJung** [prolificinteractive/material-calendarview#5]
MaterialCalendarView.setSelectedDate(Date date) is not working, it sets the date to 1970/1/1.
MaterialCalendarView.setSelectedDate(Calendar calendar) works fine.

**Comment by dandc87** [comment]
Sorry about this. I'll get a fix for this released by the end of the day.

**Comment by MinyoungJung** [comment]
Thanks for the quick reply.
By the way, is there any way to change the text color of selected date?

**Comment by dandc87** [comment]
@MinyoungJung you would have to supply a `dateTextAppearance` which has `textColor` set as a `ColorStateList` where you set the `android:state_checked` color to the custom color. This is a little convoluted and not really documented well. As an example, look at `TextAppearance.MaterialCalendarWidget.Date` style defined in the library.

**Comment by dandc87** [comment]
Should be resolved in v0.2.2

**Comment by MinyoungJung** [comment]
@dandc87 Thanks, problem solved :+1:
