### ISSUE TITLE
Direction Button not working properly with recycler view

### ISSUE THREAD

**Issue by yuanliu666** [prolificinteractive/material-calendarview#502]
When I use this calendar view with a recycler view in a coordinator layout, the scrolling behavior of this recycler view makes the direction buttons not working. Namely on start the buttons will work, but if I scroll the recycler view a little bit, the toolbar and the tab will be hidden, and now the buttons do not work.
Meanwhile the log shows this:
W/View: requestLayout() improperly called by com.prolificinteractive.materialcalendarview.CalendarPager{2f79128b VFED.... ......ID 1,154-1079,462 #7f120009 app:id/mcv_pager} during layout: running second layout pass
Can anybody tell me what goes wrong?

**Comment by quentin41500** [comment]
Are you still seeing this issue? Could you add a sample activity to our sample app for us to investigate? Thank you
