### ISSUE TITLE
Connect with Calligraphy

### ISSUE THREAD

**Issue by linean** [prolificinteractive/material-calendarview#503]
Hi, is there any way to connect calendar with Calligraphy font? It seems not working as default ;(

**Comment by bellierjonathan** [comment]
No solution?

**Comment by bellierjonathan** [comment]
Same problem, Im trying to apply fonts on DayView but isn't working.

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/382
