### ISSUE TITLE
disable past days

### ISSUE THREAD

**Issue by Ravi852741** [prolificinteractive/material-calendarview#504]

**Comment by WasimMemon** [comment]
You can set minimum date using state method of view.

```
Calendar minDateCalendar = Calendar.getInstance();
calendarView.state().edit()
.setMinimumDate(minDateCalendar).commit();
```

**Comment by rameshmedical** [comment]
Calendar minDateCalendar = Calendar.getInstance();
calendarView.state().edit()
.setMinimumDate(minDateCalendar).commit(); 


 app:mcv_showOtherDates="out_of_range"

**Comment by li2** [comment]
@quentin41500 is it possible to make disabled day grey instead of invisible? Thanks
