### ISSUE TITLE
Remove margin 

### ISSUE THREAD

**Issue by hashmedia1** [prolificinteractive/material-calendarview#508]
![16651271_10206511013172588_1956260043_o](https://cloud.githubusercontent.com/assets/10074963/22782195/f434ab5e-eeeb-11e6-84b2-c26679201be9.png)

I want to remove the margin on both side of topbar. Please help.

**Comment by quentin41500** [comment]
Not sure where that is coming from but I didn't see any margin while using the sample app. I would look into your xml, you might have some margin there.
