### ISSUE TITLE
Xml app:mcv attributes aren't compiling 

### ISSUE THREAD

**Issue by jonibatista** [prolificinteractive/material-calendarview#51]
Hi, I'm new to Android so I don't know if it's a bug or if I'm missing something.

I followed the configuration septs from the README.md and I got the following error:

![screenshot 2015-05-24 12 26 17](https://cloud.githubusercontent.com/assets/709796/7789354/8f84acf6-0255-11e5-9f51-764253b4de19.png)

The attributes with the app:mcv_* aren't compiling.

```
<com.prolificinteractive.materialcalendarview.MaterialCalendarView
    android:id="@+id/calendarView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:mcv_showOtherDates="boolean"
    app:mcv_arrowColor="color"
    app:mcv_selectionColor="color"
    app:mcv_headerTextAppearance="style"
    app:mcv_dateTextAppearance="style"
    app:mcv_weekDayTextAppearance="style"
    app:mcv_weekDayLabels="array"
    app:mcv_monthLabels="array"
    app:mcv_tileSize="dimension"
    app:mcv_firstDayOfWeek="enum"
    />
``` 

I tried with ``compileSdkVersion 21/22``and ``buildToolsVersion "21.1.2/22.0.1"``.

If I remove the app:mcv_* it work just fine.

```
<com.prolificinteractive.materialcalendarview.MaterialCalendarView
    android:id="@+id/calendarView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    />
``` 

What am I missing?

**Comment by NeoDigi** [comment]
Well you need o change the value, for example: 
app:mcv_showOtherDates="boolean"
should be app:mcv_showOtherDates="true" or app:mcv_showOtherDates="false"
also don't forget to add xmlns:app="http://schemas.android.com/apk/res-auto"
in your layout

**Comment by dandc87** [comment]
@NeoDigi is correct, the values in the README are the fields' types.

**Comment by jonibatista** [comment]
SHAME ON ME! I'm embarrassed :( 

What was I doing...  I wasn't looking to the attributes' values. 

Thanks @NeoDigi and @dandc87 and sorry for wasting your time.
