### ISSUE TITLE
Range selection of dates inconsistent

### ISSUE THREAD

**Issue by hilfritz** [prolificinteractive/material-calendarview#516]
There is an inconsistency in using the calendar in _Range Selection_ mode. 
**Process A: - Selecting 2 dates**
Steps: (make sure nothing is selected yet)
1. Select Feb 14 as the start date.
2. Select Feb 15 as the end date.
3. Select the start date (Feb 14) again.
Or 3.1 Select the end date (Feb 15) again).

The result here is that the end date (Feb 15) is selected if you did step 3 or if start date (Feb 14) is selected if you did step 3.1. The thing to note in both cases is that there is always a **selected date** as a result.

**Process B: - Selecting more than 3 days**
Steps: (make sure nothing is selected yet)
1. Select Feb 14 as the start date.
2. Select Feb 17 as the end date.
3. Select any other date.

The result here is that there will be no selected date.

**Question:**
There is inconsistency in the Selection of the calendar, I highly suggest the Selection in Process B is better. How do you fix this?

Note: There is also another issue when just selecting 3 days, not included here. But if the inconsistency between Process A and Process B gets fixed maybe as a result it will also get fixed.
Hope the images below help.

**Sample of Process B:** 
- clicking any date within the range clears the selection
![prolific-material-calendar-issue3a](https://cloud.githubusercontent.com/assets/1725745/23012819/fb7cd9aa-f462-11e6-8c95-0161470cc8d3.gif)

**Sample of Process A: (selecting only 2 days)**
- clicking any date withn the range does not clear the selection
![prolific-material-calendarview-issue3b](https://cloud.githubusercontent.com/assets/1725745/23012830/0ba9545c-f463-11e6-9b6a-8e864a12cc61.gif)

**Bug when you only select 3 days range**
- clicking the middle date does not do anything
- clicking the start or end just clears the selected date
![prolific-material-calendarview-issue3c](https://cloud.githubusercontent.com/assets/1725745/23012841/17940406-f463-11e6-893e-10a376d064b0.gif)

**Comment by WilvdMerwe** [comment]
Thanks for the very well documented issue. I'm experiencing exactly the same as described at Process A and this is causing undesirable effects in my app. Can we get some attention to this issue please.
