### ISSUE TITLE
how to remove the week of next month row display in current month

### ISSUE THREAD

**Issue by Fredydeng** [prolificinteractive/material-calendarview#517]
in the bottom of some page shows the whole week of next month , I dont want the row,how to fix it,sb can help me? will be appreciated

![image](https://cloud.githubusercontent.com/assets/13686952/23010601/50b833da-f457-11e6-862b-80b33b6e1902.png)

**Comment by quentin41500** [comment]
You can use `widget.setDynamicHeightEnabled(true);` for that.
