### ISSUE TITLE
Multiple day selection

### ISSUE THREAD

**Issue by mielet** [prolificinteractive/material-calendarview#52]
Is there a way to customize the calendar to allow for more than one day to be selected?

**Comment by dandc87** [comment]
There currently isn't built in support for multiple selection.

**Comment by eeVoskos** [comment]
+1

**Comment by AnuvadiyaHiren** [comment]
+1

**Comment by birfincankafein** [comment]
+1

**Comment by YuriHeupa** [comment]
+1

**Comment by dandc87** [comment]
This will make it into the 1.0 release. Please test out the beta (see #131)
