### ISSUE TITLE
how to show "today" and select-date together with different background?

### ISSUE THREAD

**Issue by rorschach** [prolificinteractive/material-calendarview#520]
like the picture below, and I have try to implements `DayViewDecorator` just likc `BasicActivityDecorated` to add background for 'today', but it's only works when click the item of date.How can I show "today" and select-date together with different background?Thank you very much!

![](https://camo.githubusercontent.com/3cd74ac334d88ced5b0e33f66eebf57c34f8a670/687474703a2f2f6936332e74696e797069632e636f6d2f766e6a6477352e6a7067)

**Comment by itsMelo** [comment]
@rorschach    Hello, i am in the realization of similar functions, how to add marker on the day? just like you did it. 
![_20170411161024](https://cloud.githubusercontent.com/assets/20601637/24899162/dcf1dcb2-1ed1-11e7-9d47-3cb0b4bcc45f.png)
