### ISSUE TITLE
Add Custom Day Views enhancement

### ISSUE THREAD

**Issue by ghjhf** [prolificinteractive/material-calendarview#521]
I want to add some color text below the day number, and the selection circle background include the day 
number and  exclude the color text。
 first ：1：i need to reduce the  circle scope
                2：and i creat a a decorator，and add a span,but it cant work,I used the SpannableString and
add setpan，at last addpan。if i set the background and setSelectionDrawable  it works。

can you help me？

**Comment by quentin41500** [comment]
You shoud check previous issues as this one as already been asked couple of times. Closing.

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/482
