### ISSUE TITLE
Calendar view is partially updated on Language change in Arabic 

### ISSUE THREAD

**Issue by bilal619** [prolificinteractive/material-calendarview#523]
Hi Guys,

I am using material calendar view in one of my app,  When i switch to arabic language sometimes calendar is not fully updated in case of arabic language. 

Please find the attached screenshot.

![screenshot_ -](https://cloud.githubusercontent.com/assets/7724080/23153256/561e91a4-f829-11e6-9243-80a884805903.png)

**Comment by petitTrung** [comment]
You can use the `setTitleFormatter` method, for example : 

```java
materialCalendarView.setTitleFormatter(day -> {
            Locale locale = new Locale("ar");
            DateFormat dateFormat = new SimpleDateFormat("LLLL yyyy", locale);
            return dateFormat.format(day.getDate());
        });
```
