### ISSUE TITLE
 DayViewDecorator   problems？

### ISSUE THREAD

**Issue by ghjhf** [prolificinteractive/material-calendarview#524]
Why a DayViewDecorator   can only  add the same  span？ Can different Day  add the different span？

**Comment by ghjhf** [comment]
i hope 	decorate(DayViewFacade view) can add a parameter （DayViewFacade view ，CalendarDay day）

**Comment by skillchina** [comment]
![image](https://cloud.githubusercontent.com/assets/4544449/23210796/18d4be56-f93a-11e6-93df-00f5a5df3628.png)
I just want to display the decorator below the background,how to do it

**Comment by ghjhf** [comment]
I know this, but the  The server‘s data at least  seven indetermination  kinds of data.So I must creat a lost of
decorator  to show it?

**Comment by ghjhf** [comment]
我的意思是，我用日历来个人排班，想在每天数字下面写这个人有什么班次，有可能有早班，有可能有晚班，也有可能有早晚班，但是一个DayViewDecorator虽然可以同时给多个天次添加修饰数据，但是数据好像要同一种

**Comment by wlwlxgg** [comment]
这个问题有解决吗，还是得我们自己自定义日历是么，这种需求这个控件是不是没法实现

**Comment by jackdengchuangliang** [comment]
哈哈.这里的问题答的好有趣,英语说着说着就飙车中文来了!
我这也有个问题,就是我给dayview设置background ,看起来一格一格像gridview,可是中间的格子边框都比边缘的粗,也就是相邻的边框重叠了,请问大家有什么好的解决办法吗?给每个dayview加分割线!效果如图...
![812979760179172754](https://user-images.githubusercontent.com/20262929/30020479-8043fcc4-9196-11e7-9c6b-9c76709928a7.png)

**Comment by quentin41500** [comment]
Pea
