### ISSUE TITLE
Collapse Issue 

### ISSUE THREAD

**Issue by Ashishsingh009** [prolificinteractive/material-calendarview#526]
Can we collapse the month in half/full screen animation ?

like this https://raw.githubusercontent.com/blazsolar/android-collapse-calendar-view/develop/images/preview.gif

**Comment by soulrelay** [comment]
I also need to achieve this effect

**Comment by rajscet** [comment]
I also need please help me

**Comment by SoaresGabriel** [comment]
I want this too

**Comment by quentin41500** [comment]
This is not possible currently but something similar was achieved there https://github.com/prolificinteractive/material-calendarview/pull/813.
