### ISSUE TITLE
How to change the background color of week days

### ISSUE THREAD

**Issue by sixscorpions** [prolificinteractive/material-calendarview#527]
Hi ,

I want to change the back ground color or week days. But i didn't succeed.

 
    <style name="tv_style_calender">
        
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">@dimen/_50dp</item>
        <item name="android:textStyle">bold</item>
        <item name="android:background">@color/btn_blue_color</item>
        <item name="android:textColor">@color/btn_blue_color</item>
    </style>

Here all are applied except back ground color. 

app:mcv_weekDayTextAppearance="@style/tv_style_calender"

**Comment by quentin41500** [comment]
You wanna use decorators for that, we have a sample activity that shows that for weekend days, You can just adapt the logic for weekdays.
