### ISSUE TITLE
How to set a OnClickListener to MaterialCalendarView?

### ISSUE THREAD

**Issue by iBotasky** [prolificinteractive/material-calendarview#531]
@joeminkie Helloooooo!
I got a problem.
I want to achieve an effect that when I click the MaterialCalendarView, it will `startActivity` to anthor Activity:
And here is my code：
```
calendarView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(HomeActivity.this,"Click",Toast.LENGTH_SHORT).show();
                startActivity(HomeActivity.this, intent);
            }
        });
```
But it didn't work, I don't have any idea to set a OnClickListener to the MaterialCalendarView?

**Comment by aqibgatoo** [comment]
Any click event is propagated to the child views in this case the `setOnDateChangedListener` will be called .
for your problem i think you should check this [http://stackoverflow.com/questions/4415528/how-to-pass-the-onclick-event-to-its-parent-on-android](link)

**Comment by iBotasky** [comment]
@aqibgatoo OK，thanks i got it！
