### ISSUE TITLE
Putting ListView under calendar will suspend scrolling 

### ISSUE THREAD

**Issue by jimmyyclam** [prolificinteractive/material-calendarview#533]
Hi I opened this issue, because the scolling will not work if a listview is added, please fix ASAP

**Comment by jimzlam** [comment]
Hi I opened this issue, because the scolling will not work if a listview is added, please fix ASap

**Comment by quentin41500** [comment]
Is it still happening? Can you create a code sample for us to reproduce? Sorry for the delay, thanks
