### ISSUE TITLE
Change radius of circle drawable bg

### ISSUE THREAD

**Issue by soulrelay** [prolificinteractive/material-calendarview#536]

**Comment by deepakrana0011** [comment]
Hi soulrelay,
You got any solution to reduce the selected date circle size? Because i m facing the same issue. Please help me out.
Thank you

**Comment by soulrelay** [comment]
Modify source where set the radius，but I don't think it's a good solution

**Comment by quentin41500** [comment]
you should be able tp provide your own drawable with your own size instead of the default one. Look at the sample or the wiki for more.
