### ISSUE TITLE
Using MaterialCalendarView#setSelectedDate does not fire off listeners

### ISSUE THREAD

**Issue by burntcookie90** [prolificinteractive/material-calendarview#537]
Trying to use `com.prolificinteractive.materialcalendarview.MaterialCalendarView#setSelectedDate(com.prolificinteractive.materialcalendarview.CalendarDay)` in order to pre-select a date on the calendar and it's not firing off the `com.prolificinteractive.materialcalendarview.OnDateSelectedListener` set in `com.prolificinteractive.materialcalendarview.MaterialCalendarView#setOnDateChangedListener`. Is this working as intended, or is there another way to ensure that the listeners are fired accordingly?

**Comment by krazykira** [comment]
Yes, that is working as intended. I don't think that setting a date as selected programatically will fire off the `OnDateSelectedListener` event. You should manually do whatever you're doing inside the `OnDateSelectedListener` the first time the dates are selected.

**Comment by burntcookie90** [comment]
That doesn't seem right, the `OnDateSelectedListener` should fire no matter where the "selection" occurs (code, or user interaction).

**Comment by burntcookie90** [comment]
Also, `setSelectedDate` does not page the calendar to selected date (if i'm viewing April, for example, and select a February date via `setSelectedDate` the calendar stays on April).

**Comment by cyberformed** [comment]
Hii, dude

Previously it's working, but now it's not working.

**Comment by quentin41500** [comment]
Working as intended, listener are meant to be called upon user clicks on the calendar as of right now.

> Also, setSelectedDate does not page the calendar to selected date (if i'm viewing April, for example, and select a February date via setSelectedDate the calendar stays on April).

use `widget.setCurrentDate(instance);` with `setSelectedDate` to page over.
