### ISSUE TITLE
How to add bitmap to cell of Calendar

### ISSUE THREAD

**Issue by lethanhtan89** [prolificinteractive/material-calendarview#538]
Now, I would like to add a bitmap to cell of calendar, what should I do?

**Comment by aqibgatoo** [comment]
you need to use a selection Drawable as shown in the  [example](https://github.com/prolificinteractive/material-calendarview/blob/master/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/decorators/MySelectorDecorator.java)

**Comment by lethanhtan89** [comment]
@aqibgatoo Thanks you, I'll check now.
