### ISSUE TITLE
Display the start and end of selection dates differently

### ISSUE THREAD

**Issue by krazykira** [prolificinteractive/material-calendarview#539]
Thankyou for the nice library. I want to display the selected dates start and end in different color or using different drawable.
Is that possible?

**For example:**
![image](https://cloud.githubusercontent.com/assets/2201511/24048680/e5cb32ae-0b29-11e7-92cf-ba59174ad7bf.png)

I want to change color of **21** and **29** in the above image

**Comment by laihuythinh** [comment]
me too

**Comment by quentin41500** [comment]
Check https://github.com/prolificinteractive/material-calendarview/pull/806 for an example!
