### ISSUE TITLE
Selecting multiple dates using setDateSelected()

### ISSUE THREAD

**Issue by MariposaMarie** [prolificinteractive/material-calendarview#541]
I've used:
calendarView.setDateSelected(CalendarDay.today(), true);
calendarView.setDateSelected(CalendarDay.from(2017, 3, 19), true);

but can't seem to get calendarView.setDateSelected(CalendarDay.from(2017, 3, 19), true); to show up on the calendar. Any suggestions? What may I be doing wrong? The entire class is attached below: 

`    public class StatsActivity extends AppCompatActivity {

    private MaterialCalendarView calendarView;
    private ArrayList<Date> dates;
    private Date date = new Date();
    Calendar cal = Calendar.getInstance();

    public StatsActivity() throws ParseException {
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_stats);

        calendarView = (MaterialCalendarView) findViewById(R.id.calendarView);
        initializeCalendar();
    }

    private void initializeCalendar() {
        calendarView.setSelectionMode(SELECTION_MODE_MULTIPLE); // Removes onClick functionality

        cal.add(Calendar.DATE, -1);
        calendarView.setDateSelected(cal.getTime(), true);
        calendarView.setDateSelected(CalendarDay.today(), true);
        calendarView.setDateSelected(CalendarDay.from(2017, 3, 19), true);
    }
`

<img width="341" alt="screen shot 2017-03-24 at 12 15 54 am" src="https://cloud.githubusercontent.com/assets/11483092/24280456/1272612c-1027-11e7-91d2-b3e067bf81b1.png">

As you can see, 3/19/2017 isn't selected

**Comment by Dinesh3027** [comment]
Set an Array with list of dates that you wanted to be selected and in a loop, add the date to the method      calendarView.setDateSelected()

**Comment by MariposaMarie** [comment]
@Dinesh3027 Thank you!

**Comment by KhanStan99** [comment]
@Dinesh3027 , how exactly to create list of dates which i want to select? 
i have done like this,  but it does not work

```
materialCalendarView.setSelectionMode(MaterialCalendarView.SELECTION_MODE_NONE);

        Calendar calendar = Calendar.getInstance();
        calendar.set(2017, 12, 14);

        Calendar calendar2 = Calendar.getInstance();
        calendar.set(2017, 12, 15);

        Calendar calendar3 = Calendar.getInstance();
        calendar.set(2017, 12, 16);

        Calendar calendar4 = Calendar.getInstance();
        calendar.set(2017, 12, 17);


        materialCalendarView.addDecorator(new CurrentDayDecatator(getActivity()));

        materialCalendarView.setDateSelected(calendar, true);
        materialCalendarView.setDateSelected(calendar2, true);
        materialCalendarView.setDateSelected(calendar3, true);
        materialCalendarView.setDateSelected(calendar4, true);
        materialCalendarView.setDateSelected(CalendarDay.today(), false);

```

**Comment by goldstar0415** [comment]
Hi, This does not work for me.
Did you test it on your side correctly?
Hope your solution soon.
