### ISSUE TITLE
How to get the list of dates in MaterialCalendarView.SELECTION_MODE_RANGE

### ISSUE THREAD

**Issue by erylljoy24** [prolificinteractive/material-calendarview#543]
use this line of code List<CalendarDay> dates = materialCalendarView.getSelectedDates(); but it only returns 1 date instead of list of dates

**Comment by lvfaqiang** [comment]
use  materialCalendarView.setOnRangeSelectedListener.

**Comment by mradzinski** [comment]
```getSelectedDates()``` works as expected, it returns a list of the selected dates in the calendar. Would you mind sharing some code or closing the issue if it is resolved?

**Comment by erylljoy24** [comment]
thanks @lvfaqiang and @mradzinski  for the help :)
