### ISSUE TITLE
Circle Background is too big

### ISSUE THREAD

**Issue by Greenikl** [prolificinteractive/material-calendarview#548]
Hi I am trying to reduce the circle background of a selected date. The gray circle of the date selected by default is getting too big, can i decrease the circle size of the selected day?

Any help would be appreciated ThankYou

**Comment by lvfaqiang** [comment]
You can try to use the shape attribute to control the shape you want.

**Comment by Greenikl** [comment]
I've tried it before. Still the same issue and basically the background flickers as the calendar is opened and when i select any other date the same happens.

**Comment by lvfaqiang** [comment]
this is mine my_selector.xml code:
<selector xmlns:android="http://schemas.android.com/apk/res/android"
    android:exitFadeDuration="@android:integer/config_shortAnimTime">

    <item android:state_checked="true"
        android:drawable="@drawable/shape_selection_bg" />

    <item android:state_pressed="true"
        android:drawable="@drawable/shape_selection_bg" />

    <item android:drawable="@android:color/transparent" />

</selector>

shape_selection_bg.xml :

<shape xmlns:android="http://schemas.android.com/apk/res/android">

    <corners android:radius="2dp" />

    <solid android:color="@color/c_1495eb" />

    <stroke
        android:width="1dp"
        android:color="@android:color/transparent" />
</shape>

**Comment by Greenikl** [comment]
Thank You for your time but it didn't solve my problem .

**Comment by Shaooooo** [comment]
666

**Comment by ghjhf** [comment]
private void calculateBounds(int width, int height) {


        final int radius = Math.min(height, width)/2;
        final  int xoffset =Math.abs(width-radius)/2;
        final  int yoffset =Math.abs(height-radius)/2;



        // Lollipop platform bug. Circle drawable offset needs to be half of normal offset
        final int xcircleOffset = Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP ? xoffset / 2 : xoffset;
        final int ycircleOffset = Build.VERSION.SDK_INT == Build.VERSION_CODES.LOLLIPOP ? yoffset / 2 : yoffset;
        Logger log = Logger.getLogger("lavasoft");




        if (width >= height) {
            circleDrawableRect.set(xoffset, yoffset, radius + xoffset, radius+yoffset);
            circleDrawableRect.set(xcircleOffset, ycircleOffset, radius + xcircleOffset, radius+ycircleOffset);
        }

    }

**Comment by Greenikl** [comment]
@ghjhf I ll Check on this ThankYou :)

**Comment by Greenikl** [comment]
@ghjhf Can you just tell me what is circleDrawableRect in your last two statements??

**Comment by Greenikl** [comment]
@ghjhf ThankYou for your time your answer works fine.

**Comment by iad24** [comment]
@Greenikl Was ur problem solved? I dnt know where the function calculateBounds from @ghjhf

**Comment by Gidroshvandel** [comment]
You also can use insets. For example:
<inset xmlns:android="http://schemas.android.com/apk/res/android"
    android:drawable="@drawable/calendar_circle"
    android:insetRight="5dp"
    android:insetLeft="5dp"
    android:insetBottom="5dp"
    android:insetTop="5dp" />

**Comment by pennya** [comment]
https://github.com/Gidroshvandel  It works fine !!!  This is really easiest way to reduce circle.

**Comment by Kaushik-Shyam** [comment]
@Gidroshvandel It's awesome man!!! thank you!!!

**Comment by poojabokdia** [comment]
Where do i add the inset?

**Comment by nithin-aktivolabs** [comment]
> this is mine my_selector.xml code:
> ```
> <item android:state_checked="true"
>     android:drawable="@drawable/shape_selection_bg" />
> 
> <item android:state_pressed="true"
>     android:drawable="@drawable/shape_selection_bg" />
> 
> <item android:drawable="@android:color/transparent" />
> ```
> 
> shape_selection_bg.xml :
> 
> ```
> <corners android:radius="2dp" />
> 
> <solid android:color="@color/c_1495eb" />
> 
> <stroke
>     android:width="1dp"
>     android:color="@android:color/transparent" />
> ```

Nice Idea, If we need a smaller circle for background, the way put stroke color same as background

**Comment by windcloudit** [comment]
> You also can use insets. For example:
> 
> ```
> <inset xmlns:android="http://schemas.android.com/apk/res/android"
>     android:drawable="@drawable/calendar_circle"
>     android:insetRight="5dp"
>     android:insetLeft="5dp"
>     android:insetBottom="5dp"
>     android:insetTop="5dp" />
> ```

Where I need to set it?

**Comment by SoYeonKim522** [comment]
For someone who is not familiar with inset, it's just a type of drawable file like shape, selector etc.
You can add the inset code in drawable directory as a new resource file, put inset as a root element.
And then you can use the drawable file instead of drawable image file itself!

**Comment by youngsjungg** [comment]
Thank you so much. It's my first time using inset, so I didn't understand the above, but your comment was helpful.
