### ISSUE TITLE
How to set different colors for background of different days?

### ISSUE THREAD

**Issue by imWildCat** [prolificinteractive/material-calendarview#55]
I've read https://github.com/prolificinteractive/material-calendarview/issues/33 but there are no date related param in `decorate(DayViewFacade dayViewFacade)` in `DayViewDecorator`.

**Comment by dandc87** [comment]
Hi @imWildCat, as of 0.4.0, a single `DayViewDecorator` doesn't allow for decorating individual dates independently. All dates for a decorator are decorated the same. You can add multiple decorators if you need to decorate individual dates differently, but there are possible performance implications if you do. Please see the [README section on decorators](https://github.com/prolificinteractive/material-calendarview#dayviewdecorator).

**Comment by imWildCat** [comment]
@dandc87 Thanks！
