### ISSUE TITLE
how to use disable to disable previous dates?

### ISSUE THREAD

**Issue by erylljoy24** [prolificinteractive/material-calendarview#550]
i want to disable the previous and the current date and it will not be able to select those days

**Comment by leronj23** [comment]
This is how I did it. Any dates that come before setMinimumDate will be disabled. Any dates that come after setMaximumDate will be disabled.  

calendarView.state().edit()
                .setFirstDayOfWeek(Calendar.SUNDAY)
                .setMinimumDate(CalendarDay.from(currentYear, currentMonth, currentDay))
                .setMaximumDate(CalendarDay.from(lastYear, lastMonth, lastDay))
                .setCalendarDisplayMode(CalendarMode.MONTHS)
                .commit();

**Comment by erylljoy24** [comment]
thanks for the reply @leronj23  :) 
i use this block of code:
materialCalendarView.addDecorator(new DayViewDecorator() {
            @Override
            public boolean shouldDecorate(CalendarDay day) {
                CalendarDay date= CalendarDay.today();
                return (day.isBefore(date)) ? true : false;
            }

            @Override
            public void decorate(DayViewFacade view) {
                view.setSelectionDrawable(getDrawable(R.drawable.drawable_rectangle));
                view.setDaysDisabled(true);
                view.areDaysDisabled();
            }
        });

but the disable dates disappeared, i want to show the dates but it will not be clickable anymore.

**Comment by leronj23** [comment]
This is how you used the code I provided. This is what your activity show have in it.

// Calendar
calendarView = (MaterialCalendarView) findViewById(R.id.calendarView);
calendarView.setSelectionMode(MaterialCalendarView.SELECTION_MODE_MULTIPLE);
calendarView.setOnDateChangedListener(this);

calendarView.state().edit()
.setFirstDayOfWeek(Calendar.SUNDAY)
.setMinimumDate(CalendarDay.from(currentYear, currentMonth, currentDay))
.setMaximumDate(CalendarDay.from(lastYear, lastMonth, lastDay))
.setCalendarDisplayMode(CalendarMode.MONTHS)
.commit();

This is what my shouldDecorate looks like.

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return date != null && day.equals(date);
    }

**Comment by PatelJay017** [comment]
i have used it and its working 

1 step :- 

    private static class PrimeDayDisableDecorator implements DayViewDecorator {

        @Override
        public boolean shouldDecorate(final CalendarDay day) {
            CalendarDay date= CalendarDay.today();
            return (day.isBefore(date)) ? true : false;
        }
        @Override
        public void decorate(final DayViewFacade view) {
            view.setDaysDisabled(true);
        }
    }

Step 2 :- 

in onCreate();
  calendarContainer.addDecorator(new PrimeDayDisableDecorator());
