### ISSUE TITLE
onMonthChanged being called several times v1.4.3

### ISSUE THREAD

**Issue by fernandagallina** [prolificinteractive/material-calendarview#552]
Hi,

I've updated for the latest version (1.4.3) and since then onMonthChanged() have been called more than once or twice. This way, every time I try to go to the next or previous month in the calendar, it backs to the current one. I was using version 1.3.0 and everything was performing smoothly. 

The only things that changed were the 'breaking changes'.

Any thoughts on what could possibly have gone wrong?

Thanks

**Comment by iad24** [comment]
Yes. happening to me now. Any updates on this?

**Comment by quentin41500** [comment]
`l.onMonthChanged(MaterialCalendarView.this, day);` should only be called when a page is selected.

If the pager is calling `onPageSelected` multiple time, then it might get called multiple time. sadly this would then be a pager issue and not a MCV issue.
