### ISSUE TITLE
Highlight several dates with color.

### ISSUE THREAD

**Issue by Rouix** [prolificinteractive/material-calendarview#559]
Good afternoon! Can I highlight a few dates as in the picture? How can I do that?
![05 mdpi](https://cloud.githubusercontent.com/assets/17787652/25097434/f7254038-23bd-11e7-94f2-6c617b83a140.jpg)

**Comment by quentin41500** [comment]
you can use a decorator to do this! You might wanna have a different drawable for the first element, the last element, and the elements in the middle.
