### ISSUE TITLE
What is the difference between the standard implementation?

### ISSUE THREAD

**Issue by kamilwlf** [prolificinteractive/material-calendarview#56]
What is the difference between the standard implementation and material-calendarview?
the latest support library(platform's implementation) now have a full material look and feel

**Comment by dandc87** [comment]
We made this library to have a Material calendar widget that worked on 4.0+. So this library is to function, at least, as a design back port. It's also meant to be more customizable than the platform's widget [android.widget.CalendarView](http://developer.android.com/reference/android/widget/CalendarView.html). Even for targeting 5.0 and up, the date picker was updated to Material design, but not platform's calendar widget. It still looks Holo.
