### ISSUE TITLE
highlighting current date background 

### ISSUE THREAD

**Issue by Greenikl** [prolificinteractive/material-calendarview#565]
Hey, can anyone help me how to set the background color of current date and on selecting another date provide some other background color. So initially the date is selected with some background color but that should not disappear when i select another date.

**Comment by Greenikl** [comment]
Basically i have found solution by creating my own decorator so here is the code:

public class CurrentDateDecorator implements DayViewDecorator {

    private Drawable highlightDrawable;
    private Context context;

    public CurrentDateDecorator( Context context) {
        this.context = context;
        highlightDrawable = this.context.getResources().getDrawable(R.drawable.circlebackground);
    }
    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return day.equals(CalendarDay.today());
    }

    @Override
    public void decorate(DayViewFacade view) {

        view.setBackgroundDrawable(highlightDrawable);
        view.addSpan(new ForegroundColorSpan(Color.WHITE));
        view.addSpan(new StyleSpan(Typeface.BOLD));
        view.addSpan(new RelativeSizeSpan(1.5f));

    }
}

create circlebackground.xml in drawable folder;

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="ring"
    android:innerRadius="0dp"
    android:thickness="15.5dp"
    android:useLevel="false">
    <solid android:color="@color/blue"  />
</shape>

and in your activity where you have used Material Calendar View add this line
mcv.addDecorator(new CurrentDateDecorator(this));

That's it
Happy Coding

**Comment by Greenikl** [comment]
create circlebackground.xml in drawable folder;

<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="ring"
    android:innerRadius="0dp"
    android:thickness="15.5dp"
    android:useLevel="false">
    <solid android:color="@color/blue"  />
</shape>

and in your activity where you have used Material Calendar View add this line
mcv.addDecorator(new CurrentDateDecorator(this));

That's it
Happy Coding

**Comment by skaveesh** [comment]
Many thanks. This helped me.

**Comment by DevGayathri1992** [comment]
Thank you so much

**Comment by Strawberry95** [comment]
I just created this account, only to thank you for this great solution, thank you vey much my friend. 👍
