### ISSUE TITLE
Continue Selection in Range Selection Mode

### ISSUE THREAD

**Issue by saurabhpandya** [prolificinteractive/material-calendarview#568]
Hi, I am using your lib to show select range of dates. It is working as per requirement but I am looking for the implementation which continues the selection even after selection of two dates. i.e. i have selected two dates 1st may to 5th may now I select 9th may. So now selected dates should be 1st may to 9th may(no need to select 1st may again).

**Comment by iad24** [comment]
@saurabhpandya Hi. Did u managed to do this?

**Comment by quentin41500** [comment]
This is not how the range mode is intended to work and we'll not be planning on adding this feature in for the moment. closing
