### ISSUE TITLE
getSelectedDate(); while using Range_Mode returns the wrong date

### ISSUE THREAD

**Issue by AhmedMousa7** [prolificinteractive/material-calendarview#569]
when i try to get the last selected date while using the range mode it returns the day before that day i have selected.
**for example :** when i select first date (9 may )and last date is (15 may)
when i try to getSelectedDate() it should return (15 may) **but it returns (14 may) !!!**

**Comment by AhmedMousa7** [comment]
i have found the solution , the last date i had select it is added to the second position in the array 
i can access it using the getSelectedDates().get(1) 
**i it always added to that position...**

**Comment by ahmedAlmasri** [comment]
same issue
