### ISSUE TITLE
Spacing between days

### ISSUE THREAD

**Issue by HaikuOezu** [prolificinteractive/material-calendarview#571]
Hi, I'm trying to pull off a simple calendar that highlights specific days with different colors and for the most part the library is working flawlessly... however I ran into this little issue
http://d.pr/i/4ITlY

I just want the circles to have a little bit of spacing, for context here's how I pull off the effect
`
@Override
    public void decorate(DayViewFacade view) {
        ShapeDrawable drawable = new ShapeDrawable(new OvalShape());
        drawable.getPaint().setColor(Color.BLUE);
        view.setSelectionDrawable(drawable);
    }
`

I looked up in the issue tracker how to add some spacing and I found two ways, using the mcv_minimizeHorizontalTileHeight and setting the tile size manually.

mcv_minimizeHorizontalTileHeight however doesn't seem to work (I can't even find any reference in the repo aside from a commit for 1.3) the second one makes everything worse by just shrinking the calendar (layout_width and layout_height are both set to match_parent)

http://d.pr/i/xHkvG

How can I add a bit of spacing between individual day cells in the calendar? Or alternatively is there a way I can make the drawable in the decoration have some kind of padding to fake it?

**Comment by tahir-mahmood-10p** [comment]
Also wondering if we can make Day label gravity aligned, like top bottom, currently it is centered

**Comment by pavelaizen** [comment]
what about to reduce your circle size ?

**Comment by HaikuOezu** [comment]
Yeah in the end I found out about InsetDrawable and used that to achieve the desired effect, I was just looking for a cleaner solution and since it was discussed previously in the issues I was wondering why the XML attribute seems to have disappeared.
The solution is not perfect (the selected circle is still bigger, but I suspect I can change that using the same trick) but it works just fine for now

**Comment by tahir-mahmood-10p** [comment]
Any solution to add Dynamic Text Below Date Text?
I have added multiple decorator view for that, but i guess that not a good solution

**Comment by enginebai** [comment]
@HaikuOezu Hi, could you provide some sample code of `InsetDrawable` to add space between days?? I've added but it doesn't work at all.
