### ISSUE TITLE
onDateSelected never gets called

### ISSUE THREAD

**Issue by KUMARHIREN** [prolificinteractive/material-calendarview#574]
public class CalendarActivity extends AppCompatActivity implements OnDateSelectedListener{
        @override
        public void onDateSelected(MaterialCalendarView widget, Calendar calendar, boolean selected){
                Log.v("TAG","DATE SELECTED");
         }
}

**Comment by adriamt** [comment]
I think it's only called when it's selected via a click on the Calendar because I'm facing the same problem, but the Log only gets called when I click the calendar not when I change the date dynamically.

**Comment by Kaleeswaran-Chellaiah** [comment]
MaterialCalendarView  mcv =(MaterialCalendarView)findViewById(R.id.calendarView);
      mcv.setOnDateChangedListener(new OnDateSelectedListener() {
          @Override
          public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {
              Toast.makeText(MainActivity.this,"----current date-------->\n"+date.getDate(),Toast.LENGTH_SHORT).show();
          }
      });

**Comment by quentin41500** [comment]
The listener is indeed intended to be returning value on user selection only.
