### ISSUE TITLE
How to change weekend day title color only, same as we can highlighted weekend days.

### ISSUE THREAD

**Issue by AanadVerma** [prolificinteractive/material-calendarview#591]

**Comment by Erdemtsynduev** [comment]
I added these changes https://github.com/Erdemtsynduev/material-calendarview
Now in the library, you can change the color of the weekend in WeekDayTextAppearance. You can change the color in the app: mcv_weekendTextAppearance and programmatically in public void setWeekDayTextAppearance (int weekdayResourceId, int weekendResourceId)

**Comment by quentin41500** [comment]
Use decorators for that. You can change the style of specific days.

**Comment by quentin41500** [comment]
Sorry for the delay! Glad you did.
