### ISSUE TITLE
how to choose which week to show

### ISSUE THREAD

**Issue by KoJerry** [prolificinteractive/material-calendarview#592]
I have the calendar in week mode, but on default the week is showing the current week, how can I make that the week shown is another week? e.g. the week will show the week of date that someone has entered in edittext

**Comment by quentin41500** [comment]
```
    /**
     * @param day a CalendarDay to focus the calendar on. Null will do nothing
     */
    public void setCurrentDate(@Nullable CalendarDay day) {
      ...
    }
```
