### ISSUE TITLE
custom background with range selection

### ISSUE THREAD

**Issue by TheGreat0004** [prolificinteractive/material-calendarview#594]
I want to change the range selection to the provided preview. I studied the code but found No way to custmize DayView.

Anyhelp would be appreciated.

![149695452190255](https://user-images.githubusercontent.com/10286587/26949691-805f5f8c-4cb8-11e7-8b41-adb53faf6f22.png)

**Comment by Qwin** [comment]
Same here want to do the same but it seems DayView is restricted. I wish the developer @quentin41500 would help us.

**Comment by Qwin** [comment]
@quentin41500 I actually figured out a solution: 
1. select first option for multiple dates in calendar
2. download latest source code -> and pull this PR (this should have already been merged but I am guessing the dev is missing or busy) https://github.com/prolificinteractive/material-calendarview/pull/500
3. Go to DayView.java and change the calculateBounds method to protected.
4. create CustomDayView and create a new DayViewProvider (there is a method now SetDayViewProvider) 
5.  override calculateBounds and copy the original code with one minor change when width is greater then height:
tempRect.set(0, padding, width, height - padding);
(this will make sure that the width of each field is now right next to the other there is no spacing in between.
6. Create decorators (4 of them) 
1. Decorator for normal selection (a round circle) , android shape will do
2. Decorator for round circle with rectangle on the right, android shape (I used layer-list)
3. Decorator for round circle with rectangle on the left, android shape (I used layer-list)
4. Decorator with rectangle for between dates

All decorators get the dates from the constructor.
7. MaterialCalendarViewInstance.RangeSelected should now provide to the decorates the selected range and refresh the decorators Invalidate method of decorators (https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md)
8. enjoy your beloved calendar :)

**Comment by iad24** [comment]
@quentin41500 Thanks for the steps. But possible to share ur code? esp the creation of 4 decorators?

**Comment by Vietvantue** [comment]
@quentin41500 :+1:  Thank you for instruction!
@iad24 I'm also working on it. Will share code to you when finish

**Comment by iad24** [comment]
@Vietvantue Theres a another lib here on top of this lib: https://github.com/ptrstovka/calendarview2
Its from @TheGreat0004 . Thanks mate!

**Comment by iad24** [comment]
@Vietvantue Btw, have u continued on ur own implementation of doing this? Just curious

**Comment by aadilHaffez** [comment]
Anyone has implemented the suggestion given by @Qwin ?

**Comment by TheReprator** [comment]
@aadilHaffez  please go with the new library, as link shared by @iad24
