### ISSUE TITLE
How make the calendar cannot be clicked?

### ISSUE THREAD

**Issue by andShine** [prolificinteractive/material-calendarview#596]
How do you make the calendar only slippable and cannot be clicked

**Comment by Rupesh2Singh** [comment]
use this if you want calendar cannot be clicked on any date :- 
MaterialCalendarView widget;
widget.setSelectionMode(MaterialCalendarView.SELECTION_MODE_NONE);

**Comment by Jaswinder4011** [comment]
What can be done in case we have already provided some dates to be selected by setDateSelected(). After setting these dates, now I do not want any animation which represents click, to happen.
