### ISSUE TITLE
black background in month view

### ISSUE THREAD

**Issue by cuonghq612** [prolificinteractive/material-calendarview#597]
Hi,

I got an black background issue in month view, but only happen January 2017 and December 2017, please see the screenshot, could you have any idea? Thanks.

![Image of Yaktocat](https://image.prntscr.com/image/x9lZOLe_Qmq5l6xZFHmK1A.png)

**Comment by quentin41500** [comment]
can you reproduce with the sample or provide an example activity that reproduce your issue?
