### ISSUE TITLE
Weekly Calendar duplicating days

### ISSUE THREAD

**Issue by brntsw** [prolificinteractive/material-calendarview#602]
Hello,

I have implemented the weekly view of the MaterialCalendarView, which was working fine until a specific date range I saw, which is February 13 2017 until February 19 2017, that duplicated the days, as can be seen below. 

Before clicking on next
[http://imgur.com/a/XL9Dw](http://imgur.com/a/XL9Dw)
After clicking on next
[http://imgur.com/a/ZBem5](http://imgur.com/a/ZBem5)

As shown on the images, the days repeat, which is not the expected result. The result should be: the first week is 12 until 18 of February that is Ok, but the second week would be 19 until 25 of February.

My code is like this:
```
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.ROOT);
        try {
            Date dateFrom = sdf.parse(timesheet.getTimesheetPeriod().getStartDate());
            Date dateTo = sdf.parse(timesheet.getTimesheetPeriod().getEndDate());

            Calendar calFrom = Calendar.getInstance();
            calFrom.setTime(dateFrom);

            Calendar calTo = Calendar.getInstance();
            calTo.setTime(dateTo);

            calendar.state().edit()
                    .setFirstDayOfWeek(Calendar.SUNDAY)
                    .setCalendarDisplayMode(CalendarMode.WEEKS)
                    .setMinimumDate(CalendarDay.from(calFrom.get(Calendar.YEAR), calFrom.get(Calendar.MONTH), calFrom.get(Calendar.DAY_OF_MONTH)))
                    .setMaximumDate(CalendarDay.from(calTo.get(Calendar.YEAR), calTo.get(Calendar.MONTH), calTo.get(Calendar.DAY_OF_MONTH)))
                    .commit();
        } catch (ParseException e) {
            e.printStackTrace();
        }
```

The first time I load the calendar, I set the current day like this:

```
calendar.setSelectedDate(dateFrom);
calendar.setCurrentDate(dateFrom);
```

Is there something wrong on my code?

**Comment by quentin41500** [comment]
I wasn't able to reproduce on the latest version. Please make sure to reopen the issue if it's still happening. Thank you.
