### ISSUE TITLE
How can the MonthWise Events be displayed?

### ISSUE THREAD

**Issue by SeonSarkar** [prolificinteractive/material-calendarview#603]
I am not able to display the monthwise events with LIstView below the calendar library through the JSON Data.How can this issue be solved?

you can check my question on stackoverflow?
https://stackoverflow.com/questions/44275601/display-the-list-of-events-within-the-calendar

**Comment by quentin41500** [comment]
Not related to MCV directly, feel free to ask help on stackoverflow. closing
