### ISSUE TITLE
How to change the circle size of the selected date？

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [prolificinteractive/material-calendarview#606]

**Comment by iad24** [comment]
@prolificmobile @prolificeric Is it possible to have a simple property for this? It seems a lot of people wants this feature without adding the whole src code or creating a new decorator.

**Comment by quentin41500** [comment]
You can provide your own selection drawable:
```
/**
 * Use a custom selector
 */
public class MySelectorDecorator implements DayViewDecorator {

    private final Drawable drawable;

    public MySelectorDecorator(Activity context) {
        drawable = context.getResources().getDrawable(R.drawable.my_selector);
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return true;
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.setSelectionDrawable(drawable);
    }
}
```

**Comment by Ankit-Slnk** [comment]
> You can provide your own selection drawable:
> 
> ```
> /**
>  * Use a custom selector
>  */
> public class MySelectorDecorator implements DayViewDecorator {
> 
>     private final Drawable drawable;
> 
>     public MySelectorDecorator(Activity context) {
>         drawable = context.getResources().getDrawable(R.drawable.my_selector);
>     }
> 
>     @Override
>     public boolean shouldDecorate(CalendarDay day) {
>         return true;
>     }
> 
>     @Override
>     public void decorate(DayViewFacade view) {
>         view.setSelectionDrawable(drawable);
>     }
> }
> ```

how to apply it and remove when new date is selected
