### ISSUE TITLE
How to forbid the weekday view slide?

### ISSUE THREAD

**Issue by xxwywzy** [prolificinteractive/material-calendarview#609]
I'd like to change the background color of the topbar, but I didn't find a way to implement it. I have tried every solutions mentioned in the previous issues but it doesn't work./(ㄒoㄒ)/~~

**Comment by xxwywzy** [comment]
I have solved the problem above, but I got a new problem: I want to make the weekday view not slide together with the day view, because if the background color of weekday view is changed, it looks strange when it slides o(╯□╰)o, so is there any solution to this problem? thanks so much.

**Comment by quentin41500** [comment]
The solution is to hide it and provide your own implementation then.
