### ISSUE TITLE
How to change title header / weekdays  / dateView custom font style

### ISSUE THREAD

**Issue by Mgap** [prolificinteractive/material-calendarview#611]
i have try to use 
app:mcv_headerTextAppearance @style but its doesn't work if i add font path in the style 
currently just can change the text color , 
have another for adding custom typeface

**Comment by Niroj08** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/582

**Comment by iad24** [comment]
@Niroj08 Can help put here example on how to change the font? I cant find it in the examples. thanks

**Comment by Niroj08** [comment]
@iad24 

implementation 'com.github.anasanasanas:material-calendarview:1.4.4'

allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}

use this attribute inside xml
app:mcv_textTypeFace="@string/font"

<string name="font">fonts/your_font.ttf</string>

That much will do for you :) (Y)

**Comment by iad24** [comment]
@Niroj08 only 1 typeface can be applied to all the text? cos I have 3 different typeface. Different typeface for month, weekday title, and the dates. Possible to apply multiple fonts?

**Comment by quentin41500** [comment]
Now in: https://github.com/prolificinteractive/material-calendarview/pull/782
