### ISSUE TITLE
how can i give background to the selected date other than current date?

### ISSUE THREAD

**Issue by BynryGit** [prolificinteractive/material-calendarview#612]

**Comment by Qwin** [comment]
Have a look at the sample, it uses decorators. You can create a decorator and supply a list of dates that you want highlighted. For further info please see the decorator docs:
https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md

https://github.com/prolificinteractive/material-calendarview/blob/master/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/BasicActivityDecorated.java

**Comment by SugamPradhan** [comment]
I used DayViewDecorator 
It created a dot below the dates
But is there a way to change background of the selected date..

Any help will be appreciated..

**Comment by SugamPradhan** [comment]
int color with color code

drawable = new ColorDrawable(color);

view.setBackgroundDrawable(drawable);
