### ISSUE TITLE
How to jump to a particular date

### ISSUE THREAD

**Issue by rgk1221** [prolificinteractive/material-calendarview#615]
I want that i should provide a month or date to calendar using which it will directly jump to that particular month so that user need not always scroll 10times to get to a specific month of a specific year.

**Comment by quentin41500** [comment]
What you can do is implement a month switcher when the user click on a certain button (maybe using `setOnTitleClickListener`). The month switcher is out of scope for this library so I would recommend doing your own implementation of it or finding a library that works for you.
