### ISSUE TITLE
How can i disable all sundays and alternative saturdays from the calender?

### ISSUE THREAD

**Issue by Aksh0377** [prolificinteractive/material-calendarview#616]

**Comment by Qwin** [comment]
Use decorators (docs https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md). 
Also there is a sample here : https://github.com/prolificinteractive/material-calendarview/blob/master/sample/src/main/java/com/prolificinteractive/materialcalendarview/sample/decorators/HighlightWeekendsDecorator.java

There is a method called SetBackgroundDrawable. Set that to SetDaysDisabled

**Comment by Aksh0377** [comment]
this will disable Saturday and Sunday both, i want to disable all Sundays and "**alternative Saturdays**".

**Comment by Qwin** [comment]
@Aksh0377 you still need to modify that code, I was more pointing to an example. One way to do is by creating a method SetRange(List<Date> dates) in the decorator and then after each OnMonthChange set the range of dates that need to be disabled. (for you that is alternative Saturdays of that month)

**Comment by quentin41500** [comment]
Indeed, please use decorators for that. Thanks @Qwin for the answer. You can provide your own logic for knowing what days to decorate.
