### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Purnima16** [prolificinteractive/material-calendarview#620]
1.How to add a personalized calendar name ?
2.How to add a holiday name below the date ..

please suggest me and please  forward the link if already provided/created .

Thanking you ,
purnima

**Comment by SugamPradhan** [comment]
Have you found any solution to it ??
Let me know

**Comment by Purnima16** [comment]
No',if u have any idea pls suggest

**Comment by quentin41500** [comment]
> 1.How to add a personalized calendar name ?
Not sure what you mean, you can remove the top bar if you want, or provide your list of months.
> 2.How to add a holiday name below the date ..
Use decorators. Check previous issues or sample for more, this question has already been answered.
