### ISSUE TITLE
Getting Date Value to Use in Database

### ISSUE THREAD

**Issue by YPWR** [prolificinteractive/material-calendarview#623]
Hi

I'm learning how to programme and make an app at the same time.

What I want to do is load a ListView with Checkboxes for each day on the calendar. I've mangaed to create a the calendar and the ListView.

My problem is, I want to save the data to a database. To do this I need to get the selected date value an create a new row in the database so that when I click on that same date again it will load the correct checked values.

How do I get the date from Material CalendarView and use it in the database.

**Comment by quentin41500** [comment]
You can get the selected date and use those. Make sure to check the wiki and the sample for more information.
