### ISSUE TITLE
how to hide the weekdayview?

### ISSUE THREAD

**Issue by 838514984** [prolificinteractive/material-calendarview#627]
is there a method to hide the weekdayview?
i can't find it.

**Comment by 838514984** [comment]
ok i delete _WeekDayFormatter()_invoke ,and its work.

**Comment by 838514984** [comment]
ok i delete buildWeekDays(resetAndGetWorkingCalendar());   invoke ,and its work.

**Comment by ytjojo** [comment]
i have same problem ，but i dont want change source code

**Comment by quentin41500** [comment]
It will be available in next release.
