### ISSUE TITLE
how i add a text or point under the day's text.

### ISSUE THREAD

**Issue by liyonghuan** [prolificinteractive/material-calendarview#635]
like this:

![1](https://user-images.githubusercontent.com/7736293/29266572-e76dbabe-8117-11e7-87d4-4fad36ca7394.png)

![2](https://user-images.githubusercontent.com/7736293/29266563-df429760-8117-11e7-9ef2-200d494a5a1e.png)

**Comment by eddydn** [comment]
You can implement DayViewDecorator class

**Comment by liyonghuan** [comment]
thanks, i also do it like this.
