### ISSUE TITLE
RTL in hebrew is not working

### ISSUE THREAD

**Issue by JudaTech1233** [prolificinteractive/material-calendarview#639]
Hello,
In hebrew the RTL is not working - the days appear from left to right,
I fixed the issue in a code that I cloned but I don't know how to suggest it for your review.

best regards.

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/573

**Comment by quentin41500** [comment]
Better RTL support should be coming in the next release, stay tuned
