### ISSUE TITLE
Custom to show lunar date

### ISSUE THREAD

**Issue by tansangxtt** [prolificinteractive/material-calendarview#64]
Hello,
I'd like to make a lunar calendar by using this library. But I haven't found any solution. The problem is how to add a digit in the bottom of lib's date. The following image make you see easily

![image](https://cloud.githubusercontent.com/assets/10300814/8103991/5bb3dc34-1057-11e5-9a29-fe9177e1b518.png)

Is it possible? How to do it?
That's it. Thanks everyone. I'm looking forward to hearing the answers

**Comment by dandc87** [comment]
Hi @tansangxtt. I just added the ability to customize the day labels by setting a `DayFormatter`, so you could use that to show something other than the day's numerals. Otherwise, I don't think there is a good way without heavy customization.
