### ISSUE TITLE
how do i hide the day those that don't on the month?

### ISSUE THREAD

**Issue by liyonghuan** [prolificinteractive/material-calendarview#641]
like this:
![a](https://user-images.githubusercontent.com/7736293/29511114-a9262718-8690-11e7-87ba-5180318cecb6.jpeg)

how do i hide the red area？

**Comment by junchenChow** [comment]
哥们 你这个问题解决了吗 隐藏没有显示的日子多余的行间距

**Comment by liyonghuan** [comment]
并没有...
