### ISSUE TITLE
Resize each day in calendar

### ISSUE THREAD

**Issue by iamlamnguyen** [prolificinteractive/material-calendarview#648]
Hi, guys, I want to custom resize item calendar look like an image:
![screen shot 2017-08-31 at 10 59 19 am](https://user-images.githubusercontent.com/29647445/29905944-b407e1c8-8e3b-11e7-82ec-b55ed5c41b9c.png). Somebody can help me.

**Comment by iamlamnguyen** [comment]
No body help me.

**Comment by quentin41500** [comment]
You can resize all the tile size, not sure about individual tiles so. Here is the documentation for it:
https://github.com/prolificinteractive/material-calendarview/wiki/Customization#tile-size
