### ISSUE TITLE
Stop Scrolling when clicked on a date out of the Current month

### ISSUE THREAD

**Issue by jihadkahil** [prolificinteractive/material-calendarview#658]
When I use : 
app:mcv_showOtherDates="other_months"
It shows perfectly the new Month but when I click on a date for the other month, the Calendar scroll to the next month automatically.
What I want is to show the date of other month but when I clicked on a date do not Scroll.

Thank You

**Comment by quentin41500** [comment]
What you want is `widget.setAllowClickDaysOutsideCurrentMonth(false);`
