### ISSUE TITLE
Reduce Topbar height

### ISSUE THREAD

**Issue by samwoodall** [prolificinteractive/material-calendarview#659]
Hey, awesome library. I'm currently playing around with it and was wondering if there is a way to reduce the height of the topbar or to set the gravity to bottom to fake the reduces height of the bar?. Thanks
![calendar](https://user-images.githubusercontent.com/20459878/30386084-dbebcc58-98a0-11e7-941e-49397f82d8d3.png)

**Comment by Vincebrees** [comment]
You can create your custom xml for Topbar.

**Comment by quentin41500** [comment]
Thanks @Vincebrees, closing..
