### ISSUE TITLE
Apply custom fonts to header title, date and month

### ISSUE THREAD

**Issue by PGAndroid** [prolificinteractive/material-calendarview#665]
I need to apply custom fonts to header title , date and month.

Also i want to reduce spacing between month of days.

Thanks in advanced !!

**Comment by Niroj08** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/582

**Comment by quentin41500** [comment]
Now in the build: https://github.com/prolificinteractive/material-calendarview/pull/782
