### ISSUE TITLE
Switch WeekView to MonthView and vice versa using smooth collpase and expand View

### ISSUE THREAD

**Issue by rajscet** [prolificinteractive/material-calendarview#669]
I want this calendar should work like S Planner. I mean Switching week view and month view and vice versa very smoothly using collapse and expandable view.  can any fork is ready to developed it?
I had tried it using CollapsibleToolbar but got much flickering and date selection issue. dates are redirect to next 7 days

**Comment by soujanyamandala** [comment]
I am trying to do something similar on what you mentioned. Did you get CollapseToolBarLayout working on material calendar view? 
I tried using it and it doesn't work on calendar view.

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/341
