### ISSUE TITLE
Null pointer Exception on state() function of MaterialCalendarView

### ISSUE THREAD

**Issue by nikhil8585** [prolificinteractive/material-calendarview#677]
getting the null pointer exception on implementing the calendar view as follows 

 java.lang.NullPointerException: Attempt to invoke virtual method 'com.prolificinteractive.materialcalendarview.MaterialCalendarView$State com.prolificinteractive.materialcalendarview.MaterialCalendarView.state()' on a null object reference

**Comment by quentin41500** [comment]
Seems like you are not getting the calendar view correctly. I would check how you are finding your view.
