### ISSUE TITLE
Build not working?

### ISSUE THREAD

**Issue by Abhiseshan** [prolificinteractive/material-calendarview#68]
Is it just for me or is the 0.5.0 build not compiling in Sudio? 
Also its not building properly on jitpack.io

log of the build on jitpack.io
find: `dirname' terminated by signal 13
find: `dirname' terminated by signal 13
Run gradle build
Gradle build script
Downloading https://services.gradle.org/distributions/gradle-2.2.1-all.zip
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1-all.zip to /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn
Set executable permissions for: /home/jitpack/.gradle/wrapper/dists/gradle-2.2.1-all/6dibv5rcnnqlfbq9klf8imrndn/gradle-2.2.1/bin/gradle

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_76 (Oracle Corporation 24.76-b04)
OS:           Linux 3.13.0-36-generic amd64

Getting a list of gradle tasks
Running: ./gradlew clean -Pgroup=com.github.prolificinteractive -Pversion=v0.5.0 -xtest uploadArchives
:library:clean UP-TO-DATE
:sample:clean UP-TO-DATE
:library:compileLint
:library:copyReleaseLint UP-TO-DATE
:library:preBuild UP-TO-DATE
:library:preReleaseBuild UP-TO-DATE
:library:checkReleaseManifest
:library:preDebugAndroidTestBuild UP-TO-DATE
:library:preDebugBuild UP-TO-DATE
:library:preDebugUnitTestBuild UP-TO-DATE
:library:preReleaseUnitTestBuild UP-TO-DATE
:library:prepareComAndroidSupportSupportV42220Library
:library:prepareReleaseDependencies
:library:compileReleaseAidl
:library:compileReleaseRenderscript
:library:generateReleaseBuildConfig
:library:generateReleaseAssets UP-TO-DATE
:library:mergeReleaseAssets
:library:generateReleaseResValues
:library:generateReleaseResources
:library:mergeReleaseResources
:library:processReleaseManifest
:library:processReleaseResources
:library:generateReleaseSources
:library:processReleaseJavaRes UP-TO-DATE
:library:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:library:extractReleaseAnnotations
:library:mergeReleaseProguardFiles
:library:packageReleaseJar
:library:compileReleaseNdk UP-TO-DATE
:library:packageReleaseJniLibs UP-TO-DATE
:library:packageReleaseLocalJar UP-TO-DATE
:library:packageReleaseRenderscript UP-TO-DATE
:library:packageReleaseResources
:library:bundleRelease
:library:sourcesJar
:library:signArchives SKIPPED
:library:uploadArchivesUploading: com/prolificinteractive/material-calendarview/0.5.0/material-calendarview-0.5.0.aar to repository remote at https://oss.sonatype.org/service/local/staging/deploy/maven2/
Transferring 47K from remote
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:uploadArchives'.
> Could not publish configuration 'archives'
   > Error deploying artifact 'com.prolificinteractive:material-calendarview:aar': Error deploying artifact: Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/prolificinteractive/material-calendarview/0.5.0/material-calendarview-0.5.0.aar. Return code is: 401

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.643 secs
Trying again without wrapper
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=cb19a298-3b33-4e7c-8eed-e2501d01999a.1, currentDir=/build}
Attempting to read last messages from the daemon log...
Daemon pid: 204
  log file: /home/jitpack/.gradle/daemon/2.4/daemon-204.out.log
----- Last  20 lines from daemon log file - daemon-204.out.log -----
13:48:10.957 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=cb19a298-3b33-4e7c-8eed-e2501d01999a.1, currentDir=/build}, connection = org.gradle.launcher.daemon.server.DefaultDaemonConnection@31873729] after 0.0 minutes of idle
13:48:10.958 [INFO] [org.gradle.launcher.daemon.server.DomainRegistryUpdater] Marking the daemon as busy, address: [2482979d-8c63-4cfb-801f-6316ec43c004 port:49651, addresses:[/0:0:0:0:0:0:0:1%1, /127.0.0.1]]
13:48:10.959 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [2482979d-8c63-4cfb-801f-6316ec43c004 port:49651, addresses:[/0:0:0:0:0:0:0:1%1, /127.0.0.1]]
13:48:10.960 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
13:48:10.961 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
13:48:10.965 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
13:48:10.966 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] updating lastActivityAt to 1434635290966
13:48:10.966 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Daemon is busy, sleeping until state changes.
13:48:10.967 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=cb19a298-3b33-4e7c-8eed-e2501d01999a.1, currentDir=/build}. Dispatching build started information...
13:48:10.968 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 15: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
13:48:10.976 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {HOSTNAME=4a22f13f5471, PWD=/build, OLDPWD=/usr/share/gradle, HOME=/home/jitpack, JAVA8_HOME=/usr/lib/jvm/java-8-oracle, JAVA_HOME=/usr/lib/jvm/java-7-oracle, SHLVL=2, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, JAVA7_HOME=/usr/lib/jvm/java-7-oracle, ANDROID_HOME=/android, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat}
13:48:10.988 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 13: received class org.gradle.launcher.daemon.protocol.CloseInput
13:48:10.989 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] Received IO message from client: CloseInput[id=cb19a298-3b33-4e7c-8eed-e2501d01999a.2]
13:48:10.992 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
13:48:10.993 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 204). The daemon log file: /home/jitpack/.gradle/daemon/2.4/daemon-204.out.log
13:48:11.002 [INFO] [org.gradle.launcher.daemon.server.health.DaemonHealthTracker] Starting build in new daemon [memory: 954.7 MB]
13:48:11.004 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] Closing daemon's stdin at end of input.
13:48:11.005 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] The daemon will no longer process any standard input.
13:48:11.008 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
13:48:11.009 [INFO] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=eb3d3b4d-18d6-4b80-b4a0-fc5bf9a17871,javaHome=/usr/lib/jvm/java-7-oracle,daemonRegistryDir=/home/jitpack/.gradle/daemon,pid=204,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=US-ASCII,-Duser.country=US,-Duser.language=en,-Duser.variant]
----- End of the daemon log -----

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
No build artifacts found

**Comment by jitpack-io** [comment]
@Abhiseshan It doesn't work for that version but works with the latest master code: https://jitpack.io/#prolificinteractive/material-calendarview/d00f3e65b2
Shouldn't be a problem with next release.

**Comment by dandc87** [comment]
Released v0.6.0 and it's working again.
