### ISSUE TITLE
trying to setTypeface() on DayView and WeekDayView

### ISSUE THREAD

**Issue by ebbnormal** [prolificinteractive/material-calendarview#682]
Hello,
I forked Release 1.4.3 and I am trying to add functionality of setting a custom typeface to all of the Views drawn by the `MaterialCalendarView`. 
I am currently trying to pass a `Typeface` to my `MaterialCalendarView` which i do successfully. However When I try to add the following three lines to the `CalendarPagerView`:

         public void setWeekDayTextAppearance(int taId) {
             for (WeekDayView weekDayView : weekDayViews) {
                 if(MaterialCalendarView.typeface != null) {
                     weekDayView.setTypeface(MaterialCalendarView.typeface);
                 }
                 weekDayView.setTextAppearance(getContext(), taId);
             }
         }

But i don't see the typeface loading in the calendar UI even though my typeface isn't null

I do the same thing for the DayView: 

         protected void addDayView(Collection<DayView> dayViews, Calendar calendar) {
               CalendarDay day = CalendarDay.from(calendar);
               DayView dayView = new DayView(getContext(), day);
               dayView.setOnClickListener(this);
               if(MaterialCalendarView.typeface != null) {
                  dayView.setTypeface(MaterialCalendarView.typeface);
               }

               dayViews.add(dayView);
               addView(dayView, new LayoutParams());

               calendar.add(DATE, 1);
         }

**Comment by PedroBernils** [comment]
I managed to do it by making a decorator as such:

`public class BaseDecorator implements DayViewDecorator {

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return true;
    }

    @Override
    public void decorate(DayViewFacade view) {
        Typeface typeface = Typeface.createFromAsset(ContextManager.getInstance().getContext().getApplicationContext().getAssets(), "fonts/customfont.ttf");
        view.addSpan(new CustomTypefaceSpan("customfont", typeface));
    }
}`

Then I simply add it to the calendar view on the onCreate of my activity:

`        calendarView.addDecorator(new BaseDecorator());`

**Comment by PedroBernils** [comment]
I managed to do it by making a decorator as such:

`public class BaseDecorator implements DayViewDecorator {

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return true;
    }

    @Override
    public void decorate(DayViewFacade view) {
        Typeface typeface = Typeface.createFromAsset(ContextManager.getInstance().getContext().getApplicationContext().getAssets(), "fonts/customfont.ttf");
        view.addSpan(new CustomTypefaceSpan("customfont", typeface));
    }
} `

Then I simply add it to the calendar view on the onCreate of my activity:

`        calendarView.addDecorator(new BaseDecorator());`

**Comment by tevjef** [comment]
Can you try setting through the textAppearance property?

```
<style name="CustomTextAppearance" >
      <item name="fontFamily">@font/my_font</item>
</style>
```

```
app:mcv_weekDayTextAppearance="@style/CustomTextAppearance"
```

**Comment by quentin41500** [comment]
Closing this now that we have font customization

**Comment by Thien658jjh** [comment]
> Closing this now that we have font customization ??

Where ? I can't see :'(

**Comment by tevjef** [comment]
@Thien658jjh https://github.com/prolificinteractive/material-calendarview/issues/682#issuecomment-399586181
