### ISSUE TITLE
Change Font Example

### ISSUE THREAD

**Issue by iad24** [prolificinteractive/material-calendarview#688]
I saw thats theres a support for this. But I dont see any example how to change to a custom font.
Anyone can help me?

**Comment by Niroj08** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/582

**Comment by quentin41500** [comment]
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/688

**Comment by quentin41500** [comment]
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/382
