### ISSUE TITLE
how to disable arrow from changing months?

### ISSUE THREAD

**Issue by iad24** [prolificinteractive/material-calendarview#689]
Possible to just use the swiping gesture to change months? And hide and disable click function for the arrows?

**Comment by quentin41500** [comment]
You could hide the header using `setTopbarVisible` and display your own

**Comment by rakeshbaral92** [comment]
How to hide the left and right arrow in calendar view ?

**Comment by rakeshbaral92** [comment]
Please use this. Set visibility gone when you need to disable the month change. Do it inside MaterialCalendarView. The path is (library\src\main\java\com\prolificinteractive\materialcalendarview)

buttonFuture.setVisibility(GONE);
buttonPast.setVisibility(GONE);
