### ISSUE TITLE
MaterialCalendarView height WRAP_CONTENT

### ISSUE THREAD

**Issue by Link184** [prolificinteractive/material-calendarview#690]
Hey, awesome lib!
Is possible to adapt MaterialCalendarView height by active weeks? There are a lot of unused space in case that last week is from next month(disabled week).

[Screenshot](https://imgur.com/a/gQmqr)

**Comment by Link184** [comment]
found solution setDynamicHeightEnabled(true); :)

**Comment by awaisabbasaa11** [comment]
Thank you so much
