### ISSUE TITLE
How to get CalendarDay value on decorate method?

### ISSUE THREAD

**Issue by saurabhmdh** [prolificinteractive/material-calendarview#694]
I am working on to create price view (as attached in picture).  I have a map which contains selected date & their price. 

Please help on decorate method, how to get CalendarDay as key.

public class DaysDecorator implements DayViewDecorator {
    private final Context context;
    Map<CalendarDay, String> priceMap;
    
    public DaysDecorator(Context context, Map<CalendarDay, String> priceMap) {
        this.context = context;
        this.priceMap = priceMap;
    }
    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return priceMap.containsKey(day);
    }

    @Override
    public void decorate(DayViewFacade view) {
        int price = priceMap.get(); //How to get CalendarDay here
        view.addSpan(new PriceSpan(35, Color.LTGRAY, 120000));
    }
}
//PriceSpan
class PriceSpan implements LineBackgroundSpan {

    private final float radius;
    private final int color;
    private final int price;
    /**
     * Create a span to draw a dot using a specified radius and color
     *
     * @param radius radius for the dot
     * @param color  color of the dot
     */
    @SuppressWarnings("SameParameterValue")
    public PriceSpan(float radius, int color, int price) {
        this.radius = radius;
        this.color = color;
        this.price = price;
    }

    @Override
    public void drawBackground(
            Canvas canvas, Paint paint,
            int left, int right, int top, int baseline, int bottom,
            CharSequence charSequence,
            int start, int end, int lineNum
    ) {
        int oldColor = paint.getColor();
        float oldTextSize = paint.getTextSize();
        if (color != 0) {
            paint.setColor(color);
        }
        if (price != 0) {
            paint.setTextSize(35.0f);
        }
        String text = String.valueOf(price);
        Rect bounds = new Rect();
        paint.getTextBounds(text, 0, text.length(), bounds);
        int x = ((left + right) / 2) - (bounds.width() / 2);
        canvas.drawText(text, x, bottom + radius, paint);
        paint.setTextSize(oldTextSize);
        paint.setColor(oldColor);
    }
}
![screen shot 2017-11-16 at 14 42 03](https://user-images.githubusercontent.com/23295386/32876650-2aa7b84e-cae1-11e7-8c05-8a5236182949.png)

**Comment by iad24** [comment]
hi @saurabhmdh were u able to do some work around for this?

**Comment by saurabhmdh** [comment]
Yes, I did some work around. I am worried about performance. 

here is my code 
            List <DayViewDecorator> decorators = new ArrayList<>();
            decorators.add(decorator);
            decorators.add(new PrimeDayDisableDecorator(object.getSelectedDate()));
            if (isRated) {
                for (CalendarDay day : rate.keySet()) {
                    decorators.add(new DaysDecorator(getContext(), day, rate.get(day)));
                }
            }
            widget.addDecorators(decorators);

![screen shot 2017-12-13 at 16 39 21](https://user-images.githubusercontent.com/23295386/33927147-7596ce0a-e024-11e7-8637-69b21f9d9e72.png)
