### ISSUE TITLE
Tile height and width are preserved in the SavedInstanceState and override XML values

### ISSUE THREAD

**Issue by magneticflux-** [prolificinteractive/material-calendarview#697]
What occurs:
I have a layout with a landscape and a portrait version. The portrait version defines the height of the tiles, but the landscape version does not. When the view is destroyed and recreated in the other orientation, the height and width values are saved and restored, causing the view to be the wrong size.

Expected behavior:
The XML attributes should override the saved width and height in all instances. There is no instance where tile height and width should be preserved through rotations since they are part of the view's layout rather than the view's internal state.

**Comment by quentin41500** [comment]
This will be available in the next release. Stay tuned!
