### ISSUE TITLE
Collapsed calendar does not change month if you change the day to a different month

### ISSUE THREAD

**Issue by moriso** [prolificinteractive/material-calendarview#701]
How to reproduce it:
- Select the last day of a month. The month shouldn't end on the last configured day (like on Saturday if it's default)
- Collapse the calendar
- Click on the following day

The month on the header should change to the following month. Instead, it stays the same.

**Comment by quentin41500** [comment]
I wasn't able to reproduce. When in week mode, the calendar display the month of the first day of the week currently displayed. If you could share a video maybe that would be helpful.
