### ISSUE TITLE
Library shows a week twice (between the DST switch)

### ISSUE THREAD

**Issue by AngeloAvv** [prolificinteractive/material-calendarview#704]
Scrolling the Material CalendarView in week mode, the view presents a week twice.
The week showed twice contains the day when there's a DST switch.

Here's a [video ](https://streamable.com/s/tjso7/oohmok)of the issue

**Comment by quentin41500** [comment]
Hey @AngeloAvv, I wasn't able to reproduce your issue using our sample. Can you reproduce on the sample yourself?

**Comment by quentin41500** [comment]
CNR. Closing
