### ISSUE TITLE
Is it possible to jump to a specific date with a button click?

### ISSUE THREAD

**Issue by PedroBernils** [prolificinteractive/material-calendarview#706]
Basically as the title says, I want my user to be able to instantly go back to the current day by clicking a button.

I'm already calling

`calendarView.setCurrentDate(today); `

But I can't seem to find any method that forces the view to center on the selected month and year.

**Comment by PedroBernils** [comment]
Never mind, found it.

In case anyone in the future has the same issue, the method you want is:

`setCurrentDate(CalendarDay day, boolean useSmoothScroll)`

Not the variant with a single argument that I was using initially, the two arguments version will scroll (smoothly or not) to the selected month in question.

**Comment by Ceddi23** [comment]
This what I was looking for. thanks

**Comment by yash59** [comment]
@PedroBernils calendar is scrolling to the specified month but the date is not getting selected?
