### ISSUE TITLE
Possible to only invalidate a specific DayViewDecorator

### ISSUE THREAD

**Issue by iad24** [prolificinteractive/material-calendarview#707]
For example, I have 10 decorators attached to my calendar view.
I only want to invalidate the first decorator; I don't want to invalidate the others cos it will it make it slow.

**Comment by Marchuck** [comment]
@iad24 
you can directly hold specific docorator like:
```
DayViewDecorator myDecorator = ...
calendarView.addDecorator(myDecorator)
calendarView.addDecorators(second,third,...tenth)
```

then you can remove existing one and add again (how invalidate works :) )
```
calendarView.removeDecorator(myDecorator)
myDecorator = ...//invalidate here
calendarView.addDecorator(myDecorator)
```
