### ISSUE TITLE
How to disable swipe to change month and enable date range select by swipe from one date to other

### ISSUE THREAD

**Issue by agi-umar** [prolificinteractive/material-calendarview#708]

**Comment by nofal-barefoot** [comment]
Any update on this..?

**Comment by quentin41500** [comment]
Please check the sample and wiki as they have example for that.

You can use SELECTION_MODE_RANGE and setPagingEnabled

**Comment by quentin41500** [comment]
There is no swipe feature for range selection at the moment but there is a PR currently for it. It's a pretty substantial api change so I would need more testing to make sure nothing break. No plan to add it at the moment but feel free to fork it for yourself
