### ISSUE TITLE
please support week view with animation

### ISSUE THREAD

**Issue by morpheus-chang** [prolificinteractive/material-calendarview#71]
like this 
![calend.gif](https://github.com/jonathantribouharet/JTCalendar/raw/master/Screens/example.gif)

**Comment by dandc87** [comment]
I'm sorry, but we don't plan on supporting this anytime soon. Maybe in the distant future.

**Comment by morpheus-chang** [comment]
And hope to see this useful feature in the near future, even though, thanks to the existing functionality of the project.  :smile:
