### ISSUE TITLE
add text below date like we add dotspan 

### ISSUE THREAD

**Issue by shrutinupur** [prolificinteractive/material-calendarview#711]
like dotspan how to text below the date

**Comment by yehiahd** [comment]
+1

**Comment by Slavcheg2107** [comment]
it's possible with same span interface as in DotsSpan.
Create your custom span and implement LineBackgroundSpan.
``public` class CalendarViewSpan implements LineBackgroundSpan {

String text;
public CalendarViewSpan(String text){
    this.text = text;
}

    @Override
    public void drawBackground(Canvas c, Paint p, int left, int right, int top, int baseline, int bottom,
                               CharSequence text, int start, int end, int lnum) {
        p.setColor(App.getContext().getResources().getColor(R.color.orange));
        text = this.text;
        c.drawText(String.valueOf(text), left-right, bottom+15, p );
    }
}

**Comment by quentin41500** [comment]
Thanks for the answer @Slavcheg2107, you can also check previous issues as this one as already been asked couple of times. Closing.
