### ISSUE TITLE
Error selecting three day range

### ISSUE THREAD

**Issue by DanielEhecatl** [prolificinteractive/material-calendarview#715]
When you select a range of three days and select the date in between, nothing happens. The event continues to indicate that 3 days have been selected. The correct thing would be to clean the selection and select the date in between.

**Comment by WilvdMerwe** [comment]
I'm experiencing the exact same issue. Can we please get some attention to this issue please.

**Comment by quentin41500** [comment]
Feel free to submit a PR with a fix!

**Comment by quentin41500** [comment]
Gonna close this as duplicate, feel free to check the issue here: https://github.com/prolificinteractive/material-calendarview/issues/516
