### ISSUE TITLE
Month Scroller Issue

### ISSUE THREAD

**Issue by Shrirambaabu** [prolificinteractive/material-calendarview#718]
Hi ,
If we Scroll months previously and forward for three times, It Works fine. but, 4th time, the month values as wrong.
For Example, we tried to scroll around Nov,Dec,Jan,Feb. We logged which month is selected. When we switch between these months thrice, its working fine but 4 th time, if we select jan, it logs as Feb  and so on.. Can you tell a solution for this issue?

**Comment by quentin41500** [comment]
Not sure, how we should fix this. Feel free to submit a PR with a fix if you find one.
