### ISSUE TITLE
How to add recurring event?

### ISSUE THREAD

**Issue by McLaLa** [prolificinteractive/material-calendarview#720]
Could someone explain how to display a recurring event? I would like to see a event which appears every Monday in calendar view. For instance, display event with a schedule from 2018-01-12 to 2018-04-12, 12:00 - 13:00 every Monday only.

Thank you!

**Comment by akamanzi** [comment]
@McLaLa did you find any solutions to your raised issue??

**Comment by McLaLa** [comment]
@akamanzi No, I do my schedule calculations on server side and just present them in calendar view.

**Comment by quentin41500** [comment]
You can accomplish this with decorators. Please read the documentation here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md
