### ISSUE TITLE
How to set special dates' text color?

### ISSUE THREAD

**Issue by SamBob01** [prolificinteractive/material-calendarview#721]
now I had a recommand that i need set the different textcolor on many special dates,but i can't find the method to solve it
![image](https://user-images.githubusercontent.com/31183007/35041038-58c641ce-fbbe-11e7-808a-977603c24c7f.png)

**Comment by enderkoca** [comment]
first you need to create decorator class than use  this method       calendar.addDecorators(new MySelectorDecorator(MainActivity.activity)); which date you want

**Comment by SamBob01** [comment]
thanks for your help,but if i use the method it will change all text color,would you please give me a demo?thanks!!

**Comment by SamBob01** [comment]
I've solve this problem,while use the decorate class,add below code:
 view.addSpan(new ForegroundColorSpan(Color.BLUE));
@enderkoca thanks for your answer,it is very useful for me!
