### ISSUE TITLE
Calendar is not displayed on API 7.0 in RTL

### ISSUE THREAD

**Issue by mays123** [prolificinteractive/material-calendarview#724]
i tried to use the library on devices with API 7.0 , it worked on some of them and a blank pager is displayed on others since weekdays and days are not shown (no decorators) but clickable.
Anyone could help me solving this please?

issue appears on these devices:
Huawei P9 Lite (7.0)
Huawei Y7 Pro (7.0)

**Comment by llollox** [comment]
Same problem to me.
I'm working on Android 6.0.1

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/pull/573/files

**Comment by quentin41500** [comment]
Better RTL support should be coming in the next release, stay tuned
