### ISSUE TITLE
make old date before current date look dim and not clickable

### ISSUE THREAD

**Issue by tayyabtariq50** [prolificinteractive/material-calendarview#727]

**Comment by quentin41500** [comment]
Please check the sample, you can accomplish that. The documentation is here https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOMIZATION.md#showing-other-dates

**Comment by 1nullpointer** [comment]
Can you please add an example. Am struggling to understand the docs .It says min max range but doesn't mention how
