### ISSUE TITLE
Update com.android.support version to 27+

### ISSUE THREAD

**Issue by monowar1993** [prolificinteractive/material-calendarview#728]
I cloned your repository to check out the sample app. Gradle asked me to update my com.android.support libraries to 27+ as warnings. I updated them. But BetterViewPager class's setChildrenDrawingOrderEnabledCompat method was throwing errors and leading to app crash. Please check this out and update to latest version. 
Thanks for making such a useful and easy library.

**Comment by quentin41500** [comment]
1.5.0 was updated to the latest of gradle.
