### ISSUE TITLE
Urgent college project so hoping for your reply to be quick.

### ISSUE THREAD

**Issue by Yashkumar-Panchal** [prolificinteractive/material-calendarview#731]
How can i add a personal event to my calendarview in background so the user can't change it & how do i add public hoildays to it.
![screenshot problem1](https://user-images.githubusercontent.com/24263227/35788018-64b59478-0a58-11e8-8e00-43f2b532f53a.jpg)

Thank You in Advance.

**Comment by quentin41500** [comment]
> How can i add a personal event to my calendarview in background so the user can't change it 

you can disable paging and the top bar as well. 

> how do i add public hoildays to it.

You can use decorators for holidays.

Please check the documentation and sample for more information.
