### ISSUE TITLE
Display only the month and year

### ISSUE THREAD

**Issue by ajonno** [prolificinteractive/material-calendarview#732]
Is it possible to display only the month and year ? via a property or via the state().edit() ? We need to conditionally show the date picker, either in normal month mode (where every day is displayed) or, as months in a year. similar/like this:

![img_5a14710bacae-1](https://user-images.githubusercontent.com/3005269/35789692-f5311f70-0a91-11e8-92aa-8b86a2303deb.jpeg)

**Comment by quentin41500** [comment]
This is not a feature part of this library. This would require a large amount of work to integrate and we are not planning to add large features in the future. Closing this.
