### ISSUE TITLE
problem with compilation to release file

### ISSUE THREAD

**Issue by Matatov1989** [prolificinteractive/material-calendarview#734]
Whatsapp. I have problem with compilation to release file.

Here:

 @Override
    public void setChildrenDrawingOrderEnabledCompat(boolean enable) {
        setChildrenDrawingOrderEnabled(enable);
    } 

1)D:\AndroidStudioProjects\test\MyApplication\library\src\main\java\android\support\v4\view\BetterViewPager.java
Error:(19, 5) error: method does not override or implement a method from a supertype

2)Error:Execution failed for task ':library:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Who can to halp me?
Thanks a lot!!!!

**Comment by quentin41500** [comment]
BetterViewPager was removed in the latest 1.5.0, please check if you are getting the error still
