### ISSUE TITLE
Selection not working any more on lollipop after month swipe

### ISSUE THREAD

**Issue by jitarun** [prolificinteractive/material-calendarview#740]
Hi,
I'm facing this issue in v1.4.3 in Lollipop device (android version 5.1) using the default configuration.
i know its already closed issue #100 .but now I'm  experienced this issue on latest version (v1.4.3).

**Comment by quentin41500** [comment]
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/100

**Comment by quentin41500** [comment]
I reopened the issue, feel free to submit a fix if you have one.
