### ISSUE TITLE
Set title bar color

### ISSUE THREAD

**Issue by thuan09878** [prolificinteractive/material-calendarview#741]
When i use your lib in Activity it works perfectly, but when i put mcv in MaterialDialog https://github.com/afollestad/material-dialogs the title become white as same as the background so i can't see them. I tried to set color by calendarView.setHeaderTextAppearance(R.color.black) but it didn't work.
This happens on 5.0. Do you have any idea?

**Comment by sunwicked** [comment]
Check https://github.com/prolificinteractive/material-calendarview/issues/736

**Comment by quentin41500** [comment]
You can style the header or just implement you own.
