### ISSUE TITLE
Tab Support design breaking

### ISSUE THREAD

**Issue by sudiptaDream** [prolificinteractive/material-calendarview#743]
![screenshot_2018-03-16-00-48-47](https://user-images.githubusercontent.com/5998223/37509363-145a52e6-291d-11e8-9c9d-7ae594d09684.jpg)
please help me to solve the design issue. thanks

**Comment by fedka27** [comment]
@sudiptaDream Hi. You can set dymanic height. 

`
calendarView.setDynamicHeightEnabled(true)
`
