### ISSUE TITLE
Add dot on evented dates which s shows on calendar view 

### ISSUE THREAD

**Issue by Aman49471** [prolificinteractive/material-calendarview#749]
Here i setup the date change listeners i want to add dot on paprticular evented date? how can i?
//////////Date change Listeners/////////////////////////////////////////
        calendarView.setOnDateChangedListener(new OnDateSelectedListener() {
            @Override
            public void onDateSelected(@NonNull MaterialCalendarView widget, @NonNull CalendarDay date, boolean selected) {
                eventObjectsList = db.getAllContacts();
                events = new ArrayList<>();
                events.remove(eventObjects);
                listView.setVisibility(View.GONE);
                textViewNoEvents.setVisibility(View.VISIBLE);

                for (int i = 0; i < eventObjectsList.size(); i++) {
                    if (eventObjectsList.get(i).getText().equalsIgnoreCase(getSelectedDatesString())) {
                        eventObjects = new EventObjects();
                        eventObjects.setText(eventObjectsList.get(i).getText());
                        eventObjects.setDate(eventObjectsList.get(i).getDate());
                        events.add(eventObjects);
                        calendarView.addDecorator(new HighlightDecorator(events));
                        myAdapter = new MyAdapter(getApplication(), events);
                        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(getApplicationContext());
                        listView.setLayoutManager(mLayoutManager);
                        listView.setAdapter(myAdapter);
                        textViewNoEvents.setVisibility(View.GONE);
                        listView.setVisibility(View.VISIBLE);
                    }
                }
            }
        });

**Comment by quentin41500** [comment]
Please refer to decorators and the sample which has example about your question https://github.com/prolificinteractive/material-calendarview/blob/master/docs/DECORATORS.md
