### ISSUE TITLE
add long click event on a certain day

### ISSUE THREAD

**Issue by ignivajigyasa** [prolificinteractive/material-calendarview#751]
Unable to add long click or touch listener on a particular day.

**Comment by Marchuck** [comment]
my fork can do this using OnDatePickedListener
https://github.com/Marchuck/material-calendarview

see branch feature/on-date-picked-listener

**Comment by quentin41500** [comment]
Duplicate of https://github.com/prolificinteractive/material-calendarview/issues/335. Closing
