### ISSUE TITLE
(solved) How to add multiple event dots per day

### ISSUE THREAD

**Issue by teneketo** [prolificinteractive/material-calendarview#753]
[Fairly new ti github, if this is not the correct way of spreading knowledge, do tell]

First off, you need a custom DotSpan class, which is just ever so slightly altered:

```
public class CustmMultipleDotSpan implements LineBackgroundSpan {


    private final float radius;
    private int[] color = new int[0];


    public CustmMultipleDotSpan() {
        this.radius = DEFAULT_RADIUS;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(int color) {
        this.radius = DEFAULT_RADIUS;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(float radius) {
        this.radius = radius;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(float radius, int[] color) {
        this.radius = radius;
        this.color = color;
    }

    @Override
    public void drawBackground(
            Canvas canvas, Paint paint,
            int left, int right, int top, int baseline, int bottom,
            CharSequence charSequence,
            int start, int end, int lineNum
    ) {

        int total = color.length > 5 ? 5 : color.length;
        int leftMost = (total - 1) * -10;

        for (int i = 0; i < total; i++) {
            int oldColor = paint.getColor();
            if (color[i] != 0) {
                paint.setColor(color[i]);
            }
            canvas.drawCircle((left + right) / 2 - leftMost, bottom + radius, radius, paint);
            paint.setColor(oldColor);
            leftMost = leftMost + 20;
        }
    }
}
```

You will also need an ever so slightly altered EventDecorator:

```
public class EventDecorator implements DayViewDecorator {

    private final int[] colors;
    private final HashSet<CalendarDay> dates;


    public EventDecorator(Collection<CalendarDay> dates, int[] colors) {
        //this.color = color;
        this.dates = new HashSet<>(dates);

        this.colors = colors;

    }


    public EventDecorator(List<MainActivity.Filter> filteredEvents) {
        //this.color = color;

        this.dates = new HashSet<>(filteredEvents.get(0).calDayArr);
        int[] colors = new int[1];
        colors[0] = filteredEvents.get(0).color;
        this.colors = colors;

    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return dates.contains(day);
    }

    @Override
    public void decorate(DayViewFacade view) {

        view.addSpan((new CustmMultipleDotSpan(5,colors)));

    }


}
```

And that is basically it.

Now find your calendarview in your activity, and give it some dates, and colors to show on those dates. In my particular case, I sort my dates in 5 different lists based on the amount of events per day, so you will end up with something like

`calendarView.addDecorator(new EventDecorator(threeEventDays,threeColors));`
Where threeEventDays is a Collection of CalendarDay
and threeColors is an int array 
int[] threeColors = {
                Color.rgb(0, 0, 255),
                Color.rgb(0, 255, 0),
                Color.rgb(255, 0, 0)};

It's nowhere near as ideal as it should be, but what it does is it expects an array of colors. Calculates the leftmost position, based on the array size, so for a  size one, the left most position is the middle dot we all know and love. For size 2 the left most position is -10, for size 3 it's -20 and so on. Then loops through and paints the dots.

It's limited to 5 event dots as it gets quite ugly above that, and though currently not on my roadmap, if it turns out to be a requirement I might add support for a second line of dots.

**Comment by quentin41500** [comment]
Thank you for this, closing.

**Comment by Jake21x** [comment]
Can you please post a blog or  a repository of  working demo for this. im having an issue making it.

**Comment by teneketo** [comment]
@Jake21x  What's the issue ?

**Comment by teneketo** [comment]
In your CalendarActivity, provided you have the dates in an object:

  Collection<CalendarDay> eventsToDisplayInTheCalendar= new ArrayList<>(); 

... 

int[] arrayOfColorDotsToDisplay={Color.rgb(255,0,0),Color.rgb(0,255,0),Color.rgb(255,255,0),Color.rgb(0,255,255),Color.rgb(0,0,255)};

//You show the evevnts on the calendar using this code, right
calendarView.addDecorator(new OneDayDecorator(arrayOfColorDotsToDisplay, eventsToDisplayInTheCalendar));

Then create these two classes into your project and reference them in your CalendarActivity:

CustmMultipleDotSpan.java


`import android.graphics.Canvas;
import android.graphics.Paint;
import android.text.style.LineBackgroundSpan;

public class CustmMultipleDotSpan implements LineBackgroundSpan {

    /**
     * Default radius used
     */
    public static final float DEFAULT_RADIUS = 3;

    private final float radius;
    private int[] color = new int[0];


    public CustmMultipleDotSpan() {
        this.radius = DEFAULT_RADIUS;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(int color) {
        this.radius = DEFAULT_RADIUS;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(float radius) {
        this.radius = radius;
        this.color[0] = 0;
    }


    public CustmMultipleDotSpan(float radius, int[] color) {
        this.radius = radius;
        this.color = color;
    }

    @Override
    public void drawBackground(
            Canvas canvas, Paint paint,
            int left, int right, int top, int baseline, int bottom,
            CharSequence charSequence,
            int start, int end, int lineNum
    ) {

        int total = color.length > 5 ? 5 : color.length;
        int leftMost = (total - 1) * -10;

        for (int i = 0; i < total; i++) {
            int oldColor = paint.getColor();
            if (color[i] != 0) {
                paint.setColor(color[i]);
            }
            canvas.drawCircle((left + right) / 2 - leftMost, bottom + radius, radius, paint);
            paint.setColor(oldColor);
            leftMost = leftMost + 20;
        }
    }
}`


OneDayDecorator.java

`import android.graphics.Color;
import android.graphics.ColorSpace;

import com.prolificinteractive.materialcalendarview.CalendarDay;
import com.prolificinteractive.materialcalendarview.DayViewDecorator;
import com.prolificinteractive.materialcalendarview.DayViewFacade;
import com.prolificinteractive.materialcalendarview.spans.DotSpan;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;

/**
 * Decorate a day by making the text big and bold
 */
public class OneDayDecorator implements DayViewDecorator {

    private final int[] colors;
    private final HashSet<CalendarDay> dates;


    public OneDayDecorator(Collection<CalendarDay> dates, int[] colors) {
        //this.color = color;
        this.dates = new HashSet<>(dates);

        this.colors = colors;
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {

        return dates.contains(day);
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.addSpan((new CustmMultipleDotSpan(9, colors)));
    }



}
`

**Comment by Jake21x** [comment]
Thanks for quick response :)  :+1:

**Comment by Jake21x** [comment]
Im using kotlin .. 
in your eventsToDisplayInTheCalendar array .. what kind of date format or string format we need to add in here  ?.

**Comment by teneketo** [comment]
@Jake21x I've updated my answer as it wasn't working it is now, check out the two classes again.

I don't think I've changed the collection type from the original, it's Collection<CalendarDay>

**Comment by Jake21x** [comment]
ok i manage to make you code work, how ever it always displaying 3 dots in the date
even the there only 1 event on that day .

**Comment by teneketo** [comment]
@Jake21x  Oh yeah I completely forgot to elaborate. The amount of dots is based on the array of colors sent. So I had 5 collections for each case, something like oneEventPerDayCollection, twoEventsPerDayCollection and so on.

I've deleted the loop code since as my project changed and I don't need multiple dots anymore, but I'd loop trough the entire collection of all the events.
if a day had one event it foes into oneEventPerDayCollection. If later another event was found for the same day, I'd remove the first one and add both to twoEventPerDayCollection and so on. Then actually have:

```
calendarView.addDecorator(new OneDayDecoratoroneDayArrayOfOfColorDotsToDisplay, oneDayEventsToDisplayInTheCalendar));
calendarView.addDecorator(new TwoDayDecoratoroneDayArrayOfOfColorDotsToDisplay, TwoDayEventsToDisplayInTheCalendar));
calendarView.addDecorator(new ThreeDayDecoratoroneDayArrayOfOfColorDotsToDisplay, ThreeDayEventsToDisplayInTheCalendar));
calendarView.addDecorator(new FourDayDecoratoroneDayArrayOfOfColorDotsToDisplay, FourDayEventsToDisplayInTheCalendar));
caleFiveDayEventsToDisplayInTheCalendar));
```

The main thing is, number of dots is based on the color array you pass. In theory if you remove the limit to 5 on this line  int total = color.length > 5 ? 5 : color.length; and pass 100 it'd draw them all, it's jsut that up to 5 look good.

It's not ideal but it worked ...

**Comment by Jake21x** [comment]
Ohh thats why :+1:  :) now i get it!. thank you verymuch teneketo!

**Comment by ashish-dhiman** [comment]
screen shot of the result:
I got this https://imgur.com/CBUlIW4

**Comment by h4rz** [comment]
@teneketo Tried your solution but it is not helping me in my scenario where 1 day has 1 event while the other day has 4 events so what it does is that it adds all the 4 colors on both the days
