### ISSUE TITLE
Day text becomes bold when using decorator of open circle. 

### ISSUE THREAD

**Issue by jiaxiongpi** [prolificinteractive/material-calendarview#761]
From attached screenshot, you can see the dates above open circle decorators are bold. If decorators are solid circles the dates are not bold. Please help! Thanks. 

![screenshot_20180507-112256](https://user-images.githubusercontent.com/14896702/39710018-97155f1a-51e9-11e8-9a96-8b7a5e6bb5be.png)
![screenshot_20180507-112917](https://user-images.githubusercontent.com/14896702/39710169-07e5dcb0-51ea-11e8-8d21-11fda3597e19.png)

**Comment by quentin41500** [comment]
I would check what your decorators is doing. Please provide more information in order to help. Maybe a sample app with just enough code to reproduce?

**Comment by jiaxiongpi** [comment]
Thanks Quentin for reply. The problem is resolved. The problem is on my
side.

Josh
