### ISSUE TITLE
about the checkedDrawable,please help me!

### ISSUE THREAD

**Issue by sugar0811** [prolificinteractive/material-calendarview#762]
If first setTileHeightDp (x)
Then setSelectedDate(today)
Then the CheckedDrawable backgroud will be larger and smaller
Like this
1. ![image](https://user-images.githubusercontent.com/18484054/40051681-37b6a822-586e-11e8-8c08-07141fcfeecc.png)
2. ![image](https://user-images.githubusercontent.com/18484054/40051697-4270d13e-586e-11e8-99fa-1f40239b0195.png)
Switch very quickly！
this's my code:
        Calendar calendar = Calendar.getInstance();
        binding.calendarView.setTileHeightDp(30);
        binding.calendarView.setSelectedDate(calendar.getTime());

i don't know why   please help me.

**Comment by quentin41500** [comment]
Maybe set the tile height in xml instead?
