### ISSUE TITLE
Add OnClickListener(calendarDay) on all days click event (includes disabled)

### ISSUE THREAD

**Issue by BimuratMukhtar** [prolificinteractive/material-calendarview#769]
Hi I want to prompt(show toast) users if they will click on disabled days, so i need to know this click event, please do this feature(Add OnClickListener(calendarDay) on all days(includes disabled)) available, i think more people need this.

**Comment by quentin41500** [comment]
I would recommend not disabling the days if you want to have a click listener. Disabling a day is meant to prevent any clicks.
