### ISSUE TITLE
Could you have add single-week view?

### ISSUE THREAD

**Issue by Koneey** [prolificinteractive/material-calendarview#77]
I love this library, it`s amazing~!!!
but I think the single-week view will be useful in calendar, I want use single-week in task management.

**Comment by dandc87** [comment]
Please see the reply to issue #49

**Comment by ticofab** [comment]
Thank you for this awesome library. Even tho it isn't in the plan, I would like to add my +1 for a weekly view feature. Maybe one day it will become part of the roadmap :)

**Comment by Thewhitelight** [comment]
+1
