### ISSUE TITLE
Configuration on demand

### ISSUE THREAD

**Issue by mgray88** [prolificinteractive/material-calendarview#785]
As it is now, if I try to compile the source without modifying anything, I get the following error:

```Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.```

Obviously I can fix it one of two ways modifying some files, but is there something different in your devel environment that I'm missing? I feel like I should be able to clone this and it should compile without the above error

**Comment by quentin41500** [comment]
This issue is not related to this library. a quick search should bring you to https://stackoverflow.com/questions/49990933/configuration-on-demand-is-not-supported-by-the-current-version-of-the-android-g or the gradle documentation
