### ISSUE TITLE
How to disable all the days before current day?

### ISSUE THREAD

**Issue by lakshyapunhani** [prolificinteractive/material-calendarview#793]
How to disable all the days before current day? I don't want the user to select any date before current day but he can see the previous days upto last month. How can i do this?

**Comment by quentin41500** [comment]
The wiki is a great place to start and the sample app has examples for this.

Check setting min date.

**Comment by lakshyapunhani** [comment]
calendarView.state().edit()
                .setMinimumDate(calender.getTime())
                .setMaximumDate(calendar1.getTime())
                .commit();

This is the way in the example to set minimum date and maximum date but in this way user can select all the dates visible But what i want is to set minimum date to 1st of last month but user should not be able to select the dates before the current day. How to disable selection of all those dates?
