### ISSUE TITLE
In weekview, OnMonthChangedListener's date object is wrong in marshmallow device 

### ISSUE THREAD

**Issue by VikramSenthil** [prolificinteractive/material-calendarview#799]
->The date object in the marshmallow device contains last day in the week, whereas, in other devices, the date object contains the first day in a week. 

->When calendar popups, In marshmallow it loads the previous week, not a current week.

Note: I set the start day to Monday

**Comment by quentin41500** [comment]
I tried fixing your issue but I could not reproduce it. I think your issues are related to the timezone issue that some folks were reporting.

> The date object in the marshmallow device contains last day in the week, whereas, in other devices, the date object contains the first day in a week.

I think you should only care about the month that is passed through this listener. Ideally, we shouldn't return a date but just a month, and only when it changes.

> When calendar popups, In marshmallow it loads the previous week, not a current week.

I just tried this as well and it seems to be working fine. I think this might be related to the timezone issues that some folks reported. 

All of this should be fix with #809. The release is not yet scheduled, but should be coming up so stay tuned.
