### ISSUE TITLE
How to change the dot on an event date to text or number

### ISSUE THREAD

**Issue by MinhDuc1997** [prolificinteractive/material-calendarview#802]
How to change the dot on an event date to text or number
My code, i use it to create a dot, it ok:
```
override fun decorate(view: DayViewFacade) {
            view.setBackgroundDrawable(resources.getDrawable(R.drawable.current_day))
            view.addSpan(DotSpan(5f, color))
        }
```
But i want to create a text or number instead of dot, i try use:
`view.addSpan("text here")`

Nothing is added.  Do we have any solution to this problem?

**Comment by quentin41500** [comment]
This question has been asked a couple of time. Please check previous responses thank you.

**Comment by MinhDuc1997** [comment]
i solved it

**Comment by MinhDuc1997** [comment]
But i have a problem. I put lunar date on each solar date, performance is very slow ....

**Comment by quentin41500** [comment]
Decorators are definitely not the best in terms of performance atm, we have a couple of issues that might help you, but improving it would requires more effort in general. Feel free to post your solution here on how you solved your first problem. Thanks, closing this now.
