### ISSUE TITLE
Week days disappear on orientation change

### ISSUE THREAD

**Issue by Mathbl** [prolificinteractive/material-calendarview#803]
The ability to show/hide week days in 1.6.0 seems to be broken. The week days disappear when changing orientation.

I'm speaking of this commit: https://github.com/prolificinteractive/material-calendarview/commit/28afa92143094ae982d9226278ecdd0362c0394f

It's reproducible in the sample app.

I didn't have a deep look at the code, but I see that `boolean showWeekDays;` will default to false, and might be the cause of the issue somewhere.

**Comment by quentin41500** [comment]
Thank you for reporting it, we'll work on it.
