### ISSUE TITLE
Different selectors

### ISSUE THREAD

**Issue by philippMarchenko** [prolificinteractive/material-calendarview#807]
Can i make several selectors whith different backgrounds?. Eg start and end date whith one background,and  other dates - other. Like this screen 

I try create two DayViewDecorator. But work only one

This decorator for start and end dates 
```
    class SelectorDecorator(dates: Collection<CalendarDay>,context : Context) : DayViewDecorator {

        private var selector: Drawable = context.resources.getDrawable(R.drawable.calendar_day_selector_foolday_between)
        private var context: Context? = null

        init {
            this.context = context
        }

        override fun shouldDecorate(day: CalendarDay): Boolean {
            return true
        }

        override fun decorate(view: DayViewFacade) {
            view.setSelectionDrawable(selector)
            view.addSpan(ForegroundColorSpan(ContextCompat.getColor(context!!, R.color.white)))

        }
    }
```
This decorator for dates between start and end. I insert into it list dates. But on calendar i see only first decorator
https://www.dropbox.com/s/bvpjz9qzn2kee18/Screenshot_1531419818.png?dl=0
`
class SelectorBetweenDaysDecorator(dates: Collection<CalendarDay>,context : Context) : DayViewDecorator {

        private var selector: Drawable? = null
        private val dates: ArrayList<CalendarDay> = ArrayList(dates)
        init {

            selector = context.resources.getDrawable(R.drawable.calendar_day_selector_foolday)
        }

        override fun shouldDecorate(day: CalendarDay): Boolean {

            return dates.contains(day)
        }

        override fun decorate(view: DayViewFacade) {
            view.setBackgroundDrawable(selector!!)
        }
    }`

https://www.dropbox.com/s/ot5ahu8hj1032hk/2412.png?dl=0

**Comment by quentin41500** [comment]
I just added a sample activity for this showing range decorator. Available here: https://github.com/prolificinteractive/material-calendarview/pull/806

**Comment by philippMarchenko** [comment]
Thanks !It works!
