### ISSUE TITLE
Bug - In weekMode navigation to CurrentDate not working

### ISSUE THREAD

**Issue by ViRuSs28** [prolificinteractive/material-calendarview#811]
- When i set calendar to weekmode by default it doesnt navigates to current week instead it navigates to a week prior to current week.
-  I didnt find any method to navigate calendar to particular date in weekmode so i use setCurrentDate()
method but this method also navigates calendar to week prior to date provide in setCurrentDate()

**Note** - i m facing above issues  on few device having Build.VERSION_CODES.M , Build.VERSION_CODES.N, Build.VERSION_CODES.O not all.
i.e why i m unable to track excalty which marshmellow or nougat or oreo device is having this issue.

**Comment by quentin41500** [comment]
That should be fixed with 2.0 coming up I believe. Stay tuned.
