### ISSUE TITLE
provide  method  tho disable for left and right swipe seperately

### ISSUE THREAD

**Issue by sajalgupta762** [prolificinteractive/material-calendarview#814]
How to stop Swiping gesture( left Swipe or right Swipe) on particular Month when we swipe pager inside Material Calendar view   .I have gone through the library but inside  CalendarPager Class you have override the an ScrollHorizontally(int direction)  method if we set pagingEnable variable false at paritcular month it will hang both right and left swipe but what i need  I just to want to  disable left Swipe at this particular month but i don't find any method for this  can you please provide me  disabling method for left and right swipe seperately

**Comment by quentin41500** [comment]
You can set `minimunDate` or `maximumDate` instead. That will box your calendar to those dates. You can change them on the fly.

**Comment by quentin41500** [comment]
You can also implement your own top bar and hide the current one! Closing this issue.
