### ISSUE TITLE
Weekday labels disappear when reopen calendar on a popover

### ISSUE THREAD

**Issue by nghlong93** [prolificinteractive/material-calendarview#817]
Hello,

Thank you for your hard work.
I'm encountering a problem, so, I need your help.
I put your calendar on a popover. The first time open it, everything seems to be OK. When I reopen the popover, the weekday labels of calendar are gone.
In debug mode, I can see that calendar.isShowWeekDays() is false.
I have set mcv_showWeekDays to true in XML.
I'm looking forward to hearing from you.
Thank you very much.

Long

**Comment by quentin41500** [comment]
This is the same as this one https://github.com/prolificinteractive/material-calendarview/issues/803

This has been fixed but is yet to be released. We will proceed for a release pretty soon with a couple of other fixes. Stay tuned.

**Comment by quentin41500** [comment]
Ok, `1.6.1` should be live with the fix @nghlong93. Thanks for your patience, let me know if it doesn't work. Closing this.

**Comment by nghlong93** [comment]
Thank you very much. I will test it again.
