### ISSUE TITLE
Something wrong with version 1.6.1

### ISSUE THREAD

**Issue by nghlong93** [prolificinteractive/material-calendarview#820]
Hello,

I'm using version 1.6.1.
When I use CalendarDay.today(), the string value of this function is '2018-06-24', although today is July 24th.
When I set current date by using setCurrentDate, the getCurrentDate always return '2018-6-1'.
Please help me again.
Thank you very much.

Long

**Comment by quentin41500** [comment]
That is normal: `Calendar.JULY = 6` as month are normalized from 0 to 11 with Calendar. Also it's currently working as intended, we are working on upgrading `java.time` which will use Month starting from 1 to 12.

https://github.com/prolificinteractive/material-calendarview/pull/809

**Comment by nghlong93** [comment]
OK I understand that.
What about the setCurrentDate? Whatever I set, it always turn into June 01

**Comment by quentin41500** [comment]
```
    /**
     * @return The current month shown, will be set to first day of the month
     */
    public CalendarDay getCurrentDate() {
        return adapter.getItem(pager.getCurrentItem());
    }
```

**Comment by quentin41500** [comment]
More like `getCurrentMonth()`

**Comment by nghlong93** [comment]
Thank you very much.
