### ISSUE TITLE
Calendar is not support RTL for Hebrew

### ISSUE THREAD

**Issue by Mahesh905** [prolificinteractive/material-calendarview#830]
Calendar is not support RTL for hebrew

**Comment by Mahesh905** [comment]
Are you talking about this https://github.com/prolificinteractive/material-calendarview/pull/783 but it won't work

**Comment by quentin41500** [comment]
Could you share a screenshot of what it is versus what you are expecting?

**Comment by Mahesh905** [comment]
![ltr mode](https://user-images.githubusercontent.com/41939961/43563042-cbffcd44-963d-11e8-8589-3fa75d7c2a0d.png)
in LTR Mode 
Expecting in RTL Mode
![rtl mode](https://user-images.githubusercontent.com/41939961/43563054-d9df623a-963d-11e8-9268-e322210b2713.png)

**Comment by Mahesh905** [comment]
Is it possible or not ?

**Comment by quentin41500** [comment]
Probably! Feel free to post a Pull Request with a solution if you have one.

**Comment by quentin41500** [comment]
Hey @Mahesh905, I think https://github.com/prolificinteractive/material-calendarview/pull/844/ should be much better for support of RTL. Could you try importing it or test the sample with Hebrew and let me know if that's what you are expecting?

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/releases/tag/2.0.0-RC2 Should contain better RTL support!

**Comment by Mahesh905** [comment]
not work

**Comment by quentin41500** [comment]
Yes, we have an open ticket for that. thanks for testing

**Comment by quentin41500** [comment]
https://github.com/prolificinteractive/material-calendarview/issues/851
