### ISSUE TITLE
How can I disable/red span on not selectable days in the calendar

### ISSUE THREAD

**Issue by ikasapoglu** [prolificinteractive/material-calendarview#836]
Hello, I show a green circle(span) on the users' can select days, but I want to disable the other days or mark with red span how can I do this ?

I'm using decorator : 

 myCalendar.addDecorator(new EventDecorator(getResources().getColor(R.color.material_green_300), calendarDays));

**Comment by quentin41500** [comment]
This question has been answered previously. There is tons of example in the sample and the wiki should help you figure out what you need.

You probably wanna keep track of your days in the decorator and only decorate if it's part of the list. You might need to `widget.invalidateDecorators()` which is expensive.
