### ISSUE TITLE
Week day color question

### ISSUE THREAD

**Issue by NmdOfficial** [prolificinteractive/material-calendarview#837]
Hello, 
I have two questions.

1.
In which file can I change the default color for the week days?
Current is the default color white.

2.
I added a possibility in WeekDayView.java to change the the title color programmatically.
(Because I need that way)

How can I access now my added code from the MaterialCalendarView.java ?

**Comment by quentin41500** [comment]
I commented all of that in the PR that you made. Please make sure you look first at the wiki and then the sample. They both contains tons of example, including one for your question.

We recommend changing the color for title, weekdays and days like so:

```
  <style name="CustomTextAppearance" parent="TextAppearance.AppCompat.Medium">
    <item name="android:textColor">@android:color/holo_red_dark</item>
  </style>
```

```
      app:mcv_headerTextAppearance="@style/CustomTextAppearance"
      app:mcv_dateTextAppearance="@style/CustomTextAppearance"
      app:mcv_weekDayTextAppearance="@style/CustomTextAppearance"
```

You can also set it programmatically:

```
  /**
   * @param resourceId The text appearance resource id.
   */
  public void setHeaderTextAppearance(int resourceId) {
    title.setTextAppearance(getContext(), resourceId);
  }
```
