### ISSUE TITLE
How can I make this calendar look like this?

### ISSUE THREAD

**Issue by dav-vendator** [prolificinteractive/material-calendarview#839]
![calendar](https://user-images.githubusercontent.com/33027983/43718235-a630ccf4-99a7-11e8-8515-481567e0d337.png)

**Comment by quentin41500** [comment]
Please take a look at the wiki and the sample app. They have tons of information and example for you to get started. I'm not here to do the job for you but to fix issues or improve the framework if something is not working properly. Thanks
