### ISSUE TITLE
Header Next and previous

### ISSUE THREAD

**Issue by Amit00a** [prolificinteractive/material-calendarview#842]
When I click on left arrow right arrow it shows yellow colour effect. How to remove this colour effect and add another colour effect on the arrow click.

**Comment by quentin41500** [comment]
Not sure which color effect you are referencing. If it's the ripple effect, then you should be able to change that with your theme I believe. Play around with the sample to see if you get different results. You can also change the arrow drawable all together.

**Comment by TriyambakGit** [comment]
@devamitkumartiwari were you able to solve the issue? I am also facing the same issue.
