### ISSUE TITLE
Question: Is there a possibility to paint all dates in range in one color, but paint selected dates from that range in other color

### ISSUE THREAD

**Issue by Progern** [prolificinteractive/material-calendarview#843]
So, basically I am facing next issue:

I have a range of dates (I need to show all dates, so **I can't use setMin and setMax date**, but some of them are unavailable to select) with minimum and maximum dates.

I need to paint all this date range with some color. But also I need to paint selected dates from this range in other color.

I haven't found respectively same issues here. It's not event an issue - it's a question.

Any help would be appreciated!

**Comment by quentin41500** [comment]
Thank you for pointing out the documentation. The sample should help you as well!
