### ISSUE TITLE
Binding extra data

### ISSUE THREAD

**Issue by ShrikantBadwaik-007** [prolificinteractive/material-calendarview#846]
Hi, amazing library.

I have a question, how do I bind some extra data along with dates on CalendarView.
Say I have list of Task object which contain a `created_date `parameter. I using that `created_date `param to create `CalendarDay `object which I using to create list of `CalendarDay `to show dots on CalendarView using `DayViewDecorator`.

```
List<CalendarDay> list = new ArrayList<>();
for (Task task: taskList) {
    if (task!= null) {
        CalendarDay calendarDay = CalendarDay.from(LocalDate.parse(task.getCreatedDate()));
         list.add(calendarDay);
    }       
}
calendarView.addDecorator(new ViewDecorator(list));
```
Is there any method to bind my task object with CalendarDay?
Thanks.

**Comment by quentin41500** [comment]
The calendar doesn't hold any other data than dates and is not intended for. You could always store then in a decorator maybe and fetch them from there, or handle them on your end.
