### ISSUE TITLE
How to change the selected dayView style

### ISSUE THREAD

**Issue by slma93** [prolificinteractive/material-calendarview#849]
public class SelectSpanDecorator implements DayViewDecorator {
    CalendarDay mSelectedDay;

    public SelectSpanDecorator(CalendarDay day) {
        this.mSelectedDay = day;
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return day == mSelectedDay;
    }

    @Override
    public void decorate(DayViewFacade view) {
        int strokeColor = Color.parseColor("#2E3135");
        int fillColor = Color.parseColor("#00ffffff");
        GradientDrawable gd = new GradientDrawable();
        gd.setColor(fillColor);
        gd.setGradientRadius(5);
        gd.setShape(GradientDrawable.OVAL);
        gd.setStroke(strokeWidth, strokeColor);
        view.setSelectionDrawable(gd);
    }
}

Please help check the above code, is there have any problems.When I run the code,the below problems appeared:
(1) the selected dayView's  calendar text disappeared
(2) the above gd.setGradientRadius() didn't work,I can't change the selected dayView's background drawable size.

How can I figure out above two problems.

**Comment by quentin41500** [comment]
Your fill color is transparent: `#00ffffff`

**Comment by quentin41500** [comment]
For the gradient, maybe create a custom drawable in xml and try getting it and setting it here.
