### ISSUE TITLE
Is possible to change selected day text color?

### ISSUE THREAD

**Issue by Marabita** [prolificinteractive/material-calendarview#85]
First thanks for the component, is excellent and very complete.

I'm trying to change the text color of the selected day and just found the setSelectionColor property but it changes the color of the round form.

**Comment by dandc87** [comment]
You can use `app:mcv_dateTextAppearance` (or the Java setter) to do this. I still need to document how this should be done, but for now you can copy the default implementation and modify as you need. Essentially you need to supply a `android:textColor` that is a color state list with your desired colors.

Add a style:
```xml
<style name="TextAppearance.MyCustomDay" parent="android:TextAppearance.DeviceDefault.Small">
    <item name="android:textSize">12sp</item>
    <item name="android:textColor">@color/my_custom_day_color</item>
</style>
```
and create `color/my_custom_day_color.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android"
    android:enterFadeDuration="@android:integer/config_shortAnimTime"
    android:exitFadeDuration="@android:integer/config_shortAnimTime">

    <item android:state_checked="true" android:color="SELECTION_COLOR" />
    <item android:state_pressed="true" android:color="SELECTION_COLOR" />
    <item android:state_enabled="false"  android:color="#808080" />
    <item android:color="@android:color/black" />
</selector>
```
then set `app:mcv_dateTextAppearance="@style/TextAppearance.MyCustomDay"`

**Comment by Marabita** [comment]
Hi @dandc87, Thanks for very fast response
I resolved using a decoration specific to change the selected date:

```java
public class OneDayDecorator implements DayViewDecorator {

    private CalendarDay date;

    public OneDayDecorator() {
        date = CalendarDay.today();
    }

    @Override
    public boolean shouldDecorate(CalendarDay day) {
        return date != null && day.equals(date);
    }

    @Override
    public void decorate(DayViewFacade view) {
        view.addSpan(new ForegroundColorSpan(Color.RED));
    }

    /**
     * We're changing the internals, so make sure to call {@linkplain MaterialCalendarView#invalidateDecorators()}
     */
    public void setDate(Date date) {
        this.date = CalendarDay.from(date);
    }
} 
```

And adding on calendar view:
```java
        mCalendarView.addDecorator(mSelectedDayDecorator);
```

**Comment by Studentessa** [comment]
@Marabita! your solution works for me! 
thanks!

**Comment by haiho** [comment]
thanks @Marabita  , I has been highlight current day, i happy

**Comment by Kharlos** [comment]
Great its work! and if u want use custom color I add context in OneDayDecorator and use

`        view.addSpan(new ForegroundColorSpan(mContext.getResources().getColor(R.color.celeste)));
`

**Comment by tsdmrfth** [comment]
Hello @Marabita . I am trying to use your solution but I guess I do not fully understand your solution. I created decorator class and set it to my calendar view but the result is still the same. Can you help me please..

**Comment by giancarloap** [comment]
Works like a charm. Thanks!

**Comment by Sathyan-Elangovan** [comment]
@marcello-marabita-mblabs  Thanks it works for me.
