### ISSUE TITLE
disable selection/deselection of any item onClick, without custom decorator?

### ISSUE THREAD

**Issue by ismaielsharif** [prolificinteractive/material-calendarview#852]
how to disable selection/deselection of any item onClick, without custom decorator?
i have studied documentation and sample code thoroughly, and didn't find the solution to disable selection/deselection on clicks of date. there id a class in sample code i which current date con not be edited by user, but it is implemented with custom decorator. i want to implement without decorator.

**Comment by quentin41500** [comment]
Decorators is the only way of disabling decorators like the documentation mentioned https://github.com/prolificinteractive/material-calendarview/wiki/Decorators `Set dates as disabled`.

If you are not willing to use decorators, then I'm not sure why you are trying to customize the calendar. This is the recommended way.

**Comment by ranjeetscience** [comment]
But if select the dates in range then the disable date also come in the list.How after disabling a particular date using decorator and if we select date in range,then that date should not come in the list.
