### ISSUE TITLE
Clickable dates

### ISSUE THREAD

**Issue by TidalAeon** [prolificinteractive/material-calendarview#858]
In the continuation of this [topic](https://github.com/prolificinteractive/material-calendarview/issues/328)...
I've tried to disable
`android:clickable="false"`, `android:contextClickable="false"`, `android:longClickable="false"`, `app:mcv_allowClickDaysOutsideCurrentMonth="false"` all of these attributes, but I can still select dates with touch (click). I can't call `setSelectionMode(SELECTION_MODE_NONE)` because my app select multiple dates programmatically and shows it on MCV.
So how can I disable dates from picking, being able to swipe months?

**Comment by quentin41500** [comment]
Programmatic usage and user input are tied together through the selectionMode, there is currently no way for you to have dates being selected while disabling user input. It currently only support one select day programmatically when in `SELECTION_MODE_NONE`. I would consider adding a feature to disable user input completely to dissociate from selectionMode. Feel free to submit a PR for it.

**Comment by TidalAeon** [comment]
Ok, thanks!
