### ISSUE TITLE
Custom background selector

### ISSUE THREAD

**Issue by Kyxar** [prolificinteractive/material-calendarview#863]
Hi, 
I want to change the default background selector but I can't find the way to use the information on this documentation page below:
https://github.com/prolificinteractive/material-calendarview/blob/master/docs/CUSTOM_SELECTORS.md#drawables

Where do i write the link to my custom background selector? I try 
```
<com.prolificinteractive.materialcalendarview.MaterialCalendarView
app:mcv_selectionColor="@drawable/default_materialcalendar_selector

```
but it seams to required a color ressources only:
`android.content.res.Resources$NotFoundException: File res/drawable/default_materialcalendar_selector.xml from color state list resource ID`

Thanks for help 

i'm using the Version 1.5.0

**Comment by quentin41500** [comment]
The background needs to be passed to a decorator in order to specify which days it should apply to. More here:
https://github.com/prolificinteractive/material-calendarview/wiki/Decorators

**Comment by TTMOSALA** [comment]
There really should be a simpler way to just change the drawable for selected day without creating a decorator. The functionality is already there why should it be recreated.
