### ISSUE TITLE
Other languages' months aren't capitalized

### ISSUE THREAD

**Issue by polpg** [prolificinteractive/material-calendarview#869]
- [ ] When changing the language to Spanish or Catalan (I only tried it with those two) the month's name starts with lower case instead of uppercase (as it does with English). See image:![screenshot_1536937954](https://user-images.githubusercontent.com/20172920/45559674-5ef16c80-b843-11e8-8173-3cdcc7164b06.png)

- [ ] Also, it doesn't update until you restart the activity:
![screenshot_1536937939](https://user-images.githubusercontent.com/20172920/45559681-644eb700-b843-11e8-8472-7d06d7311e75.png)

**Comment by polGamer29** [comment]
It also starts with lower case in French (possibly more languages).

**Comment by quentin41500** [comment]
I do believe only english capitalize months. If the translation isn't fitting your need, you can always provide your own, but I don't think this is an issue on MCV!
