### ISSUE TITLE
Failing to add to Android Studio

### ISSUE THREAD

**Issue by gibsonndemanga** [prolificinteractive/material-calendarview#884]
I have followed the setting up instructions to the dot but its failing to add material-calendarview to android studio.

Could not find com.github.prolificinteractive:material-calendarview:2.0.0.
Searched in the following locations:
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.pom
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.jar
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/google/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.pom
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/google/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.jar
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/android/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.pom
    file:/C:/Users/Gibson T Ndemanga/AppData/Local/Android/Sdk/extras/android/m2repository/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.jar
    https://dl.google.com/dl/android/maven2/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.pom
    https://dl.google.com/dl/android/maven2/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.jar
    https://jcenter.bintray.com/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.pom
    https://jcenter.bintray.com/com/github/prolificinteractive/material-calendarview/2.0.0/material-calendarview-2.0.0.jar
Required by:
    project :app

**Comment by quentin41500** [comment]
Did you forget step 1?

Step 1. Add the JitPack repository to your build file

```groovy
allprojects {
  repositories {
    ...
    maven { url 'https://jitpack.io' }
  }
}
```

Step 2. Add the dependency

```groovy
dependencies {
  implementation 'com.github.prolificinteractive:material-calendarview:${version}'
}
```

**Comment by cengizahmet** [comment]
old dependency name: 
'com.prolificinteractive:material-calendarview:${version}'
new dependency name:
'com.github.prolificinteractive:material-calendarview:${version}'

**Comment by SilvioRogerio** [comment]
'com.github.prolificinteractive:material-calendarview:${version}' no working for me, i need remove ${version} and change with 1.5.0

**Comment by cengizahmet** [comment]
> 'com.github.prolificinteractive:material-calendarview:${version}' no working for me, i need remove ${version} and change with 1.5.0

You can use 2.0.0

**Comment by SilvioRogerio** [comment]
Thanks!
