### ISSUE TITLE
Failed to resolve: com.github.prolificinteractive:material-calendarview:1.4.3

### ISSUE THREAD

**Issue by notnotme** [prolificinteractive/material-calendarview#887]
in build.gradle
allprojects {
        ....
        maven { url "https://jitpack.io" }
        ....
}

in app.gradle:
    implementation 'com.github.prolificinteractive:material-calendarview:1.4.3'

Result:
Failed to resolve: com.github.prolificinteractive:material-calendarview:1.4.3

Same with 1.4.0, 1.4.1, 1.4.2...

I guess something is wrong maybe gradle version or I don't know why.

**Comment by quentin41500** [comment]
It changed for this at https://github.com/prolificinteractive/material-calendarview/releases/tag/1.5.0

before it was implementation 'com.prolificinteractive:material-calendarview:1.4.3'

**Comment by karthickmurugesa** [comment]
I have same problem now while using Failed to resolve: com.github.prolificinteractive:material-calendarview:2.0  So I have changed the gradle 
**com.github.prolificinteractive:material-calendarview:2.0.0**

**Comment by akshaytaru2007** [comment]
Same problem

**Comment by krunal8055** [comment]
I have also same problem But I just change the version 2.0.0 and It works.

**implementation 'com.github.prolificinteractive:material-calendarview:2.0.0'**

Version 2.0.0 works For me!

**Comment by Ediphonce** [comment]
Worked for me as well!
Changed **implementation 'com.github.prolificinteractive:material-calendarview:2.0'**
To **implementation 'com.github.prolificinteractive:material-calendarview:2.0.0'**

**Comment by mbob001** [comment]
> 
> 
> Worked for me as well! Changed **implementation 'com.github.prolificinteractive:material-calendarview:2.0'** To **implementation 'com.github.prolificinteractive:material-calendarview:2.0.0'**

Now, not working same error: **Failed to resolve: com.github.prolificinteractive:material-calendarview:2.0.0**

**Comment by DBXJes** [comment]
For some reason, doing some research, the repositories today can't find the package by looking for it.
Searching for more maintained repositories **I was able** to find older versions but they allowed me to make use of this API.
```
// https://mvnrepository.com/artifact/com.prolificinteractive/material-calendarview
implementation group: 'com.prolificinteractive', name: 'material-calendarview', version: '1.4.3'
```
@notnotme
