### ISSUE TITLE
I want to only disable past date how?

### ISSUE THREAD

**Issue by shubhamkhuva** [prolificinteractive/material-calendarview#895]
val today = LocalDate.now()
        calendarView.state().edit()
                .setMinimumDate(CalendarDay.from(today))
                .commit();

This code remove past date but i want display but disable

**Comment by shubhamkhuva** [comment]
?

**Comment by quentin41500** [comment]
Use decorators. https://github.com/prolificinteractive/material-calendarview/wiki/Decorators

There is a section for setting days as disabled.
