### ISSUE TITLE
How to get day selected (long) ?

### ISSUE THREAD

**Issue by Thien658jjh** [prolificinteractive/material-calendarview#898]
> calendarDay.getDate().toEpochDay() 

that method is always return value < 0 ??

**Comment by Thien658jjh** [comment]
Is mothod calendarDay.getDate().getTime() has been removed ?

**Comment by Thien658jjh** [comment]
Yeah, and I've just jumped down to version 1.6.
I hope that you will add method getTime in the future. Thank you

**Comment by quentin41500** [comment]
`calendarDay.getDate()` is now returning a LocalDate as of https://github.com/prolificinteractive/material-calendarview/releases/tag/2.0.0. 

Please refer to the class documentation instead https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html, it should have what you need.

There is no plan on adding new API to the CalendarDay atm.
