### ISSUE TITLE
DayTextView is off center

### ISSUE THREAD

**Issue by NeoDigi** [prolificinteractive/material-calendarview#9]
![screenshot_2015-03-02-11-43-33](https://cloud.githubusercontent.com/assets/6572589/6439341/2068ed6a-c0d2-11e4-8e29-cc6bbb008a22.png)

Look like the gravity is set on the LEFT and not CENTER, the circle for the selected date allign with the name of the day, but everyday day are off.

**Comment by NeoDigi** [comment]
I found the source of this bug:
android:supportsRtl="true" in the manifest will cause it.

**Comment by dandc87** [comment]
Thanks @NeoDigi for tracking down the cause of the bug!

I added `setTextAlignment(TEXT_ALIGNMENT_CENTER);` to both DayView and WeekDayView to keep text centered. I will release the update to Maven Central by the weekend.

**Comment by NeoDigi** [comment]
Thank you, It works perfectly now
