### ISSUE TITLE
Disable click day

### ISSUE THREAD

**Issue by Travis9011** [prolificinteractive/material-calendarview#90]
Hello! Is possible, not allow a click on each day of the calendar?
Thanks

**Comment by dandc87** [comment]
Are you looking to disable selecting any day, or individual days?

You can disable individual days by using decorators. See `DisableDaysActivity.java` in the sample app.

There currently isn't a way to disable selection in general. I was planning on implementing this along with #52.

**Comment by dandc87** [comment]
This will make it into the 1.0 release. Please test out the beta (see #131)

**Comment by jxuewill** [comment]
Is there a way to disable clicking but make the date visible?
