### ISSUE TITLE
How to achieve the current effect？

### ISSUE THREAD

**Issue by merhong2012** [prolificinteractive/material-calendarview#91]
I want to give today's date plus a selected effect。like this
![qq 20150723134933](https://cloud.githubusercontent.com/assets/7665010/8843942/e4ebedc4-3141-11e5-9132-9568c10fa1b5.png)

**Comment by dandc87** [comment]
You can use a decorator. Please look at `BasicActivityDecorated` in the sample app. You are looking to make something similar to the `OneDayDecorator` that uses `DayViewFacade.setBackgroundDrawable()` instead of setting spans.

**Comment by merhong2012** [comment]
Thank you very much！！:)
