### ISSUE TITLE
Error while adding library with appCompact-v7:28.0.0

### ISSUE THREAD

**Issue by thezukkino** [prolificinteractive/material-calendarview#914]
Hello,
I've created a new project with appCompact-v7:28.0.0 impl on my gradle.
If I try to add your library v.2.0.0 I get the error attached.

![import](https://user-images.githubusercontent.com/29436502/50724395-11985400-10ed-11e9-8f12-525bc36393e7.png)

If there a way to solve this issue?

Best regards

**Comment by aldebaran798** [comment]
Add this line to the graddle file.
implementation 'com.android.support:support-v4:28.0.0'

**Comment by thezukkino** [comment]
The error disappears.
Great thanks.
