### ISSUE TITLE
Design preview in android studio doesn't work with library.

### ISSUE THREAD

**Issue by Killain** [prolificinteractive/material-calendarview#918]
![issue](https://user-images.githubusercontent.com/36140653/51438436-3845b580-1cbd-11e9-8a11-d32ab4f051b1.png)

Hello! I expected to see the changes in design mode, but xml doesn't seem to show library view at all. Can you help me with this?

**Comment by quentin41500** [comment]
Duplicate https://github.com/prolificinteractive/material-calendarview/issues/876
