### ISSUE TITLE
Selected Date Drawable

### ISSUE THREAD

**Issue by birfincankafein** [prolificinteractive/material-calendarview#92]
Thank you for creating this amazing library. Its very useful. 

I want to assign selected date to drawable. I want to assign circle border. But all I can do is assign color. How can I assign circle border to selected date? 

All I can do is: 
```java
		materialCalendarView.setSelectionColor( /*Some Color Here*/ );

**Comment by dandc87** [comment]
You will have to use a decorator to supply a custom selector. Please look at the `BasicActivityDecorated` in the sample application. Specifically the `MySelectorDecorator` is what you want. Make sure the drawable you use responds to pressed and checked.
