### ISSUE TITLE
Current date indication

### ISSUE THREAD

**Issue by Shajeel-Afzal** [prolificinteractive/material-calendarview#93]
Is it possible to set color for the current date? Great library.

**Comment by dandc87** [comment]
You can use a decorator. Please look at `BasicActivityDecorated` in the sample app. You are looking to make something similar to the `OneDayDecorator` that uses `DayViewFacade.setBackgroundDrawable()` instead of setting spans.

**Comment by Shajeel-Afzal** [comment]
Thanks it worked.

**Comment by aldebaran798** [comment]
@Shajeel-Afzal you solved the problem? I have same issue
