### ISSUE TITLE
Unable to Instantiate Class

### ISSUE THREAD

**Issue by therealestkevin** [prolificinteractive/material-calendarview#931]
I am getting this error upon simply placing a calendarview in an activity. Any feedback would help. Thanks
![image](https://user-images.githubusercontent.com/30887959/52835845-20373b00-309d-11e9-9b8c-278941a069a2.png)

![image](https://user-images.githubusercontent.com/30887959/52835883-45c44480-309d-11e9-810d-90643e424f5e.png)

Here is my dependency Setup, I have also enabled Jetifier and AndroidX
![image](https://user-images.githubusercontent.com/30887959/52835892-4e1c7f80-309d-11e9-80a9-f888fee1f537.png)

![image](https://user-images.githubusercontent.com/30887959/52835905-55438d80-309d-11e9-9877-bf08829ff697.png)

**Comment by vajjasivateja** [comment]
how did you solve this error?
