### ISSUE TITLE
Events on a date indication 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [prolificinteractive/material-calendarview#94]
Hi, 

There should be option to indicate that whether a specific date has any events or not. If there will be event it should show a little circle under the date. I think it will make this library more sweet. 

Thanks.

**Comment by dandc87** [comment]
You can use a decorator. Please look at BasicActivityDecorated in the sample app. You are looking to make something similar to the EventDecorator that uses the `DotSpan` class provided in the library.
