### ISSUE TITLE
exception occured

### ISSUE THREAD

**Issue by flamenvo** [prolificinteractive/material-calendarview#95]
i use  clearSelection   in   onDateChanged()   an exception occured

**Comment by dandc87** [comment]
@flamenvo could you post the stack trace?

**Comment by flamenvo** [comment]
@dandc87   thanks!        i know why the  exception occured,   when  i use clearSelection in onDateChanged(), onDateChanged()    will  execute    twice.

**Comment by dandc87** [comment]
@flamenvo Thanks, I'll look into this! Why are you clearing the day when it changes? If you are trying to prevent the user from selecting dates, you can use a decorator (look at the `PrimeDayDisableDecorator` in the `DisableDaysActivity` sample).

**Comment by dandc87** [comment]
@flamenvo I believe this is fixed in 1.0+. Can you test this with the latest release?

**Comment by flamenvo** [comment]
@dandc87  After testing the latest release  this  problem does not occur.  thanks!

**Comment by dandc87** [comment]
:tada:
