### ISSUE TITLE
Change color of past dates only

### ISSUE THREAD

**Issue by dzafiri** [prolificinteractive/material-calendarview#952]
Is there a way to set different color to past dates ?

**Comment by mandricmihai** [comment]
Use a decorator

**Comment by munstein** [comment]
You need to create a _DayViewDecorator_ like the code below(replace the R.color.grey with a color you want):

`class PastDaysDecorator(private val context: Context) : DayViewDecorator {

    override fun shouldDecorate(day: CalendarDay): Boolean {
        return day.isBefore(CalendarDay.today())
    }

    override fun decorate(view: DayViewFacade) {
        view.addSpan(ForegroundColorSpan(ContextCompat.getColor(context, R.color.grey)))
    }
}`

**Comment by dzafiri** [comment]
> You need to create a _DayViewDecorator_ like the code below(replace the R.color.grey with a color you want):
> 
> `class PastDaysDecorator(private val context: Context) : DayViewDecorator {
> 
> ```
> override fun shouldDecorate(day: CalendarDay): Boolean {
>     return day.isBefore(CalendarDay.today())
> }
> 
> override fun decorate(view: DayViewFacade) {
>     view.addSpan(ForegroundColorSpan(ContextCompat.getColor(context, R.color.grey)))
> }
> ```
> 
> }`

Thanks!!! you rock
