### ISSUE TITLE
Android2.3

### ISSUE THREAD

**Issue by merhong2012** [prolificinteractive/material-calendarview#96]
Hello, thank you very much busy schedule to answer questions！

I want to use it in my project, but requires a minimum is API8, is there any way you can let me run on android 2.3?

**Comment by dandc87** [comment]
Hey @merhong2012, the library was designed to work for 4.0+ only, and I don't have time to audit the code and make sure everything works correctly for Gingerbread. I'm not opposed to supporting before 4.0, so if someone wants to do the work and open a pull request, it would be appreciated.
