### ISSUE TITLE
How to set the calendar to a date got from user??

### ISSUE THREAD

**Issue by mjwaghmare** [prolificinteractive/material-calendarview#960]
want to set the calendar or show that date to user when he enter a date in the edittext..

**Comment by StuStirling** [comment]
You will need to parse the date entered into the `EditText` by the user. Have a look at `org.threeten.bp.format.DateTimeFormatter` to do this.

Once you can get a `LocalDate` object from it you can then set the date of the calendar. 
`setCurrentDate(localDate)`. Alternatively, you may want to call `setSelectedDate` if you want to make it visible to the user as well

**Comment by mjwaghmare** [comment]
> 
> 
> You will need to parse the date entered into the `EditText` by the user. Have a look at `org.threeten.bp.format.DateTimeFormatter` to do this.
> 
> Once you can get a `LocalDate` object from it you can then set the date of the calendar.
> `setCurrentDate(localDate)`. Alternatively, you may want to call `setSelectedDate` if you want to make it visible to the user as well

thanks...got it :)
