### ISSUE TITLE
Different backgrounds for days

### ISSUE THREAD

**Issue by rjborba** [prolificinteractive/material-calendarview#97]
Hey, I wrote two "addDecoration" which adds two differents types of circles arround some days. I need somehow change the color of the selected day (default Blue) when the selected day is one which has this Decorate (one of the rings). It's possible?

I already tryed create a list to save the days which should be decorated and on the OnDateChange change the Selector color if the day should be decorated. The problem is that the transition is not soft as the original.

**Comment by dandc87** [comment]
@rjborba are you referring to the subtle fade of the selector? That is done by setting an exit fade duration on your selector drawable (or any supported `DrawableContainer`):

```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android"
    android:exitFadeDuration="@android:integer/config_shortAnimTime" >
    ...
</selector>
```

or

```java
myStateListDrawable.setExitFadeDuration(fadeTimeInMs);
```

**Comment by rjborba** [comment]
I don't know if I'm expressing right but the selector fade is working perfectly. The problem appear just when I change the selector color. There is no fade out in this situation.

I'm doing something like this:

              // onDateChanged
                if(selectionCurrentColor !=  colorA && a.contains(calendarDay.getDay())) {
                    calendar.setSelectionColor(colorA);
                }
                else if(selectionCurrentColor != defaultColor){
                    calendar.setSelectionColor(defaultColor);
                }

and if setSelectionColor() is called, there is not smooth fadeout between the last selected date and the selected date.

**Comment by dandc87** [comment]
Oh, I get it now. There isn't a fade animation because you're changing the selection color while the user is changing the selection. This is happening because when you change selection, a new drawable is created, instead of mutating the old one.

**Comment by rjborba** [comment]
Knowing that, there is any workarround for my situation?

Em 05/08/2015 17:54, Adam Koski <notifications@github.com> escreveu:
Oh, I get it now. There isn't a fade animation because you're changing the selection color while the user is changing the selection. This is happening because when you change selection, a new drawable is created, instead of mutating the old one.

---

**Comment by dandc87** [comment]
I think if you were to use decorators to set different colored selectors, instead of calling `setSelectionColor()`, it would would fade correctly. Assuming your custom selectors use the fade duration I mentioned above.
