### ISSUE TITLE
Show disabled days? 

### ISSUE THREAD

**Issue by ThexXTURBOXx** [prolificinteractive/material-calendarview#989]
Hello, is it possible to show disabled days, but greyed out and unclickable?
I have already tried disabling the day and adding a Span after that, but that doesn't work as disabling a day just hides that day completely.
I have also searched for Events or other methods to make the date unclickable and then adding a Span, but I didn't find anything like that.
Is there a way?

**Comment by venky1893** [comment]
app:mcv_showOtherDates="all"

**Comment by SenghaniMaulik** [comment]
> app:mcv_showOtherDates="all"

Thank you @venky1893  , its working

**Comment by ThexXTURBOXx** [comment]
It's been a long time, but I was able to solve this issue somehow.
For reference, see here:
https://github.com/ThexXTURBOXx/studip-app-uni-passau/blob/master/app/src/main/java/studip_uni_passau/femtopedia/de/unipassaustudip/activities/MensaActivity.java#L94
and here:
https://github.com/ThexXTURBOXx/studip-app-uni-passau/blob/master/app/src/main/res/layout/content_mensa.xml#L11

**Comment by fabiorbap** [comment]
None of these solutions worked for me...
      
```
binding.calendarView.addDecorator(object : DayViewDecorator {
            override fun shouldDecorate(day: CalendarDay?): Boolean {
                return true
            }

            override fun decorate(view: DayViewFacade?) {
                view?.addSpan(
                    ForegroundColorSpan(
                        ContextCompat.getColor(
                            context,
                            R.color.red
                        )
                    )
                )
            }
        })
        state().edit().setMinimumDate(CalendarDay.today())
            .commit()
```


```
<com.prolificinteractive.materialcalendarview.MaterialCalendarView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/calendar_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:mcv_showOtherDates="all" />
```
